<?xml version="1.0" encoding='utf-8'?>

<!--
	verbs-ro.xml - List of Romanian verbs with their conjugation template.
	The templates were generated by SekouD using Unsupervised Learning,
	and follow the xml schema defined by Pierre Sarrazin in conjug_manager.

	Copyright (C) 2018 Sekou Diao <https://github.com/SekouD>
	Copyright (C) 2003-2016 Pierre Sarrazin <http://sarrazip.com/>

	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with this program; if not, write to the Free Software
	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
	02110-1301, USA.
-->

<!DOCTYPE verbs-ro [
    <!ELEMENT verbs-ro (v)+>
    <!ATTLIST verbs-ro
      xmlns CDATA #FIXED ''>

    <!ELEMENT v (i,t)> <!-- verb's conjugation information (infinitive, radical) -->
    <!ATTLIST v
      xmlns CDATA #FIXED ''>

    <!ELEMENT i (#PCDATA)>  <!-- infinitive -->
    <!ATTLIST i
      xmlns CDATA #FIXED ''>

    <!ELEMENT t (#PCDATA)> <!-- template (radical:termination) -->
    <!ATTLIST t
        xmlns CDATA #FIXED ''>
]>

<verbs-ro>

<v><i>abate</i>		<t>ab:ate</t></v>
<v><i>abatoriza</i>		<t>dans:a</t></v>
<v><i>abcede</i>		<t>abce:de</t></v>
<v><i>abdica</i>		<t>abdic:a</t></v>
<v><i>abduce</i>		<t>abdu:ce</t></v>
<v><i>abeceda</i>		<t>abeced:a</t></v>
<v><i>abhora</i>		<t>dans:a</t></v>
<v><i>abilita</i>		<t>dans:a</t></v>
<v><i>abjudeca</i>		<t>abdic:a</t></v>
<v><i>abjura</i>		<t>abdic:a</t></v>
<v><i>ablacta</i>		<t>dans:a</t></v>
<v><i>ablega</i>		<t>able:ga</t></v>
<v><i>abnega</i>		<t>abdic:a</t></v>
<v><i>aboli</i>		<t>fer:i</t></v>
<v><i>abona</i>		<t>dans:a</t></v>
<v><i>aborda</i>		<t>dans:a</t></v>
<v><i>abraza</i>		<t>dans:a</t></v>
<v><i>abrevia</i>		<t>abrevi:a</t></v>
<v><i>abroga</i>		<t>abdic:a</t></v>
<v><i>abrutiza</i>		<t>dans:a</t></v>
<v><i>absenta</i>		<t>dans:a</t></v>
<v><i>absolutiza</i>		<t>dans:a</t></v>
<v><i>absolvi</i>		<t>fer:i</t></v>
<v><i>absorbi</i>		<t>abso:rbi</t></v>
<v><i>abstractiza</i>		<t>dans:a</t></v>
<v><i>abstrage</i>		<t>abstr:age</t></v>
<v><i>abunda</i>		<t>abund:a</t></v>
<v><i>aburca</i>		<t>abdic:a</t></v>
<v><i>aburi</i>		<t>fer:i</t></v>
<v><i>abuza</i>		<t>dans:a</t></v>
<v><i>abzice</i>		<t>abzi:ce</t></v>
<v><i>abţigui</i>		<t>locui:</t></v>
<v><i>abţine</i>		<t>pu:ne</t></v>
<v><i>academiza</i>		<t>dans:a</t></v>
<v><i>acapara</i>		<t>dans:a</t></v>
<v><i>accede</i>		<t>abce:de</t></v>
<v><i>accelera</i>		<t>dans:a</t></v>
<v><i>accentua</i>		<t>dans:a</t></v>
<v><i>accepta</i>		<t>accep:ta</t></v>
<v><i>accesa</i>		<t>dans:a</t></v>
<v><i>accesibiliza</i>		<t>dans:a</t></v>
<v><i>accidenta</i>		<t>dans:a</t></v>
<v><i>acetifica</i>		<t>abdic:a</t></v>
<v><i>achiesa</i>		<t>dans:a</t></v>
<v><i>achita</i>		<t>accep:ta</t></v>
<v><i>achiziţiona</i>		<t>dans:a</t></v>
<v><i>acidifica</i>		<t>abdic:a</t></v>
<v><i>acidula</i>		<t>dans:a</t></v>
<v><i>acila</i>		<t>dans:a</t></v>
<v><i>aciola</i>		<t>dans:a</t></v>
<v><i>acira</i>		<t>abdic:a</t></v>
<v><i>aciua</i>		<t>dans:a</t></v>
<v><i>aclama</i>		<t>abdic:a</t></v>
<v><i>aclimata</i>		<t>dans:a</t></v>
<v><i>aclimatiza</i>		<t>dans:a</t></v>
<v><i>acolisi</i>		<t>fer:i</t></v>
<v><i>acomoda</i>		<t>dans:a</t></v>
<v><i>acompania</i>		<t>dans:a</t></v>
<v><i>aconta</i>		<t>dans:a</t></v>
<v><i>acoperi</i>		<t>acop:eri</t></v>
<v><i>acorda</i>		<t>acor:da</t></v>
<v><i>acosta</i>		<t>dans:a</t></v>
<v><i>acredita</i>		<t>dans:a</t></v>
<v><i>acri</i>		<t>fer:i</t></v>
<v><i>acromatiza</i>		<t>dans:a</t></v>
<v><i>acroșa</i>		<t>dans:a</t></v>
<v><i>activa</i>		<t>dans:a</t></v>
<v><i>activiza</i>		<t>dans:a</t></v>
<v><i>actualiza</i>		<t>dans:a</t></v>
<v><i>acufunda</i>		<t>acor:da</t></v>
<v><i>acultura</i>		<t>dans:a</t></v>
<v><i>acumula</i>		<t>dans:a</t></v>
<v><i>acupla</i>		<t>dans:a</t></v>
<v><i>acutiza</i>		<t>dans:a</t></v>
<v><i>acuza</i>		<t>abdic:a</t></v>
<v><i>acăţa</i>		<t>ac:ăţa</t></v>
<v><i>acăţăra</i>		<t>ac:ăţăra</t></v>
<v><i>acţiona</i>		<t>dans:a</t></v>
<v><i>adapta</i>		<t>dans:a</t></v>
<v><i>ademeni</i>		<t>fer:i</t></v>
<v><i>adera</i>		<t>abdic:a</t></v>
<v><i>adeveri</i>		<t>fer:i</t></v>
<v><i>adia</i>		<t>adi:a</t></v>
<v><i>adiţiona</i>		<t>dans:a</t></v>
<v><i>adjectiva</i>		<t>dans:a</t></v>
<v><i>adjectiviza</i>		<t>dans:a</t></v>
<v><i>adjudeca</i>		<t>abdic:a</t></v>
<v><i>adjura</i>		<t>abdic:a</t></v>
<v><i>administra</i>		<t>dans:a</t></v>
<v><i>admira</i>		<t>abdic:a</t></v>
<v><i>admite</i>		<t>admi:te</t></v>
<v><i>admonesta</i>		<t>dans:a</t></v>
<v><i>adnota</i>		<t>dans:a</t></v>
<v><i>adopta</i>		<t>accep:ta</t></v>
<v><i>adora</i>		<t>abdic:a</t></v>
<v><i>adormi</i>		<t>do:rmi</t></v>
<v><i>adresa</i>		<t>dans:a</t></v>
<v><i>adsorbi</i>		<t>abso:rbi</t></v>
<v><i>aduce</i>		<t>adu:ce</t></v>
<v><i>adula</i>		<t>dans:a</t></v>
<v><i>adulmeca</i>		<t>abdic:a</t></v>
<v><i>adultera</i>		<t>dans:a</t></v>
<v><i>adumbri</i>		<t>fer:i</t></v>
<v><i>aduna</i>		<t>abdic:a</t></v>
<v><i>adurmeca</i>		<t>abdic:a</t></v>
<v><i>adverbializa</i>		<t>dans:a</t></v>
<v><i>adânci</i>		<t>fer:i</t></v>
<v><i>adăpa</i>		<t>abdic:a</t></v>
<v><i>adăposti</i>		<t>fer:i</t></v>
<v><i>adăsta</i>		<t>accep:ta</t></v>
<v><i>adăuga</i>		<t>ad:ăuga</t></v>
<v><i>aera</i>		<t>dans:a</t></v>
<v><i>aerisi</i>		<t>fer:i</t></v>
<v><i>afanisi</i>		<t>fer:i</t></v>
<v><i>afecta</i>		<t>dans:a</t></v>
<v><i>afera</i>		<t>dans:a</t></v>
<v><i>afierosi</i>		<t>fer:i</t></v>
<v><i>afilia</i>		<t>abrevi:a</t></v>
<v><i>afina</i>		<t>dans:a</t></v>
<v><i>afirma</i>		<t>abdic:a</t></v>
<v><i>afișa</i>		<t>dans:a</t></v>
<v><i>afla</i>		<t>afl:a</t></v>
<v><i>aflui</i>		<t>locui:</t></v>
<v><i>afoniza</i>		<t>dans:a</t></v>
<v><i>afreta</i>		<t>dans:a</t></v>
<v><i>africaniza</i>		<t>dans:a</t></v>
<v><i>afronta</i>		<t>accep:ta</t></v>
<v><i>afrunta</i>		<t>accep:ta</t></v>
<v><i>afuma</i>		<t>abdic:a</t></v>
<v><i>afunda</i>		<t>acor:da</t></v>
<v><i>afurca</i>		<t>abdic:a</t></v>
<v><i>afurisi</i>		<t>fer:i</t></v>
<v><i>afâna</i>		<t>dans:a</t></v>
<v><i>agasa</i>		<t>dans:a</t></v>
<v><i>ageri</i>		<t>fer:i</t></v>
<v><i>agesti</i>		<t>fer:i</t></v>
<v><i>aghesmui</i>		<t>locui:</t></v>
<v><i>agita</i>		<t>accep:ta</t></v>
<v><i>aglomera</i>		<t>dans:a</t></v>
<v><i>aglutina</i>		<t>dans:a</t></v>
<v><i>agonisi</i>		<t>fer:i</t></v>
<v><i>agoniza</i>		<t>dans:a</t></v>
<v><i>agrava</i>		<t>dans:a</t></v>
<v><i>agrea</i>		<t>dans:a</t></v>
<v><i>agrega</i>		<t>abund:a</t></v>
<v><i>agrementa</i>		<t>dans:a</t></v>
<v><i>agresa</i>		<t>dans:a</t></v>
<v><i>agresiona</i>		<t>dans:a</t></v>
<v><i>agricoliza</i>		<t>dans:a</t></v>
<v><i>agrăi</i>		<t>locui:</t></v>
<v><i>agăţa</i>		<t>abdic:a</t></v>
<v><i>ahtia</i>		<t>abrevi:a</t></v>
<v><i>aiepta</i>		<t>ai:epta</t></v>
<v><i>aiura</i>		<t>dans:a</t></v>
<v><i>aiuri</i>		<t>fer:i</t></v>
<v><i>ajumi</i>		<t>fer:i</t></v>
<v><i>ajuna</i>		<t>dans:a</t></v>
<v><i>ajunge</i>		<t>ajun:ge</t></v>
<v><i>ajura</i>		<t>dans:a</t></v>
<v><i>ajusta</i>		<t>dans:a</t></v>
<v><i>ajuta</i>		<t>accep:ta</t></v>
<v><i>alambica</i>		<t>alambic:a</t></v>
<v><i>alarma</i>		<t>dans:a</t></v>
<v><i>albi</i>		<t>fer:i</t></v>
<v><i>albii</i>		<t>albi:i</t></v>
<v><i>albini</i>		<t>fer:i</t></v>
<v><i>alburi</i>		<t>albur:i</t></v>
<v><i>albăstri</i>		<t>fer:i</t></v>
<v><i>alcaliniza</i>		<t>dans:a</t></v>
<v><i>alcooliza</i>		<t>dans:a</t></v>
<v><i>alcătui</i>		<t>locui:</t></v>
<v><i>aldui</i>		<t>locui:</t></v>
<v><i>alega</i>		<t>abdic:a</t></v>
<v><i>alege</i>		<t>ale:ge</t></v>
<v><i>alegoriza</i>		<t>dans:a</t></v>
<v><i>alerga</i>		<t>ale:rga</t></v>
<v><i>alerta</i>		<t>dans:a</t></v>
<v><i>aleza</i>		<t>dans:a</t></v>
<v><i>alfabetiza</i>		<t>dans:a</t></v>
<v><i>algoritmiza</i>		<t>dans:a</t></v>
<v><i>alia</i>		<t>abrevi:a</t></v>
<v><i>alici</i>		<t>fer:i</t></v>
<v><i>aliena</i>		<t>dans:a</t></v>
<v><i>aligni</i>		<t>fer:i</t></v>
<v><i>alimba</i>		<t>dans:a</t></v>
<v><i>alimenta</i>		<t>dans:a</t></v>
<v><i>alina</i>		<t>abdic:a</t></v>
<v><i>alini</i>		<t>fer:i</t></v>
<v><i>alinia</i>		<t>abrevi:a</t></v>
<v><i>alinta</i>		<t>accep:ta</t></v>
<v><i>alipi</i>		<t>fer:i</t></v>
<v><i>alivăni</i>		<t>fer:i</t></v>
<v><i>aloca</i>		<t>abdic:a</t></v>
<v><i>altera</i>		<t>dans:a</t></v>
<v><i>alterna</i>		<t>dans:a</t></v>
<v><i>altoi</i>		<t>locui:</t></v>
<v><i>aluminiza</i>		<t>dans:a</t></v>
<v><i>aluneca</i>		<t>abdic:a</t></v>
<v><i>alunga</i>		<t>abdic:a</t></v>
<v><i>alungi</i>		<t>fer:i</t></v>
<v><i>aluniza</i>		<t>dans:a</t></v>
<v><i>aluziona</i>		<t>dans:a</t></v>
<v><i>alămi</i>		<t>fer:i</t></v>
<v><i>alăpta</i>		<t>dans:a</t></v>
<v><i>alătura</i>		<t>abdic:a</t></v>
<v><i>amalgama</i>		<t>dans:a</t></v>
<v><i>amalgamiza</i>		<t>dans:a</t></v>
<v><i>amaneta</i>		<t>dans:a</t></v>
<v><i>amara</i>		<t>dans:a</t></v>
<v><i>amarina</i>		<t>dans:a</t></v>
<v><i>amartiza</i>		<t>abeced:a</t></v>
<v><i>ambala</i>		<t>dans:a</t></v>
<v><i>ambarasa</i>		<t>dans:a</t></v>
<v><i>ambarda</i>		<t>dans:a</t></v>
<v><i>ambeta</i>		<t>dans:a</t></v>
<v><i>ambiguiza</i>		<t>dans:a</t></v>
<v><i>ambiţiona</i>		<t>dans:a</t></v>
<v><i>ambosa</i>		<t>dans:a</t></v>
<v><i>ambra</i>		<t>dans:a</t></v>
<v><i>ambreia</i>		<t>abrevi:a</t></v>
<v><i>ambusca</i>		<t>alambic:a</t></v>
<v><i>ambuteia</i>		<t>abrevi:a</t></v>
<v><i>ambutisa</i>		<t>dans:a</t></v>
<v><i>ameliora</i>		<t>dans:a</t></v>
<v><i>amenaja</i>		<t>dans:a</t></v>
<v><i>amenda</i>		<t>dans:a</t></v>
<v><i>ameninţa</i>		<t>abdic:a</t></v>
<v><i>americaniza</i>		<t>dans:a</t></v>
<v><i>ameriza</i>		<t>dans:a</t></v>
<v><i>amesteca</i>		<t>abdic:a</t></v>
<v><i>ameţi</i>		<t>fer:i</t></v>
<v><i>amiezi</i>		<t>fer:i</t></v>
<v><i>aminti</i>		<t>fer:i</t></v>
<v><i>amnistia</i>		<t>abrevi:a</t></v>
<v><i>amoreza</i>		<t>dans:a</t></v>
<v><i>amorsa</i>		<t>dans:a</t></v>
<v><i>amortiza</i>		<t>dans:a</t></v>
<v><i>amorţi</i>		<t>fer:i</t></v>
<v><i>amplasa</i>		<t>dans:a</t></v>
<v><i>amplifica</i>		<t>abdic:a</t></v>
<v><i>amprenta</i>		<t>dans:a</t></v>
<v><i>amputa</i>		<t>dans:a</t></v>
<v><i>amurgi</i>		<t>albur:i</t></v>
<v><i>amuza</i>		<t>abdic:a</t></v>
<v><i>amuţa</i>		<t>abdic:a</t></v>
<v><i>amuţi</i>		<t>fer:i</t></v>
<v><i>amuși</i>		<t>fer:i</t></v>
<v><i>amușina</i>		<t>abdic:a</t></v>
<v><i>amâna</i>		<t>abdic:a</t></v>
<v><i>amăgi</i>		<t>fer:i</t></v>
<v><i>amănunţi</i>		<t>fer:i</t></v>
<v><i>amărî</i>		<t>ur:î</t></v>
<v><i>anacroniza</i>		<t>dans:a</t></v>
<v><i>anagrama</i>		<t>dans:a</t></v>
<v><i>anagramatiza</i>		<t>dans:a</t></v>
<v><i>analiza</i>		<t>dans:a</t></v>
<v><i>anamorfoza</i>		<t>dans:a</t></v>
<v><i>anarhiza</i>		<t>dans:a</t></v>
<v><i>anastomoza</i>		<t>dans:a</t></v>
<v><i>anatemiza</i>		<t>dans:a</t></v>
<v><i>ancheta</i>		<t>dans:a</t></v>
<v><i>anchiloza</i>		<t>dans:a</t></v>
<v><i>anclanșa</i>		<t>dans:a</t></v>
<v><i>ancola</i>		<t>dans:a</t></v>
<v><i>ancora</i>		<t>dans:a</t></v>
<v><i>ancrasa</i>		<t>abeced:a</t></v>
<v><i>andoca</i>		<t>alambic:a</t></v>
<v><i>andosa</i>		<t>dans:a</t></v>
<v><i>aneantiza</i>		<t>dans:a</t></v>
<v><i>anecdotiza</i>		<t>dans:a</t></v>
<v><i>anemia</i>		<t>abrevi:a</t></v>
<v><i>anestezia</i>		<t>abrevi:a</t></v>
<v><i>anexa</i>		<t>dans:a</t></v>
<v><i>angaja</i>		<t>dans:a</t></v>
<v><i>angeliza</i>		<t>dans:a</t></v>
<v><i>angliciza</i>		<t>dans:a</t></v>
<v><i>angoasa</i>		<t>dans:a</t></v>
<v><i>angrena</i>		<t>dans:a</t></v>
<v><i>anihila</i>		<t>dans:a</t></v>
<v><i>anima</i>		<t>dans:a</t></v>
<v><i>animaliza</i>		<t>dans:a</t></v>
<v><i>anina</i>		<t>abdic:a</t></v>
<v><i>aniversa</i>		<t>dans:a</t></v>
<v><i>anosti</i>		<t>fer:i</t></v>
<v><i>anroba</i>		<t>abdic:a</t></v>
<v><i>antagoniza</i>		<t>dans:a</t></v>
<v><i>antecalcula</i>		<t>dans:a</t></v>
<v><i>antedata</i>		<t>dans:a</t></v>
<v><i>antepune</i>		<t>pu:ne</t></v>
<v><i>anticipa</i>		<t>dans:a</t></v>
<v><i>antipatiza</i>		<t>dans:a</t></v>
<v><i>antologa</i>		<t>alambic:a</t></v>
<v><i>antologiza</i>		<t>dans:a</t></v>
<v><i>antrena</i>		<t>dans:a</t></v>
<v><i>antrepozita</i>		<t>dans:a</t></v>
<v><i>antropomorfiza</i>		<t>dans:a</t></v>
<v><i>anula</i>		<t>dans:a</t></v>
<v><i>anunţa</i>		<t>abdic:a</t></v>
<v><i>anvizaja</i>		<t>dans:a</t></v>
<v><i>aparţine</i>		<t>aparţi:ne</t></v>
<v><i>apela</i>		<t>dans:a</t></v>
<v><i>apica</i>		<t>abdic:a</t></v>
<v><i>aplana</i>		<t>dans:a</t></v>
<v><i>aplatiza</i>		<t>dans:a</t></v>
<v><i>aplauda</i>		<t>acor:da</t></v>
<v><i>apleca</i>		<t>abdic:a</t></v>
<v><i>aplica</i>		<t>abdic:a</t></v>
<v><i>apocopa</i>		<t>dans:a</t></v>
<v><i>apologiza</i>		<t>dans:a</t></v>
<v><i>aporta</i>		<t>abeced:a</t></v>
<v><i>apostrofa</i>		<t>dans:a</t></v>
<v><i>apoteoza</i>		<t>dans:a</t></v>
<v><i>apoza</i>		<t>dans:a</t></v>
<v><i>aprecia</i>		<t>abrevi:a</t></v>
<v><i>apreta</i>		<t>dans:a</t></v>
<v><i>apreţui</i>		<t>locui:</t></v>
<v><i>aprinde</i>		<t>aprin:de</t></v>
<v><i>aproba</i>		<t>abdic:a</t></v>
<v><i>aprofunda</i>		<t>dans:a</t></v>
<v><i>apropia</i>		<t>adi:a</t></v>
<v><i>aprova</i>		<t>abund:a</t></v>
<v><i>aproviziona</i>		<t>dans:a</t></v>
<v><i>aproxima</i>		<t>dans:a</t></v>
<v><i>apuca</i>		<t>abdic:a</t></v>
<v><i>apune</i>		<t>pu:ne</t></v>
<v><i>apunta</i>		<t>abeced:a</t></v>
<v><i>apupa</i>		<t>abund:a</t></v>
<v><i>apăra</i>		<t>ap:ăra</t></v>
<v><i>apărea</i>		<t>p:ărea</t></v>
<v><i>apăsa</i>		<t>ap:ăsa</t></v>
<v><i>ara</i>		<t>abdic:a</t></v>
<v><i>arabiza</i>		<t>dans:a</t></v>
<v><i>aranja</i>		<t>dans:a</t></v>
<v><i>arbitra</i>		<t>dans:a</t></v>
<v><i>arbora</i>		<t>dans:a</t></v>
<v><i>arboriza</i>		<t>dans:a</t></v>
<v><i>arcui</i>		<t>locui:</t></v>
<v><i>arcăni</i>		<t>fer:i</t></v>
<v><i>arde</i>		<t>a:rde</t></v>
<v><i>ardeia</i>		<t>abrevi:a</t></v>
<v><i>arenda</i>		<t>dans:a</t></v>
<v><i>arendăși</i>		<t>fer:i</t></v>
<v><i>aresta</i>		<t>dans:a</t></v>
<v><i>arestui</i>		<t>locui:</t></v>
<v><i>areta</i>		<t>abund:a</t></v>
<v><i>arginta</i>		<t>dans:a</t></v>
<v><i>argintui</i>		<t>locui:</t></v>
<v><i>argotiza</i>		<t>dans:a</t></v>
<v><i>argumenta</i>		<t>dans:a</t></v>
<v><i>argăsi</i>		<t>fer:i</t></v>
<v><i>argăţi</i>		<t>fer:i</t></v>
<v><i>arhitectura</i>		<t>dans:a</t></v>
<v><i>aridiza</i>		<t>dans:a</t></v>
<v><i>arima</i>		<t>dans:a</t></v>
<v><i>aristocratiza</i>		<t>dans:a</t></v>
<v><i>aristoteliza</i>		<t>dans:a</t></v>
<v><i>arma</i>		<t>dans:a</t></v>
<v><i>armonia</i>		<t>abrevi:a</t></v>
<v><i>armoniza</i>		<t>dans:a</t></v>
<v><i>aroga</i>		<t>abdic:a</t></v>
<v><i>aromatiza</i>		<t>dans:a</t></v>
<v><i>aromi</i>		<t>fer:i</t></v>
<v><i>aronda</i>		<t>dans:a</t></v>
<v><i>arpegia</i>		<t>abrevi:a</t></v>
<v><i>articula</i>		<t>dans:a</t></v>
<v><i>artificializa</i>		<t>dans:a</t></v>
<v><i>arunca</i>		<t>abdic:a</t></v>
<v><i>arvuni</i>		<t>fer:i</t></v>
<v><i>arăci</i>		<t>fer:i</t></v>
<v><i>arămi</i>		<t>fer:i</t></v>
<v><i>arăta</i>		<t>ar:ăta</t></v>
<v><i>asalta</i>		<t>dans:a</t></v>
<v><i>asambla</i>		<t>dans:a</t></v>
<v><i>asana</i>		<t>dans:a</t></v>
<v><i>asasina</i>		<t>dans:a</t></v>
<v><i>ascensiona</i>		<t>dans:a</t></v>
<v><i>ascetiza</i>		<t>dans:a</t></v>
<v><i>asculta</i>		<t>accep:ta</t></v>
<v><i>ascunde</i>		<t>aprin:de</t></v>
<v><i>ascuţi</i>		<t>ascu:ţi</t></v>
<v><i>aseca</i>		<t>abdic:a</t></v>
<v><i>asedia</i>		<t>abrevi:a</t></v>
<v><i>aseleniza</i>		<t>dans:a</t></v>
<v><i>asemui</i>		<t>locui:</t></v>
<v><i>asemăna</i>		<t>abdic:a</t></v>
<v><i>aseptiza</i>		<t>dans:a</t></v>
<v><i>aservi</i>		<t>fer:i</t></v>
<v><i>asezona</i>		<t>dans:a</t></v>
<v><i>asfalta</i>		<t>dans:a</t></v>
<v><i>asfinţi</i>		<t>albur:i</t></v>
<v><i>asfixia</i>		<t>abrevi:a</t></v>
<v><i>asibila</i>		<t>dans:a</t></v>
<v><i>asigna</i>		<t>dans:a</t></v>
<v><i>asigura</i>		<t>abdic:a</t></v>
<v><i>asimila</i>		<t>dans:a</t></v>
<v><i>asista</i>		<t>accep:ta</t></v>
<v><i>asmuţi</i>		<t>ascu:ţi</t></v>
<v><i>asocia</i>		<t>abrevi:a</t></v>
<v><i>asola</i>		<t>dans:a</t></v>
<v><i>asoma</i>		<t>dans:a</t></v>
<v><i>asorta</i>		<t>dans:a</t></v>
<v><i>aspecta</i>		<t>dans:a</t></v>
<v><i>aspira</i>		<t>abdic:a</t></v>
<v><i>aspri</i>		<t>fer:i</t></v>
<v><i>asteniza</i>		<t>dans:a</t></v>
<v><i>astruca</i>		<t>abdic:a</t></v>
<v><i>astupa</i>		<t>abdic:a</t></v>
<v><i>astâmpăra</i>		<t>ap:ăra</t></v>
<v><i>astăura</i>		<t>abdic:a</t></v>
<v><i>asuda</i>		<t>acor:da</t></v>
<v><i>asuma</i>		<t>abdic:a</t></v>
<v><i>asupri</i>		<t>fer:i</t></v>
<v><i>asurzi</i>		<t>fer:i</t></v>
<v><i>ataca</i>		<t>abdic:a</t></v>
<v><i>atașa</i>		<t>dans:a</t></v>
<v><i>atenta</i>		<t>dans:a</t></v>
<v><i>atenua</i>		<t>dans:a</t></v>
<v><i>atenţiona</i>		<t>dans:a</t></v>
<v><i>ateriza</i>		<t>dans:a</t></v>
<v><i>atesta</i>		<t>ate:sta</t></v>
<v><i>atinge</i>		<t>atin:ge</t></v>
<v><i>atomiza</i>		<t>dans:a</t></v>
<v><i>atrage</i>		<t>abstr:age</t></v>
<v><i>atribui</i>		<t>atribui:</t></v>
<v><i>atrofia</i>		<t>abrevi:a</t></v>
<v><i>atârna</i>		<t>abdic:a</t></v>
<v><i>audia</i>		<t>abrevi:a</t></v>
<v><i>augmenta</i>		<t>dans:a</t></v>
<v><i>augura</i>		<t>dans:a</t></v>
<v><i>aureola</i>		<t>dans:a</t></v>
<v><i>auri</i>		<t>fer:i</t></v>
<v><i>ausculta</i>		<t>accep:ta</t></v>
<v><i>autentifica</i>		<t>abdic:a</t></v>
<v><i>autoaccidenta</i>		<t>dans:a</t></v>
<v><i>autoacuza</i>		<t>abdic:a</t></v>
<v><i>autoadministra</i>		<t>dans:a</t></v>
<v><i>autoafirma</i>		<t>abdic:a</t></v>
<v><i>autoanaliza</i>		<t>dans:a</t></v>
<v><i>autoaprecia</i>		<t>abrevi:a</t></v>
<v><i>autoaproviziona</i>		<t>dans:a</t></v>
<v><i>autocaracteriza</i>		<t>dans:a</t></v>
<v><i>autocenzura</i>		<t>dans:a</t></v>
<v><i>autoclaustra</i>		<t>dans:a</t></v>
<v><i>autoconserva</i>		<t>abdic:a</t></v>
<v><i>autocontempla</i>		<t>dans:a</t></v>
<v><i>autocontrola</i>		<t>dans:a</t></v>
<v><i>autoculpabiliza</i>		<t>dans:a</t></v>
<v><i>autodeclanșa</i>		<t>abeced:a</t></v>
<v><i>autodefini</i>		<t>fer:i</t></v>
<v><i>autodemasca</i>		<t>autodema:sca</t></v>
<v><i>autodenunţa</i>		<t>abdic:a</t></v>
<v><i>autodepăși</i>		<t>fer:i</t></v>
<v><i>autodetermina</i>		<t>abdic:a</t></v>
<v><i>autodiagnostica</i>		<t>alambic:a</t></v>
<v><i>autodistruge</i>		<t>autodistru:ge</t></v>
<v><i>autodizolva</i>		<t>abund:a</t></v>
<v><i>autodocumenta</i>		<t>dans:a</t></v>
<v><i>autodota</i>		<t>dans:a</t></v>
<v><i>autoevalua</i>		<t>dans:a</t></v>
<v><i>autoevidenţia</i>		<t>abrevi:a</t></v>
<v><i>autoexamina</i>		<t>dans:a</t></v>
<v><i>autoexcita</i>		<t>accep:ta</t></v>
<v><i>autofinanţa</i>		<t>dans:a</t></v>
<v><i>autoflagela</i>		<t>dans:a</t></v>
<v><i>autofuraja</i>		<t>dans:a</t></v>
<v><i>autogospodări</i>		<t>fer:i</t></v>
<v><i>autografia</i>		<t>abrevi:a</t></v>
<v><i>autoguverna</i>		<t>dans:a</t></v>
<v><i>autohtoniza</i>		<t>dans:a</t></v>
<v><i>autoignora</i>		<t>dans:a</t></v>
<v><i>autoiluziona</i>		<t>dans:a</t></v>
<v><i>autoincendia</i>		<t>abrevi:a</t></v>
<v><i>autoinstrui</i>		<t>locui:</t></v>
<v><i>autointitula</i>		<t>dans:a</t></v>
<v><i>autoironiza</i>		<t>dans:a</t></v>
<v><i>autoliniști</i>		<t>fer:i</t></v>
<v><i>automatiza</i>		<t>dans:a</t></v>
<v><i>automutila</i>		<t>dans:a</t></v>
<v><i>autonomiza</i>		<t>dans:a</t></v>
<v><i>autoobserva</i>		<t>abdic:a</t></v>
<v><i>autopastișa</i>		<t>dans:a</t></v>
<v><i>autoperfecţiona</i>		<t>dans:a</t></v>
<v><i>autopersifla</i>		<t>dans:a</t></v>
<v><i>autoportretiza</i>		<t>dans:a</t></v>
<v><i>autoproclama</i>		<t>abdic:a</t></v>
<v><i>autoprograma</i>		<t>dans:a</t></v>
<v><i>autoproteja</i>		<t>dans:a</t></v>
<v><i>autopsia</i>		<t>abrevi:a</t></v>
<v><i>autoregla</i>		<t>dans:a</t></v>
<v><i>autoreproșa</i>		<t>dans:a</t></v>
<v><i>autoriza</i>		<t>dans:a</t></v>
<v><i>autosalva</i>		<t>dans:a</t></v>
<v><i>autoservi</i>		<t>fer:i</t></v>
<v><i>autosugestiona</i>		<t>dans:a</t></v>
<v><i>autosupraveghea</i>		<t>autosupraveghe:a</t></v>
<v><i>autoutila</i>		<t>dans:a</t></v>
<v><i>autovaccina</i>		<t>dans:a</t></v>
<v><i>auzi</i>		<t>au:zi</t></v>
<v><i>avala</i>		<t>dans:a</t></v>
<v><i>avaliza</i>		<t>dans:a</t></v>
<v><i>avansa</i>		<t>dans:a</t></v>
<v><i>avantaja</i>		<t>dans:a</t></v>
<v><i>avaria</i>		<t>abrevi:a</t></v>
<v><i>avea</i>		<t>a:vea</t></v>
<v><i>aveni</i>		<t>v:eni</t></v>
<v><i>aventura</i>		<t>dans:a</t></v>
<v><i>avertiza</i>		<t>dans:a</t></v>
<v><i>aviva</i>		<t>dans:a</t></v>
<v><i>aviza</i>		<t>dans:a</t></v>
<v><i>avorta</i>		<t>dans:a</t></v>
<v><i>avua</i>		<t>dans:a</t></v>
<v><i>avânta</i>		<t>accep:ta</t></v>
<v><i>axa</i>		<t>dans:a</t></v>
<v><i>axiomatiza</i>		<t>dans:a</t></v>
<v><i>azura</i>		<t>dans:a</t></v>
<v><i>azvârli</i>		<t>azvârl:i</t></v>
<v><i>aâa</i>		<t>abdic:a</t></v>
<v><i>aţine</i>		<t>aţi:ne</t></v>
<v><i>aţinti</i>		<t>fer:i</t></v>
<v><i>aţipi</i>		<t>fer:i</t></v>
<v><i>așchia</i>		<t>abrevi:a</t></v>
<v><i>așeza</i>		<t>aș:eza</t></v>
<v><i>aștepta</i>		<t>aște:pta</t></v>
<v><i>așterne</i>		<t>aște:rne</t></v>
<v><i>bacceli</i>		<t>fer:i</t></v>
<v><i>badijona</i>		<t>dans:a</t></v>
<v><i>bagateliza</i>		<t>dans:a</t></v>
<v><i>balada</i>		<t>dans:a</t></v>
<v><i>baladiza</i>		<t>dans:a</t></v>
<v><i>balansa</i>		<t>dans:a</t></v>
<v><i>balasta</i>		<t>dans:a</t></v>
<v><i>balcaniza</i>		<t>dans:a</t></v>
<v><i>baleia</i>		<t>abrevi:a</t></v>
<v><i>baleta</i>		<t>dans:a</t></v>
<v><i>baliza</i>		<t>dans:a</t></v>
<v><i>balona</i>		<t>dans:a</t></v>
<v><i>balota</i>		<t>dans:a</t></v>
<v><i>banaliza</i>		<t>dans:a</t></v>
<v><i>bancruta</i>		<t>dans:a</t></v>
<v><i>banda</i>		<t>dans:a</t></v>
<v><i>bandaja</i>		<t>dans:a</t></v>
<v><i>bantustaniza</i>		<t>dans:a</t></v>
<v><i>bara</i>		<t>dans:a</t></v>
<v><i>barbariza</i>		<t>dans:a</t></v>
<v><i>barbota</i>		<t>dans:a</t></v>
<v><i>baricada</i>		<t>dans:a</t></v>
<v><i>barochiza</i>		<t>dans:a</t></v>
<v><i>bascula</i>		<t>dans:a</t></v>
<v><i>bastarda</i>		<t>dans:a</t></v>
<v><i>bate</i>		<t>ab:ate</t></v>
<v><i>batjocori</i>		<t>fer:i</t></v>
<v><i>baza</i>		<t>dans:a</t></v>
<v><i>bazarda</i>		<t>dans:a</t></v>
<v><i>bazona</i>		<t>dans:a</t></v>
<v><i>bea</i>		<t>b:ea</t></v>
<v><i>beatifica</i>		<t>abdic:a</t></v>
<v><i>behăi</i>		<t>atribui:</t></v>
<v><i>bejeni</i>		<t>fer:i</t></v>
<v><i>bejăni</i>		<t>fer:i</t></v>
<v><i>beli</i>		<t>fer:i</t></v>
<v><i>bemoliza</i>		<t>dans:a</t></v>
<v><i>benchetui</i>		<t>locui:</t></v>
<v><i>beneficia</i>		<t>abrevi:a</t></v>
<v><i>benocla</i>		<t>abeced:a</t></v>
<v><i>berbeci</i>		<t>fer:i</t></v>
<v><i>bestializa</i>		<t>dans:a</t></v>
<v><i>betegi</i>		<t>fer:i</t></v>
<v><i>beteji</i>		<t>fer:i</t></v>
<v><i>betona</i>		<t>dans:a</t></v>
<v><i>bezmetici</i>		<t>fer:i</t></v>
<v><i>beșica</i>		<t>abdic:a</t></v>
<v><i>beșteli</i>		<t>fer:i</t></v>
<v><i>bichiri</i>		<t>fer:i</t></v>
<v><i>biciui</i>		<t>locui:</t></v>
<v><i>bifa</i>		<t>dans:a</t></v>
<v><i>bifurca</i>		<t>abdic:a</t></v>
<v><i>bili</i>		<t>fer:i</t></v>
<v><i>bilţui</i>		<t>atribui:</t></v>
<v><i>bindisi</i>		<t>fer:i</t></v>
<v><i>binecuvânta</i>		<t>dans:a</t></v>
<v><i>binemerita</i>		<t>accep:ta</t></v>
<v><i>binevoi</i>		<t>locui:</t></v>
<v><i>binocla</i>		<t>dans:a</t></v>
<v><i>biostimula</i>		<t>dans:a</t></v>
<v><i>birocratiza</i>		<t>dans:a</t></v>
<v><i>birui</i>		<t>atribui:</t></v>
<v><i>bisa</i>		<t>dans:a</t></v>
<v><i>bituma</i>		<t>dans:a</t></v>
<v><i>bivuaca</i>		<t>alambic:a</t></v>
<v><i>bizantiniza</i>		<t>dans:a</t></v>
<v><i>bizota</i>		<t>dans:a</t></v>
<v><i>bizui</i>		<t>atribui:</t></v>
<v><i>blagoslovi</i>		<t>fer:i</t></v>
<v><i>blama</i>		<t>dans:a</t></v>
<v><i>blanșa</i>		<t>dans:a</t></v>
<v><i>blasfema</i>		<t>dans:a</t></v>
<v><i>blasfemia</i>		<t>abrevi:a</t></v>
<v><i>blaza</i>		<t>dans:a</t></v>
<v><i>blazona</i>		<t>dans:a</t></v>
<v><i>blegi</i>		<t>fer:i</t></v>
<v><i>blehăi</i>		<t>atribui:</t></v>
<v><i>bleojdi</i>		<t>fer:i</t></v>
<v><i>bleotocări</i>		<t>fer:i</t></v>
<v><i>blestema</i>		<t>abdic:a</t></v>
<v><i>blești</i>		<t>fer:i</t></v>
<v><i>blinda</i>		<t>dans:a</t></v>
<v><i>bloca</i>		<t>alambic:a</t></v>
<v><i>blodogori</i>		<t>fer:i</t></v>
<v><i>blufa</i>		<t>dans:a</t></v>
<v><i>bluza</i>		<t>dans:a</t></v>
<v><i>blăni</i>		<t>fer:i</t></v>
<v><i>blănui</i>		<t>locui:</t></v>
<v><i>bobi</i>		<t>fer:i</t></v>
<v><i>bobina</i>		<t>dans:a</t></v>
<v><i>boboti</i>		<t>fer:i</t></v>
<v><i>boci</i>		<t>fer:i</t></v>
<v><i>bocăni</i>		<t>fer:i</t></v>
<v><i>bodiceca</i>		<t>alambic:a</t></v>
<v><i>bodogăni</i>		<t>fer:i</t></v>
<v><i>bogonisi</i>		<t>fer:i</t></v>
<v><i>boi</i>		<t>locui:</t></v>
<v><i>boicota</i>		<t>dans:a</t></v>
<v><i>boieri</i>		<t>fer:i</t></v>
<v><i>bolborosi</i>		<t>fer:i</t></v>
<v><i>bolboșa</i>		<t>dans:a</t></v>
<v><i>boldi</i>		<t>fer:i</t></v>
<v><i>boli</i>		<t>fer:i</t></v>
<v><i>bolmoji</i>		<t>fer:i</t></v>
<v><i>bolnăvi</i>		<t>fer:i</t></v>
<v><i>bolovăni</i>		<t>fer:i</t></v>
<v><i>bolti</i>		<t>fer:i</t></v>
<v><i>bolânzi</i>		<t>fer:i</t></v>
<v><i>bolșeviza</i>		<t>dans:a</t></v>
<v><i>bomba</i>		<t>dans:a</t></v>
<v><i>bombarda</i>		<t>dans:a</t></v>
<v><i>bombăni</i>		<t>fer:i</t></v>
<v><i>boncăi</i>		<t>boncăi:</t></v>
<v><i>boncălui</i>		<t>boncăi:</t></v>
<v><i>bondisa</i>		<t>abeced:a</t></v>
<v><i>bonifica</i>		<t>abdic:a</t></v>
<v><i>bonti</i>		<t>fer:i</t></v>
<v><i>bontăni</i>		<t>fer:i</t></v>
<v><i>bordura</i>		<t>dans:a</t></v>
<v><i>borfăi</i>		<t>locui:</t></v>
<v><i>borna</i>		<t>dans:a</t></v>
<v><i>bornăi</i>		<t>atribui:</t></v>
<v><i>boroni</i>		<t>fer:i</t></v>
<v><i>borteli</i>		<t>fer:i</t></v>
<v><i>borti</i>		<t>fer:i</t></v>
<v><i>borzoi</i>		<t>boncăi:</t></v>
<v><i>borî</i>		<t>ur:î</t></v>
<v><i>borăi</i>		<t>borăi:</t></v>
<v><i>borși</i>		<t>albur:i</t></v>
<v><i>bosconi</i>		<t>fer:i</t></v>
<v><i>boscorodi</i>		<t>fer:i</t></v>
<v><i>bosumfla</i>		<t>afl:a</t></v>
<v><i>botaniza</i>		<t>dans:a</t></v>
<v><i>boteza</i>		<t>abdic:a</t></v>
<v><i>bovariza</i>		<t>abeced:a</t></v>
<v><i>boxa</i>		<t>dans:a</t></v>
<v><i>boţi</i>		<t>fer:i</t></v>
<v><i>boșorogi</i>		<t>fer:i</t></v>
<v><i>braca</i>		<t>alambic:a</t></v>
<v><i>bracona</i>		<t>dans:a</t></v>
<v><i>bramburi</i>		<t>fer:i</t></v>
<v><i>branșa</i>		<t>dans:a</t></v>
<v><i>brava</i>		<t>dans:a</t></v>
<v><i>braza</i>		<t>dans:a</t></v>
<v><i>braţa</i>		<t>dans:a</t></v>
<v><i>breveta</i>		<t>dans:a</t></v>
<v><i>breza</i>		<t>dans:a</t></v>
<v><i>bria</i>		<t>abrevi:a</t></v>
<v><i>bricheta</i>		<t>dans:a</t></v>
<v><i>bricola</i>		<t>dans:a</t></v>
<v><i>brobona</i>		<t>dans:a</t></v>
<v><i>broboni</i>		<t>fer:i</t></v>
<v><i>broda</i>		<t>dans:a</t></v>
<v><i>brodi</i>		<t>fer:i</t></v>
<v><i>bronza</i>		<t>dans:a</t></v>
<v><i>broșa</i>		<t>dans:a</t></v>
<v><i>bruftui</i>		<t>locui:</t></v>
<v><i>bruftului</i>		<t>locui:</t></v>
<v><i>bruia</i>		<t>abrevi:a</t></v>
<v><i>bruma</i>		<t>abeced:a</t></v>
<v><i>bruna</i>		<t>dans:a</t></v>
<v><i>brusca</i>		<t>alambic:a</t></v>
<v><i>brutaliza</i>		<t>dans:a</t></v>
<v><i>brânci</i>		<t>fer:i</t></v>
<v><i>brânzi</i>		<t>albur:i</t></v>
<v><i>brăcui</i>		<t>locui:</t></v>
<v><i>brăhni</i>		<t>albur:i</t></v>
<v><i>brănui</i>		<t>locui:</t></v>
<v><i>brăzda</i>		<t>dans:a</t></v>
<v><i>brăzdui</i>		<t>locui:</t></v>
<v><i>bubui</i>		<t>borăi:</t></v>
<v><i>bucela</i>		<t>dans:a</t></v>
<v><i>bucheri</i>		<t>fer:i</t></v>
<v><i>buchirisi</i>		<t>fer:i</t></v>
<v><i>buchisa</i>		<t>dans:a</t></v>
<v><i>buchisi</i>		<t>fer:i</t></v>
<v><i>buciarda</i>		<t>dans:a</t></v>
<v><i>buciuma</i>		<t>abdic:a</t></v>
<v><i>bucla</i>		<t>dans:a</t></v>
<v><i>bucura</i>		<t>abdic:a</t></v>
<v><i>bucăţeli</i>		<t>fer:i</t></v>
<v><i>bucăţi</i>		<t>fer:i</t></v>
<v><i>bucși</i>		<t>fer:i</t></v>
<v><i>buda</i>		<t>dans:a</t></v>
<v><i>bufni</i>		<t>fer:i</t></v>
<v><i>bugezi</i>		<t>fer:i</t></v>
<v><i>buhăi</i>		<t>locui:</t></v>
<v><i>bui</i>		<t>locui:</t></v>
<v><i>buici</i>		<t>fer:i</t></v>
<v><i>buimăci</i>		<t>fer:i</t></v>
<v><i>buiurdisi</i>		<t>fer:i</t></v>
<v><i>bujdi</i>		<t>fer:i</t></v>
<v><i>bulbuca</i>		<t>abdic:a</t></v>
<v><i>bulbuci</i>		<t>albur:i</t></v>
<v><i>bulgări</i>		<t>fer:i</t></v>
<v><i>bulona</i>		<t>dans:a</t></v>
<v><i>buluci</i>		<t>fer:i</t></v>
<v><i>bulversa</i>		<t>dans:a</t></v>
<v><i>bumbăci</i>		<t>fer:i</t></v>
<v><i>bunghini</i>		<t>fer:i</t></v>
<v><i>bura</i>		<t>abeced:a</t></v>
<v><i>burduși</i>		<t>fer:i</t></v>
<v><i>burica</i>		<t>abdic:a</t></v>
<v><i>burlăci</i>		<t>fer:i</t></v>
<v><i>burniţa</i>		<t>abeced:a</t></v>
<v><i>burzului</i>		<t>locui:</t></v>
<v><i>buscula</i>		<t>dans:a</t></v>
<v><i>butaforiza</i>		<t>dans:a</t></v>
<v><i>butori</i>		<t>fer:i</t></v>
<v><i>butuci</i>		<t>fer:i</t></v>
<v><i>butăși</i>		<t>fer:i</t></v>
<v><i>buzdugăni</i>		<t>fer:i</t></v>
<v><i>buzni</i>		<t>fer:i</t></v>
<v><i>buzunări</i>		<t>fer:i</t></v>
<v><i>buși</i>		<t>fer:i</t></v>
<v><i>bușuma</i>		<t>dans:a</t></v>
<v><i>bâcâi</i>		<t>atribui:</t></v>
<v><i>bâhli</i>		<t>fer:i</t></v>
<v><i>bâigui</i>		<t>atribui:</t></v>
<v><i>bâjbâi</i>		<t>atribui:</t></v>
<v><i>bâlbâi</i>		<t>atribui:</t></v>
<v><i>bâltâcâi</i>		<t>atribui:</t></v>
<v><i>bântui</i>		<t>atribui:</t></v>
<v><i>bârfi</i>		<t>fer:i</t></v>
<v><i>bârliga</i>		<t>abund:a</t></v>
<v><i>bârnui</i>		<t>locui:</t></v>
<v><i>bârzoia</i>		<t>abrevi:a</t></v>
<v><i>bârâi</i>		<t>atribui:</t></v>
<v><i>bâzgoia</i>		<t>abrevi:a</t></v>
<v><i>bâzgăi</i>		<t>locui:</t></v>
<v><i>bâzâi</i>		<t>atribui:</t></v>
<v><i>bâţâi</i>		<t>atribui:</t></v>
<v><i>băciui</i>		<t>locui:</t></v>
<v><i>bădădăi</i>		<t>locui:</t></v>
<v><i>băga</i>		<t>b:ăga</t></v>
<v><i>băi</i>		<t>locui:</t></v>
<v><i>băia</i>		<t>abrevi:a</t></v>
<v><i>băjeni</i>		<t>fer:i</t></v>