<?xml version="1.0" encoding='utf-8'?>

<!--
	verbs-it.xml - List of Italian verbs with their conjugation template.
	The templates were generated by SekouD using Unsupervised Learning,
	and follow the xml schema defined by Pierre Sarrazin in conjug_manager.

	Copyright (C) 2018 Sekou Diao <https://github.com/SekouD>
	Copyright (C) 2003-2016 Pierre Sarrazin <http://sarrazip.com/>

	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with this program; if not, write to the Free Software
	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
	02110-1301, USA.
-->

<!DOCTYPE verbs-it [
    <!ELEMENT verbs-it (v)+>
    <!ATTLIST verbs-it
      xmlns CDATA #FIXED ''>

    <!ELEMENT v (i,t)> <!-- verb's conjugation information (infinitive, radical) -->
    <!ATTLIST v
      xmlns CDATA #FIXED ''>

    <!ELEMENT i (#PCDATA)>  <!-- infinitive -->
    <!ATTLIST i
      xmlns CDATA #FIXED ''>

    <!ELEMENT t (#PCDATA)> <!-- template (radical:termination) -->
    <!ATTLIST t
        xmlns CDATA #FIXED ''>
]>

<verbs-it>

<v><i>abbacchiare</i>		<t>studi:are</t></v>
<v><i>abbacinare</i>		<t>lav:are</t></v>
<v><i>abbagliare</i>		<t>abbagli:are</t></v>
<v><i>abbaiare</i>		<t>studi:are</t></v>
<v><i>abballare</i>		<t>lav:are</t></v>
<v><i>abballinare</i>		<t>lav:are</t></v>
<v><i>abbambinare</i>		<t>lav:are</t></v>
<v><i>abbancare</i>		<t>pag:are</t></v>
<v><i>abbandonare</i>		<t>lav:are</t></v>
<v><i>abbarbagliare</i>		<t>abbagli:are</t></v>
<v><i>abbarbare</i>		<t>lav:are</t></v>
<v><i>abbarbicare</i>		<t>pag:are</t></v>
<v><i>abbarcare</i>		<t>pag:are</t></v>
<v><i>abbarrare</i>		<t>lav:are</t></v>
<v><i>abbaruffare</i>		<t>lav:are</t></v>
<v><i>abbassare</i>		<t>lav:are</t></v>
<v><i>abbastare</i>		<t>abbast:are</t></v>
<v><i>abbattere</i>		<t>abbatt:ere</t></v>
<v><i>abbellire</i>		<t>pun:ire</t></v>
<v><i>abbeverare</i>		<t>lav:are</t></v>
<v><i>abbiadare</i>		<t>lav:are</t></v>
<v><i>abbicare</i>		<t>pag:are</t></v>
<v><i>abbiettare</i>		<t>lav:are</t></v>
<v><i>abbigliare</i>		<t>studi:are</t></v>
<v><i>abbinare</i>		<t>lav:are</t></v>
<v><i>abbindolare</i>		<t>lav:are</t></v>
<v><i>abbiosciare</i>		<t>abbiosc:iare</t></v>
<v><i>abbisciare</i>		<t>mang:iare</t></v>
<v><i>abbisognare</i>		<t>abbisogn:are</t></v>
<v><i>abbittare</i>		<t>lav:are</t></v>
<v><i>abboccare</i>		<t>pag:are</t></v>
<v><i>abbocconare</i>		<t>lav:are</t></v>
<v><i>abbominare</i>		<t>lav:are</t></v>
<v><i>abbonacciare</i>		<t>abbiosc:iare</t></v>
<v><i>abbonare</i>		<t>abb:onare</t></v>
<v><i>abbondare</i>		<t>lav:are</t></v>
<v><i>abbonire</i>		<t>pun:ire</t></v>
<v><i>abbordare</i>		<t>lav:are</t></v>
<v><i>abborracciare</i>		<t>mang:iare</t></v>
<v><i>abborrare</i>		<t>lav:are</t></v>
<v><i>abborrire</i>		<t>abborr:ire</t></v>
<v><i>abbottare</i>		<t>lav:are</t></v>
<v><i>abbottinare</i>		<t>lav:are</t></v>
<v><i>abbottonare</i>		<t>lav:are</t></v>
<v><i>abbozzare</i>		<t>lav:are</t></v>
<v><i>abbracciare</i>		<t>mang:iare</t></v>
<v><i>abbraciare</i>		<t>mang:iare</t></v>
<v><i>abbrancare</i>		<t>pag:are</t></v>
<v><i>abbreviare</i>		<t>studi:are</t></v>
<v><i>abbriccare</i>		<t>pag:are</t></v>
<v><i>abbrigliare</i>		<t>studi:are</t></v>
<v><i>abbrivare</i>		<t>lav:are</t></v>
<v><i>abbronzare</i>		<t>lav:are</t></v>
<v><i>abbronzire</i>		<t>vest:ire</t></v>
<v><i>abbruciacchiare</i>		<t>studi:are</t></v>
<v><i>abbruciare</i>		<t>mang:iare</t></v>
<v><i>abbrumare</i>		<t>abbast:are</t></v>
<v><i>abbrunare</i>		<t>lav:are</t></v>
<v><i>abbrunire</i>		<t>pun:ire</t></v>
<v><i>abbrusciare</i>		<t>mang:iare</t></v>
<v><i>abbrustiare</i>		<t>studi:are</t></v>
<v><i>abbrustolare</i>		<t>lav:are</t></v>
<v><i>abbrustolire</i>		<t>pun:ire</t></v>
<v><i>abbrutire</i>		<t>abbrut:ire</t></v>
<v><i>abbruttire</i>		<t>abbrut:ire</t></v>
<v><i>abbuiare</i>		<t>studi:are</t></v>
<v><i>abbuonare</i>		<t>lav:are</t></v>
<v><i>abburattare</i>		<t>lav:are</t></v>
<v><i>abbuzzire</i>		<t>pun:ire</t></v>
<v><i>abdicare</i>		<t>pag:are</t></v>
<v><i>abdurre</i>		<t>cond:urre</t></v>
<v><i>aberrare</i>		<t>lav:are</t></v>
<v><i>abiettare</i>		<t>lav:are</t></v>
<v><i>abilitare</i>		<t>lav:are</t></v>
<v><i>abitare</i>		<t>lav:are</t></v>
<v><i>abituare</i>		<t>lav:are</t></v>
<v><i>abiurare</i>		<t>lav:are</t></v>
<v><i>ablasmare</i>		<t>lav:are</t></v>
<v><i>abnegare</i>		<t>pag:are</t></v>
<v><i>abolire</i>		<t>pun:ire</t></v>
<v><i>abominare</i>		<t>lav:are</t></v>
<v><i>abondare</i>		<t>lav:are</t></v>
<v><i>aborrire</i>		<t>aborr:ire</t></v>
<v><i>abortire</i>		<t>abbrut:ire</t></v>
<v><i>abradere</i>		<t>ri:dere</t></v>
<v><i>abrogare</i>		<t>pag:are</t></v>
<v><i>abusare</i>		<t>lav:are</t></v>
<v><i>accadere</i>		<t>cad:ere</t></v>
<v><i>accaffare</i>		<t>lav:are</t></v>
<v><i>accagionare</i>		<t>lav:are</t></v>
<v><i>accagliare</i>		<t>studi:are</t></v>
<v><i>accalappiare</i>		<t>studi:are</t></v>
<v><i>accalcare</i>		<t>pag:are</t></v>
<v><i>accallare</i>		<t>lav:are</t></v>
<v><i>accalorare</i>		<t>lav:are</t></v>
<v><i>accalorire</i>		<t>pun:ire</t></v>
<v><i>accambiare</i>		<t>studi:are</t></v>
<v><i>accamiciare</i>		<t>mang:iare</t></v>
<v><i>accampare</i>		<t>lav:are</t></v>
<v><i>accampionare</i>		<t>lav:are</t></v>
<v><i>accanare</i>		<t>lav:are</t></v>
<v><i>accanirsi</i>		<t>pun:ire</t></v>
<v><i>accannellare</i>		<t>lav:are</t></v>
<v><i>accantonare</i>		<t>lav:are</t></v>
<v><i>accaparrare</i>		<t>lav:are</t></v>
<v><i>accapezzare</i>		<t>lav:are</t></v>
<v><i>accappiare</i>		<t>studi:are</t></v>
<v><i>accappiettare</i>		<t>lav:are</t></v>
<v><i>accapponare</i>		<t>lav:are</t></v>
<v><i>accapricciare</i>		<t>mang:iare</t></v>
<v><i>accareggiare</i>		<t>mang:iare</t></v>
<v><i>accarezzare</i>		<t>lav:are</t></v>
<v><i>accarnare</i>		<t>lav:are</t></v>
<v><i>accarpionare</i>		<t>lav:are</t></v>
<v><i>accartocciare</i>		<t>mang:iare</t></v>
<v><i>accasare</i>		<t>lav:are</t></v>
<v><i>accasciare</i>		<t>mang:iare</t></v>
<v><i>accasellare</i>		<t>lav:are</t></v>
<v><i>accasermare</i>		<t>lav:are</t></v>
<v><i>accastellare</i>		<t>lav:are</t></v>
<v><i>accatastare</i>		<t>lav:are</t></v>
<v><i>accattare</i>		<t>lav:are</t></v>
<v><i>accattivare</i>		<t>lav:are</t></v>
<v><i>accavalcare</i>		<t>pag:are</t></v>
<v><i>accavallare</i>		<t>lav:are</t></v>
<v><i>accecare</i>		<t>accec:are</t></v>
<v><i>accedere</i>		<t>acced:ere</t></v>
<v><i>acceffare</i>		<t>lav:are</t></v>
<v><i>accelerare</i>		<t>lav:are</t></v>
<v><i>accellerare</i>		<t>lav:are</t></v>
<v><i>accenciare</i>		<t>mang:iare</t></v>
<v><i>accendere</i>		<t>sce:ndere</t></v>
<v><i>accennare</i>		<t>lav:are</t></v>
<v><i>accensare</i>		<t>lav:are</t></v>
<v><i>accentare</i>		<t>lav:are</t></v>
<v><i>accentrare</i>		<t>lav:are</t></v>
<v><i>accentuare</i>		<t>lav:are</t></v>
<v><i>acceppare</i>		<t>lav:are</t></v>
<v><i>accerchiare</i>		<t>studi:are</t></v>
<v><i>accertare</i>		<t>lav:are</t></v>
<v><i>accestire</i>		<t>vest:ire</t></v>
<v><i>accettare</i>		<t>lav:are</t></v>
<v><i>accettilare</i>		<t>lav:are</t></v>
<v><i>acchetare</i>		<t>lav:are</t></v>
<v><i>acchiappare</i>		<t>lav:are</t></v>
<v><i>acchinare</i>		<t>lav:are</t></v>
<v><i>acchiocciolare</i>		<t>lav:are</t></v>
<v><i>acchitare</i>		<t>lav:are</t></v>
<v><i>acchittare</i>		<t>lav:are</t></v>
<v><i>acciabattare</i>		<t>lav:are</t></v>
<v><i>acciaccare</i>		<t>pag:are</t></v>
<v><i>acciaiare</i>		<t>studi:are</t></v>
<v><i>acciambellare</i>		<t>lav:are</t></v>
<v><i>acciarpare</i>		<t>lav:are</t></v>
<v><i>accidere</i>		<t>ri:dere</t></v>
<v><i>accidiare</i>		<t>studi:are</t></v>
<v><i>acciecare</i>		<t>pag:are</t></v>
<v><i>acciglionare</i>		<t>lav:are</t></v>
<v><i>accingere</i>		<t>vol:gere</t></v>
<v><i>accintolare</i>		<t>lav:are</t></v>
<v><i>acciottolare</i>		<t>lav:are</t></v>
<v><i>acciuffare</i>		<t>lav:are</t></v>
<v><i>accivettare</i>		<t>lav:are</t></v>
<v><i>acclamare</i>		<t>lav:are</t></v>
<v><i>acclarare</i>		<t>lav:are</t></v>
<v><i>acclimare</i>		<t>lav:are</t></v>
<v><i>acclimatare</i>		<t>lav:are</t></v>
<v><i>accludere</i>		<t>ri:dere</t></v>
<v><i>accoccare</i>		<t>pag:are</t></v>
<v><i>accodare</i>		<t>lav:are</t></v>
<v><i>accogliere</i>		<t>acco:gliere</t></v>
<v><i>accollare</i>		<t>lav:are</t></v>
<v><i>accoltellare</i>		<t>lav:are</t></v>
<v><i>accomiatare</i>		<t>lav:are</t></v>
<v><i>accomodare</i>		<t>lav:are</t></v>
<v><i>accompagnare</i>		<t>accompagn:are</t></v>
<v><i>accomunare</i>		<t>lav:are</t></v>
<v><i>acconciare</i>		<t>mang:iare</t></v>
<v><i>accondiscendere</i>		<t>sce:ndere</t></v>
<v><i>acconsentire</i>		<t>acconsent:ire</t></v>
<v><i>accontentare</i>		<t>lav:are</t></v>
<v><i>accoppare</i>		<t>lav:are</t></v>
<v><i>accoppiare</i>		<t>studi:are</t></v>
<v><i>accorare</i>		<t>lav:are</t></v>
<v><i>accorciare</i>		<t>abbiosc:iare</t></v>
<v><i>accordare</i>		<t>lav:are</t></v>
<v><i>accorpare</i>		<t>lav:are</t></v>
<v><i>accorrere</i>		<t>accor:rere</t></v>
<v><i>accostare</i>		<t>lav:are</t></v>
<v><i>accostumare</i>		<t>lav:are</t></v>
<v><i>accovonare</i>		<t>lav:are</t></v>
<v><i>accozzare</i>		<t>lav:are</t></v>
<v><i>accreditare</i>		<t>lav:are</t></v>
<v><i>accrescere</i>		<t>cono:scere</t></v>
<v><i>accudire</i>		<t>pun:ire</t></v>
<v><i>acculturare</i>		<t>lav:are</t></v>
<v><i>accumulare</i>		<t>lav:are</t></v>
<v><i>accusare</i>		<t>lav:are</t></v>
<v><i>acerbare</i>		<t>lav:are</t></v>
<v><i>acidificare</i>		<t>pag:are</t></v>
<v><i>acidulare</i>		<t>lav:are</t></v>
<v><i>acquarellare</i>		<t>lav:are</t></v>
<v><i>acquartierare</i>		<t>lav:are</t></v>
<v><i>acquattare</i>		<t>lav:are</t></v>
<v><i>acquerellare</i>		<t>lav:are</t></v>
<v><i>acquetare</i>		<t>lav:are</t></v>
<v><i>acquiescere</i>		<t>acquiesc:ere</t></v>
<v><i>acquietare</i>		<t>lav:are</t></v>
<v><i>acquisire</i>		<t>pun:ire</t></v>
<v><i>acquistare</i>		<t>lav:are</t></v>
<v><i>acuire</i>		<t>pun:ire</t></v>
<v><i>acuminare</i>		<t>lav:are</t></v>
<v><i>acutizzare</i>		<t>lav:are</t></v>
<v><i>adagiare</i>		<t>mang:iare</t></v>
<v><i>adattare</i>		<t>lav:are</t></v>
<v><i>addebitare</i>		<t>lav:are</t></v>
<v><i>addensare</i>		<t>lav:are</t></v>
<v><i>addentare</i>		<t>lav:are</t></v>
<v><i>addentellare</i>		<t>lav:are</t></v>
<v><i>addentrare</i>		<t>lav:are</t></v>
<v><i>addestrare</i>		<t>lav:are</t></v>
<v><i>addipanare</i>		<t>lav:are</t></v>
<v><i>addire</i>		<t>add:ire</t></v>
<v><i>addirizzare</i>		<t>lav:are</t></v>
<v><i>additare</i>		<t>lav:are</t></v>
<v><i>addivenire</i>		<t>addiv:enire</t></v>
<v><i>addizionare</i>		<t>lav:are</t></v>
<v><i>addobbare</i>		<t>lav:are</t></v>
<v><i>addogare</i>		<t>pag:are</t></v>
<v><i>addolcare</i>		<t>accec:are</t></v>
<v><i>addolcire</i>		<t>pun:ire</t></v>
<v><i>addolorare</i>		<t>lav:are</t></v>
<v><i>addomesticare</i>		<t>pag:are</t></v>
<v><i>addormentare</i>		<t>lav:are</t></v>
<v><i>addormire</i>		<t>vest:ire</t></v>
<v><i>addossare</i>		<t>lav:are</t></v>
<v><i>addottorare</i>		<t>lav:are</t></v>
<v><i>addottrinare</i>		<t>lav:are</t></v>
<v><i>addrizzare</i>		<t>lav:are</t></v>
<v><i>addurre</i>		<t>cond:urre</t></v>
<v><i>adeguare</i>		<t>lav:are</t></v>
<v><i>adempiere</i>		<t>adempi:ere</t></v>
<v><i>adempire</i>		<t>adempi:ere</t></v>
<v><i>adergere</i>		<t>vol:gere</t></v>
<v><i>aderire</i>		<t>pun:ire</t></v>
<v><i>aderizzare</i>		<t>lav:are</t></v>
<v><i>adescare</i>		<t>pag:are</t></v>
<v><i>adibire</i>		<t>pun:ire</t></v>
<v><i>adimare</i>		<t>lav:are</t></v>
<v><i>adire</i>		<t>pun:ire</t></v>
<v><i>adocchiare</i>		<t>studi:are</t></v>
<v><i>adombrare</i>		<t>lav:are</t></v>
<v><i>adontare</i>		<t>lav:are</t></v>
<v><i>adoperare</i>		<t>lav:are</t></v>
<v><i>adoprare</i>		<t>lav:are</t></v>
<v><i>adorare</i>		<t>lav:are</t></v>
<v><i>adornare</i>		<t>lav:are</t></v>
<v><i>adottare</i>		<t>lav:are</t></v>
<v><i>aduggiare</i>		<t>mang:iare</t></v>
<v><i>adugnare</i>		<t>adugn:are</t></v>
<v><i>adulare</i>		<t>lav:are</t></v>
<v><i>adulterare</i>		<t>lav:are</t></v>
<v><i>adunare</i>		<t>lav:are</t></v>
<v><i>adunghiare</i>		<t>studi:are</t></v>
<v><i>adusare</i>		<t>lav:are</t></v>
<v><i>aerare</i>		<t>lav:are</t></v>
<v><i>aerotrasportare</i>		<t>lav:are</t></v>
<v><i>affaccendare</i>		<t>lav:are</t></v>
<v><i>affacciare</i>		<t>mang:iare</t></v>
<v><i>affagottare</i>		<t>lav:are</t></v>
<v><i>affamare</i>		<t>lav:are</t></v>
<v><i>affannare</i>		<t>lav:are</t></v>
<v><i>affardellare</i>		<t>lav:are</t></v>
<v><i>affascinare</i>		<t>lav:are</t></v>
<v><i>affastellare</i>		<t>lav:are</t></v>
<v><i>affaticare</i>		<t>pag:are</t></v>
<v><i>affatturare</i>		<t>lav:are</t></v>
<v><i>affazzonare</i>		<t>lav:are</t></v>
<v><i>affermare</i>		<t>lav:are</t></v>
<v><i>afferrare</i>		<t>lav:are</t></v>
<v><i>affettare</i>		<t>lav:are</t></v>
<v><i>affezionare</i>		<t>lav:are</t></v>
<v><i>affiancare</i>		<t>pag:are</t></v>
<v><i>affiatare</i>		<t>lav:are</t></v>
<v><i>affibbiare</i>		<t>studi:are</t></v>
<v><i>affidare</i>		<t>lav:are</t></v>
<v><i>affievolire</i>		<t>pun:ire</t></v>
<v><i>affiggere</i>		<t>affi:ggere</t></v>
<v><i>affigliare</i>		<t>studi:are</t></v>
<v><i>affilare</i>		<t>lav:are</t></v>
<v><i>affiliare</i>		<t>studi:are</t></v>
<v><i>affinare</i>		<t>lav:are</t></v>
<v><i>affiocare</i>		<t>pag:are</t></v>
<v><i>affiochire</i>		<t>affioch:ire</t></v>
<v><i>affiorare</i>		<t>abbast:are</t></v>
<v><i>affittare</i>		<t>lav:are</t></v>
<v><i>affittire</i>		<t>abbrut:ire</t></v>
<v><i>affliggere</i>		<t>le:ggere</t></v>
<v><i>afflosciare</i>		<t>mang:iare</t></v>
<v><i>affloscire</i>		<t>vest:ire</t></v>
<v><i>affluire</i>		<t>abbrut:ire</t></v>
<v><i>affocare</i>		<t>pag:are</t></v>
<v><i>affogare</i>		<t>accec:are</t></v>
<v><i>affollare</i>		<t>lav:are</t></v>
<v><i>affondare</i>		<t>abbast:are</t></v>
<v><i>afforcare</i>		<t>pag:are</t></v>
<v><i>afforzare</i>		<t>lav:are</t></v>
<v><i>affossare</i>		<t>lav:are</t></v>
<v><i>affrancare</i>		<t>pag:are</t></v>
<v><i>affrangere</i>		<t>vol:gere</t></v>
<v><i>affratellare</i>		<t>lav:are</t></v>
<v><i>affrescare</i>		<t>pag:are</t></v>
<v><i>affrettare</i>		<t>lav:are</t></v>
<v><i>affrittellare</i>		<t>lav:are</t></v>
<v><i>affrontare</i>		<t>lav:are</t></v>
<v><i>affumicare</i>		<t>pag:are</t></v>
<v><i>affusolare</i>		<t>lav:are</t></v>
<v><i>agevolare</i>		<t>lav:are</t></v>
<v><i>aggallare</i>		<t>lav:are</t></v>
<v><i>agganciare</i>		<t>mang:iare</t></v>
<v><i>aggarbare</i>		<t>lav:are</t></v>
<v><i>aggeggiare</i>		<t>mang:iare</t></v>
<v><i>aggelare</i>		<t>abbast:are</t></v>
<v><i>aggettare</i>		<t>abbast:are</t></v>
<v><i>aggettivare</i>		<t>lav:are</t></v>
<v><i>agghiacciare</i>		<t>abbiosc:iare</t></v>
<v><i>agghiaiare</i>		<t>studi:are</t></v>
<v><i>agghindare</i>		<t>lav:are</t></v>
<v><i>aggiaccare</i>		<t>pag:are</t></v>
<v><i>aggiogare</i>		<t>pag:are</t></v>
<v><i>aggiornare</i>		<t>abbast:are</t></v>
<v><i>aggirare</i>		<t>lav:are</t></v>
<v><i>aggiudicare</i>		<t>pag:are</t></v>
<v><i>aggiungere</i>		<t>vol:gere</t></v>
<v><i>aggiuntare</i>		<t>lav:are</t></v>
<v><i>aggiustare</i>		<t>lav:are</t></v>
<v><i>agglomerare</i>		<t>lav:are</t></v>
<v><i>agglutinare</i>		<t>lav:are</t></v>
<v><i>aggobbire</i>		<t>abbrut:ire</t></v>
<v><i>aggomitolare</i>		<t>lav:are</t></v>
<v><i>aggottare</i>		<t>lav:are</t></v>
<v><i>aggradare</i>		<t>aggrada:re</t></v>
<v><i>aggradire</i>		<t>pun:ire</t></v>
<v><i>aggraffare</i>		<t>lav:are</t></v>
<v><i>aggraffiare</i>		<t>studi:are</t></v>
<v><i>aggraffignare</i>		<t>aggraffign:are</t></v>
<v><i>aggranchiare</i>		<t>abbagli:are</t></v>
<v><i>aggranchire</i>		<t>abbrut:ire</t></v>
<v><i>aggrandire</i>		<t>pun:ire</t></v>
<v><i>aggranfiare</i>		<t>studi:are</t></v>
<v><i>aggrappare</i>		<t>lav:are</t></v>
<v><i>aggraticciare</i>		<t>mang:iare</t></v>
<v><i>aggravare</i>		<t>abbast:are</t></v>
<v><i>aggraziare</i>		<t>studi:are</t></v>
<v><i>aggredire</i>		<t>pun:ire</t></v>
<v><i>aggregare</i>		<t>pag:are</t></v>
<v><i>aggrevare</i>		<t>lav:are</t></v>
<v><i>aggricciare</i>		<t>mang:iare</t></v>
<v><i>aggrinzare</i>		<t>abbast:are</t></v>
<v><i>aggrinzire</i>		<t>abbrut:ire</t></v>
<v><i>aggrommare</i>		<t>abbast:are</t></v>
<v><i>aggrondare</i>		<t>lav:are</t></v>
<v><i>aggrottare</i>		<t>lav:are</t></v>
<v><i>aggrovigliare</i>		<t>studi:are</t></v>
<v><i>aggrovigliolare</i>		<t>lav:are</t></v>
<v><i>aggrumare</i>		<t>lav:are</t></v>
<v><i>aggruppare</i>		<t>lav:are</t></v>
<v><i>agguagliare</i>		<t>studi:are</t></v>
<v><i>agguantare</i>		<t>lav:are</t></v>
<v><i>agguerrire</i>		<t>pun:ire</t></v>
<v><i>agire</i>		<t>pun:ire</t></v>
<v><i>agitare</i>		<t>lav:are</t></v>
<v><i>agognare</i>		<t>agogn:are</t></v>
<v><i>agonizzare</i>		<t>lav:are</t></v>
<v><i>agroppare</i>		<t>lav:are</t></v>
<v><i>agucchiare</i>		<t>studi:are</t></v>
<v><i>aguzzare</i>		<t>lav:are</t></v>
<v><i>aiutare</i>		<t>lav:are</t></v>
<v><i>aizzare</i>		<t>lav:are</t></v>
<v><i>alare</i>		<t>lav:are</t></v>
<v><i>albeggiare</i>		<t>abbiosc:iare</t></v>
<v><i>alberare</i>		<t>lav:are</t></v>
<v><i>albergare</i>		<t>pag:are</t></v>
<v><i>albicare</i>		<t>pag:are</t></v>
<v><i>alcolizzare</i>		<t>lav:are</t></v>
<v><i>aleggiare</i>		<t>mang:iare</t></v>
<v><i>alenare</i>		<t>lav:are</t></v>
<v><i>alfabetizzare</i>		<t>lav:are</t></v>
<v><i>algere</i>		<t>al:gere</t></v>
<v><i>aliare</i>		<t>studi:are</t></v>
<v><i>alienare</i>		<t>lav:are</t></v>
<v><i>alimentare</i>		<t>lav:are</t></v>
<v><i>alitare</i>		<t>lav:are</t></v>
<v><i>allacciare</i>		<t>mang:iare</t></v>
<v><i>allagare</i>		<t>pag:are</t></v>
<v><i>allampanare</i>		<t>abbast:are</t></v>
<v><i>allappare</i>		<t>lav:are</t></v>
<v><i>allargare</i>		<t>pag:are</t></v>
<v><i>allarmare</i>		<t>lav:are</t></v>
<v><i>allascare</i>		<t>pag:are</t></v>
<v><i>allattare</i>		<t>lav:are</t></v>
<v><i>alleare</i>		<t>lav:are</t></v>
<v><i>allegare</i>		<t>pag:are</t></v>
<v><i>alleggerire</i>		<t>pun:ire</t></v>
<v><i>allegorizzare</i>		<t>lav:are</t></v>
<v><i>allegrare</i>		<t>lav:are</t></v>
<v><i>allenare</i>		<t>lav:are</t></v>
<v><i>allentare</i>		<t>lav:are</t></v>
<v><i>allertare</i>		<t>lav:are</t></v>
<v><i>allessare</i>		<t>lav:are</t></v>
<v><i>allestire</i>		<t>pun:ire</t></v>
<v><i>allettare</i>		<t>lav:are</t></v>
<v><i>allevare</i>		<t>lav:are</t></v>
<v><i>alleviare</i>		<t>obli:are</t></v>
<v><i>allibare</i>		<t>lav:are</t></v>
<v><i>allibire</i>		<t>abbrut:ire</t></v>
<v><i>allibrare</i>		<t>lav:are</t></v>
<v><i>allicciare</i>		<t>mang:iare</t></v>
<v><i>allietare</i>		<t>lav:are</t></v>
<v><i>allignare</i>		<t>allign:are</t></v>
<v><i>allineare</i>		<t>lav:are</t></v>
<v><i>allivellare</i>		<t>lav:are</t></v>
<v><i>allividire</i>		<t>abbrut:ire</t></v>
<v><i>allocare</i>		<t>pag:are</t></v>
<v><i>alloccare</i>		<t>pag:are</t></v>
<v><i>allogare</i>		<t>pag:are</t></v>
<v><i>alloggiare</i>		<t>mang:iare</t></v>
<v><i>allontanare</i>		<t>lav:are</t></v>
<v><i>alloppiare</i>		<t>studi:are</t></v>
<v><i>allucinare</i>		<t>lav:are</t></v>
<v><i>alludere</i>		<t>ri:dere</t></v>
<v><i>allumacare</i>		<t>pag:are</t></v>
<v><i>allumare</i>		<t>lav:are</t></v>
<v><i>alluminare</i>		<t>lav:are</t></v>
<v><i>allunare</i>		<t>lav:are</t></v>
<v><i>allungare</i>		<t>pag:are</t></v>
<v><i>almanaccare</i>		<t>pag:are</t></v>
<v><i>alpeggiare</i>		<t>studi:are</t></v>
<v><i>altalenare</i>		<t>lav:are</t></v>
<v><i>alterare</i>		<t>lav:are</t></v>
<v><i>altercare</i>		<t>pag:are</t></v>
<v><i>alternare</i>		<t>lav:are</t></v>
<v><i>alzare</i>		<t>lav:are</t></v>
<v><i>amalgamare</i>		<t>lav:are</t></v>
<v><i>amare</i>		<t>lav:are</t></v>
<v><i>amareggiare</i>		<t>mang:iare</t></v>
<v><i>amarrare</i>		<t>lav:are</t></v>
<v><i>ambientare</i>		<t>lav:are</t></v>
<v><i>ambire</i>		<t>pun:ire</t></v>
<v><i>ambulare</i>		<t>lav:are</t></v>
<v><i>americanizzare</i>		<t>lav:are</t></v>
<v><i>amicare</i>		<t>pag:are</t></v>
<v><i>ammaccare</i>		<t>pag:are</t></v>
<v><i>ammaestrare</i>		<t>lav:are</t></v>
<v><i>ammagliare</i>		<t>studi:are</t></v>
<v><i>ammaiare</i>		<t>studi:are</t></v>
<v><i>ammainare</i>		<t>lav:are</t></v>
<v><i>ammalare</i>		<t>lav:are</t></v>
<v><i>ammaliare</i>		<t>studi:are</t></v>
<v><i>ammalinconire</i>		<t>abbrut:ire</t></v>
<v><i>ammalizziare</i>		<t>studi:are</t></v>
<v><i>ammalizzire</i>		<t>abbrut:ire</t></v>
<v><i>ammanettare</i>		<t>lav:are</t></v>
<v><i>ammanierare</i>		<t>lav:are</t></v>
<v><i>ammanigliare</i>		<t>studi:are</t></v>
<v><i>ammannare</i>		<t>lav:are</t></v>
<v><i>ammannire</i>		<t>pun:ire</t></v>
<v><i>ammansare</i>		<t>lav:are</t></v>
<v><i>ammansire</i>		<t>pun:ire</t></v>
<v><i>ammantare</i>		<t>lav:are</t></v>
<v><i>ammantellare</i>		<t>lav:are</t></v>
<v><i>ammarare</i>		<t>abbast:are</t></v>
<v><i>ammarrare</i>		<t>lav:are</t></v>
<v><i>ammassare</i>		<t>lav:are</t></v>
<v><i>ammassellare</i>		<t>lav:are</t></v>
<v><i>ammassicciare</i>		<t>mang:iare</t></v>
<v><i>ammatassare</i>		<t>lav:are</t></v>
<v><i>ammattare</i>		<t>lav:are</t></v>
<v><i>ammattire</i>		<t>abbrut:ire</t></v>
<v><i>ammattonare</i>		<t>lav:are</t></v>
<v><i>ammazzare</i>		<t>lav:are</t></v>
<v><i>ammelmare</i>		<t>abbast:are</t></v>
<v><i>ammenare</i>		<t>lav:are</t></v>
<v><i>ammencire</i>		<t>abbrut:ire</t></v>
<v><i>ammennicolare</i>		<t>lav:are</t></v>
<v><i>ammestare</i>		<t>lav:are</t></v>
<v><i>ammetare</i>		<t>lav:are</t></v>
<v><i>ammettere</i>		<t>amm:ettere</t></v>
<v><i>ammezzare</i>		<t>lav:are</t></v>
<v><i>ammezzire</i>		<t>abbrut:ire</t></v>
<v><i>ammiccare</i>		<t>pag:are</t></v>
<v><i>amminicolare</i>		<t>lav:are</t></v>
<v><i>amministrare</i>		<t>lav:are</t></v>
<v><i>amminutare</i>		<t>lav:are</t></v>
<v><i>ammirare</i>		<t>lav:are</t></v>
<v><i>ammiserire</i>		<t>pun:ire</t></v>
<v><i>ammobiliare</i>		<t>obli:are</t></v>
<v><i>ammodernare</i>		<t>lav:are</t></v>
<v><i>ammogliare</i>		<t>studi:are</t></v>
<v><i>ammollare</i>		<t>lav:are</t></v>
<v><i>ammollire</i>		<t>pun:ire</t></v>
<v><i>ammonire</i>		<t>pun:ire</t></v>
<v><i>ammontare</i>		<t>abbast:are</t></v>
<v><i>ammonticchiare</i>		<t>studi:are</t></v>
<v><i>ammorbare</i>		<t>lav:are</t></v>
<v><i>ammorbidare</i>		<t>lav:are</t></v>
<v><i>ammorbidire</i>		<t>abbrut:ire</t></v>
<v><i>ammorsare</i>		<t>lav:are</t></v>
<v><i>ammortare</i>		<t>lav:are</t></v>
<v><i>ammortire</i>		<t>pun:ire</t></v>
<v><i>ammortizzare</i>		<t>lav:are</t></v>
<v><i>ammorzare</i>		<t>lav:are</t></v>
<v><i>ammosciare</i>		<t>abbiosc:iare</t></v>
<v><i>ammoscire</i>		<t>abbrut:ire</t></v>
<v><i>ammostare</i>		<t>lav:are</t></v>
<v><i>ammucchiare</i>		<t>studi:are</t></v>
<v><i>ammucidire</i>		<t>abbrut:ire</t></v>
<v><i>ammuffare</i>		<t>abbast:are</t></v>
<v><i>ammuffire</i>		<t>abbrut:ire</t></v>
<v><i>ammusare</i>		<t>abbast:are</t></v>
<v><i>ammusire</i>		<t>abbrut:ire</t></v>
<v><i>ammutinare</i>		<t>lav:are</t></v>
<v><i>ammutire</i>		<t>abbrut:ire</t></v>
<v><i>ammutolire</i>		<t>abbrut:ire</t></v>
<v><i>amnistiare</i>		<t>obli:are</t></v>
<v><i>amoreggiare</i>		<t>mang:iare</t></v>
<v><i>ampliare</i>		<t>studi:are</t></v>
<v><i>amplificare</i>		<t>pag:are</t></v>
<v><i>amputare</i>		<t>lav:are</t></v>
<v><i>analizzare</i>		<t>lav:are</t></v>
<v><i>anastomizzare</i>		<t>lav:are</t></v>
<v><i>anatematizzare</i>		<t>lav:are</t></v>
<v><i>anatemizzare</i>		<t>lav:are</t></v>
<v><i>anatomizzare</i>		<t>lav:are</t></v>
<v><i>ancheggiare</i>		<t>mang:iare</t></v>
<v><i>anchilosare</i>		<t>lav:are</t></v>
<v><i>ancorare</i>		<t>lav:are</t></v>
<v><i>andare</i>		<t>:andare</t></v>
<v><i>andicappare</i>		<t>lav:are</t></v>
<v><i>anelare</i>		<t>lav:are</t></v>
<v><i>anellare</i>		<t>lav:are</t></v>
<v><i>anestetizzare</i>		<t>lav:are</t></v>
<v><i>anfanare</i>		<t>lav:are</t></v>
<v><i>anfaneggiare</i>		<t>mang:iare</t></v>
<v><i>angariare</i>		<t>studi:are</t></v>
<v><i>angarieggiare</i>		<t>mang:iare</t></v>
<v><i>angere</i>		<t>ange:re</t></v>
<v><i>anglicizzare</i>		<t>lav:are</t></v>
<v><i>angolare</i>		<t>lav:are</t></v>
<v><i>angosciare</i>		<t>mang:iare</t></v>
<v><i>angustiare</i>		<t>studi:are</t></v>
<v><i>animare</i>		<t>lav:are</t></v>
<v><i>annacquare</i>		<t>lav:are</t></v>
<v><i>annaffiare</i>		<t>studi:are</t></v>
<v><i>annaspare</i>		<t>lav:are</t></v>
<v><i>annebbiare</i>		<t>abbagli:are</t></v>
<v><i>annegare</i>		<t>accec:are</t></v>
<v><i>anneghittire</i>		<t>abbrut:ire</t></v>
<v><i>annerare</i>		<t>lav:are</t></v>
<v><i>annerire</i>		<t>abbrut:ire</t></v>
<v><i>annettere</i>		<t>anne:ttere</t></v>
<v><i>annichilare</i>		<t>lav:are</t></v>
<v><i>annichilire</i>		<t>pun:ire</t></v>
<v><i>annidare</i>		<t>lav:are</t></v>
<v><i>annientare</i>		<t>lav:are</t></v>
<v><i>annitrire</i>		<t>pun:ire</t></v>
<v><i>annobiliare</i>		<t>studi:are</t></v>
<v><i>annobilire</i>		<t>pun:ire</t></v>
<v><i>annoccare</i>		<t>pag:are</t></v>
<v><i>annodare</i>		<t>lav:are</t></v>
<v><i>annoiare</i>		<t>studi:are</t></v>
<v><i>annotare</i>		<t>lav:are</t></v>
<v><i>annottare</i>		<t>annott:are</t></v>
<v><i>annoverare</i>		<t>lav:are</t></v>
<v><i>annuire</i>		<t>pun:ire</t></v>
<v><i>annullare</i>		<t>lav:are</t></v>
<v><i>annunciare</i>		<t>mang:iare</t></v>
<v><i>annunziare</i>		<t>studi:are</t></v>
<v><i>annusare</i>		<t>lav:are</t></v>
<v><i>annuvolare</i>		<t>lav:are</t></v>
<v><i>ansare</i>		<t>lav:are</t></v>
<v><i>ansimare</i>		<t>lav:are</t></v>
<v><i>antecedere</i>		<t>anteced:ere</t></v>
<v><i>anteporre</i>		<t>po:rre</t></v>
<v><i>anticipare</i>		<t>lav:are</t></v>
<v><i>antidatare</i>		<t>lav:are</t></v>
<v><i>antivedere</i>		<t>antiv:edere</t></v>
<v><i>antivenire</i>		<t>antiv:enire</t></v>
<v><i>apocopare</i>		<t>lav:are</t></v>
<v><i>apologizzare</i>		<t>lav:are</t></v>
<v><i>apostatare</i>		<t>lav:are</t></v>
<v><i>apostrofare</i>		<t>lav:are</t></v>
<v><i>appaciare</i>		<t>mang:iare</t></v>
<v><i>appacificare</i>		<t>pag:are</t></v>
<v><i>appagare</i>		<t>pag:are</t></v>
<v><i>appaiare</i>		<t>studi:are</t></v>
<v><i>appallottolare</i>		<t>lav:are</t></v>
<v><i>appaltare</i>		<t>lav:are</t></v>
<v><i>appannare</i>		<t>lav:are</t></v>
<v><i>apparecchiare</i>		<t>studi:are</t></v>
<v><i>apparentare</i>		<t>lav:are</t></v>
<v><i>apparigliare</i>		<t>studi:are</t></v>
<v><i>apparire</i>		<t>appar:ire</t></v>
<v><i>appartare</i>		<t>lav:are</t></v>
<v><i>appartenere</i>		<t>appart:enere</t></v>
<v><i>appassionare</i>		<t>lav:are</t></v>
<v><i>appassire</i>		<t>abbrut:ire</t></v>
<v><i>appellare</i>		<t>lav:are</t></v>
<v><i>appenare</i>		<t>lav:are</t></v>
<v><i>appendere</i>		<t>sce:ndere</t></v>
<v><i>appennellare</i>		<t>lav:are</t></v>
<v><i>appesantire</i>		<t>pun:ire</t></v>
<v><i>appestare</i>		<t>lav:are</t></v>
<v><i>appetire</i>		<t>pun:ire</t></v>
<v><i>appettare</i>		<t>lav:are</t></v>
<v><i>appezzare</i>		<t>lav:are</t></v>
<v><i>appianare</i>		<t>lav:are</t></v>
<v><i>appiattare</i>		<t>lav:are</t></v>
<v><i>appiattire</i>		<t>pun:ire</t></v>
<v><i>appiccare</i>		<t>pag:are</t></v>
<v><i>appicciare</i>		<t>mang:iare</t></v>
<v><i>appiccicare</i>		<t>pag:are</t></v>
<v><i>appiccinire</i>		<t>pun:ire</t></v>
<v><i>appicciolire</i>		<t>pun:ire</t></v>
<v><i>appiedare</i>		<t>lav:are</t></v>
<v><i>appigionare</i>		<t>lav:are</t></v>
<v><i>appinzare</i>		<t>lav:are</t></v>
<v><i>appiombare</i>		<t>lav:are</t></v>
<v><i>appioppare</i>		<t>lav:are</t></v>
<v><i>applaudire</i>		<t>applaud:ire</t></v>
<v><i>applicare</i>		<t>pag:are</t></v>
<v><i>appoderare</i>		<t>lav:are</t></v>
<v><i>appoggiare</i>		<t>mang:iare</t></v>
<v><i>apporre</i>		<t>po:rre</t></v>
<v><i>apportare</i>		<t>lav:are</t></v>
<v><i>appostare</i>		<t>lav:are</t></v>
<v><i>appratire</i>		<t>pun:ire</t></v>
<v><i>apprendere</i>		<t>sce:ndere</t></v>
<v><i>appressare</i>		<t>lav:are</t></v>
<v><i>apprestare</i>		<t>lav:are</t></v>
<v><i>apprettare</i>		<t>lav:are</t></v>
<v><i>apprezzare</i>		<t>lav:are</t></v>
<v><i>approdare</i>		<t>abbast:are</t></v>
<v><i>approfittare</i>		<t>lav:are</t></v>
<v><i>approfondare</i>		<t>lav:are</t></v>
<v><i>approfondire</i>		<t>pun:ire</t></v>
<v><i>approntare</i>		<t>lav:are</t></v>
<v><i>appropinquare</i>		<t>abbast:are</t></v>
<v><i>appropriare</i>		<t>studi:are</t></v>
<v><i>approssimare</i>		<t>lav:are</t></v>
<v><i>approvare</i>		<t>lav:are</t></v>
<v><i>approvisionare</i>		<t>lav:are</t></v>
<v><i>approvvigionare</i>		<t>lav:are</t></v>
<v><i>appruare</i>		<t>lav:are</t></v>
<v><i>appuntare</i>		<t>lav:are</t></v>
<v><i>appuntellare</i>		<t>lav:are</t></v>
<v><i>appuntire</i>		<t>pun:ire</t></v>
<v><i>appurare</i>		<t>lav:are</t></v>
<v><i>appuzzare</i>		<t>lav:are</t></v>
<v><i>aprire</i>		<t>ap:rire</t></v>
<v><i>arabescare</i>		<t>pag:are</t></v>
<v><i>arare</i>		<t>lav:are</t></v>
<v><i>arbitrare</i>		<t>lav:are</t></v>
<v><i>arborare</i>		<t>lav:are</t></v>
<v><i>arcaizzare</i>		<t>lav:are</t></v>
<v><i>arcare</i>		<t>pag:are</t></v>
<v><i>archeggiare</i>		<t>mang:iare</t></v>
<v><i>archibugiare</i>		<t>mang:iare</t></v>
<v><i>architettare</i>		<t>lav:are</t></v>
<v><i>archiviare</i>		<t>studi:are</t></v>
<v><i>arcuare</i>		<t>lav:are</t></v>
<v><i>ardere</i>		<t>ar:dere</t></v>
<v><i>ardire</i>		<t>:ardire</t></v>
<v><i>areare</i>		<t>lav:are</t></v>
<v><i>arenare</i>		<t>lav:are</t></v>
<v><i>argentare</i>		<t>lav:are</t></v>
<v><i>arginare</i>		<t>lav:are</t></v>
<v><i>argomentare</i>		<t>lav:are</t></v>
<v><i>arguire</i>		<t>pun:ire</t></v>
<v><i>arianizzare</i>		<t>lav:are</t></v>
<v><i>arieggiare</i>		<t>mang:iare</t></v>
<v><i>arietare</i>		<t>lav:are</t></v>
<v><i>armare</i>		<t>lav:are</t></v>
<v><i>armeggiare</i>		<t>mang:iare</t></v>
<v><i>armonizzare</i>		<t>lav:are</t></v>
<v><i>aromatizzare</i>		<t>lav:are</t></v>
<v><i>arpeggiare</i>		<t>mang:iare</t></v>
<v><i>arpionare</i>		<t>lav:are</t></v>