<?xml version="1.0"?>

<!--
	verbs-fr.xml - List of French verbs with their conjugation template
	Copyright (C) 2003-2016 Pierre Sarrazin <http://sarrazip.com/>
	
	English translations added by Brett Tolbert
	<https://github.com/bretttolbert/verbecc>

	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with this program; if not, write to the Free Software
	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
	02110-1301, USA.
-->

<!DOCTYPE verbs-fr [
	<!ELEMENT verbs-fr (v+)>
	<!ELEMENT v (i, t, aspirate-h?)>
	<!ELEMENT i (#PCDATA)>  <!-- infinitive -->
	<!ELEMENT t (#PCDATA)>	<!-- template (radical:termination) -->
	<!ELEMENT en (#PCDATA)>  <!-- english translation -->
	<!ELEMENT aspirate-h EMPTY>  <!-- useful for verbs starting with h -->
]>

<!--
	The <v> lines are sorted with this filter:
	env LANG=en_US.utf8 sort -f
-->

<verbs-fr>

<v><i>abaisser</i><t>aim:er</t><en>lower</en></v>
<v><i>abandonner</i><t>aim:er</t><en>abandon</en></v>
<v><i>abasourdir</i><t>fin:ir</t><en>stun</en></v>
<v><i>abâtardir</i><t>fin:ir</t><en>bastardize</en></v>
<v><i>abattre</i><t>bat:tre</t><en>tear down</en></v>
<v><i>abcéder</i><t>c:éder</t><en>abscess</en></v>
<v><i>abdiquer</i><t>aim:er</t><en>abdicate</en></v>
<v><i>aberrer</i><t>aim:er</t><en>err</en></v>
<v><i>abêtir</i><t>fin:ir</t><en>stultify</en></v>
<v><i>abhorrer</i><t>aim:er</t><en>abhor</en></v>
<v><i>abîmer</i><t>aim:er</t><en>spoil</en></v>
<v><i>abjurer</i><t>aim:er</t><en>recant</en></v>
<v><i>ablater</i><t>aim:er</t><en>ablate</en></v>
<v><i>abloquer</i><t>aim:er</t><en>clamp</en></v>
<v><i>abolir</i><t>fin:ir</t><en>abolish</en></v>
<v><i>abominer</i><t>aim:er</t><en>abominate</en></v>
<v><i>abonder</i><t>aim:er</t><en>abound</en></v>
<v><i>abonner</i><t>aim:er</t><en>subscribe</en></v>
<v><i>abonnir</i><t>fin:ir</t><en>improve</en></v>
<v><i>aborder</i><t>aim:er</t><en>approach</en></v>
<v><i>aboucher</i><t>aim:er</t><en>confer</en></v>
<v><i>abouler</i><t>aim:er</t><en>roll along a surface</en></v>
<v><i>abouter</i><t>aim:er</t><en>join, link, attach or tie together by their extremities</en></v>
<v><i>aboutir</i><t>fin:ir</t><en>lead to</en></v>
<v><i>aboyer</i><t>netto:yer</t><en>bark</en></v>
<v><i>abraser</i><t>aim:er</t><en>abrade</en></v>
<v><i>abréger</i><t>abr:éger</t><en>shorten</en></v>
<v><i>abreuver</i><t>aim:er</t><en>drink</en></v>
<v><i>abrévier</i><t>aim:er</t><en>abbreviate</en></v>
<v><i>abricoter</i><t>aim:er</t><en>glaze with a thin layer of apricot preserve</en></v>
<v><i>abrier</i><t>aim:er</t><en>cover</en></v>
<v><i>abriter</i><t>aim:er</t><en>house, to shelter, to harbour</en></v>
<v><i>abroger</i><t>man:ger</t><en>repeal</en></v>
<v><i>abrutir</i><t>fin:ir</t><en>stupefy</en></v>
<v><i>absenter</i><t>aim:er</t><en>off</en></v>
<v><i>absorber</i><t>aim:er</t><en>absorb</en></v>
<v><i>absoudre</i><t>abso:udre</t><en>absolve</en></v>
<v><i>abstenir</i><t>t:enir</t><en>refrain</en></v>
<v><i>abstraire</i><t>extra:ire</t><en>abstract</en></v>
<v><i>abuser</i><t>aim:er</t><en>abuse</en></v>
<v><i>accabler</i><t>aim:er</t><en>overwhelm</en></v>
<v><i>accaparer</i><t>aim:er</t><en>monopolize</en></v>
<v><i>accastiller</i><t>aim:er</t><en>accastiller</en></v>
<v><i>accéder</i><t>c:éder</t><en>access</en></v>
<v><i>accélérer</i><t>réf:érer</t><en>accelerate</en></v>
<v><i>accentuer</i><t>aim:er</t><en>accentuate</en></v>
<v><i>accepter</i><t>aim:er</t><en>accept</en></v>
<v><i>accessoiriser</i><t>aim:er</t><en>accessorize</en></v>
<v><i>accidenter</i><t>aim:er</t><en>hurt (in an accident)</en></v>
<v><i>acclamer</i><t>aim:er</t><en>cheer</en></v>
<v><i>acclimater</i><t>aim:er</t><en>acclimatize</en></v>
<v><i>accointer</i><t>aim:er</t><en>acquaint</en></v>
<v><i>accoler</i><t>aim:er</t><en>append</en></v>
<v><i>accommoder</i><t>aim:er</t><en>accommodate</en></v>
<v><i>accompagner</i><t>aim:er</t><en>accompany</en></v>
<v><i>accomplir</i><t>fin:ir</t><en>accomplish</en></v>
<v><i>accorder</i><t>aim:er</t><en>grant</en></v>
<v><i>accorer</i><t>aim:er</t><en>support in any way</en></v>
<v><i>accoster</i><t>aim:er</t><en>land</en></v>
<v><i>accoter</i><t>aim:er</t><en>lean against</en></v>
<v><i>accoucher</i><t>aim:er</t><en>birth</en></v>
<v><i>accouder</i><t>aim:er</t><en>lean</en></v>
<v><i>accouer</i><t>aim:er</t><en>tie the horses one behind the other</en></v>
<v><i>accoupler</i><t>aim:er</t><en>mate</en></v>
<v><i>accourcir</i><t>fin:ir</t><en>shorten</en></v>
<v><i>accourir</i><t>cour:ir</t><en>rush</en></v>
<v><i>accoutrer</i><t>aim:er</t><en>accoutrer</en></v>
<v><i>accoutumer</i><t>aim:er</t><en>accustom</en></v>
<v><i>accréditer</i><t>aim:er</t><en>accredit</en></v>
<v><i>accréter</i><t>décr:éter</t><en>accrete</en></v>
<v><i>accrocher</i><t>aim:er</t><en>hang</en></v>
<v><i>accroître</i><t>accr:oître</t><en>increase</en></v>
<v><i>accroupir</i><t>fin:ir</t><en>crouch</en></v>
<v><i>accueillir</i><t>cueill:ir</t><en>welcome</en></v>
<v><i>acculer</i><t>aim:er</t><en>cornering</en></v>
<v><i>acculturer</i><t>aim:er</t><en>acculturate</en></v>
<v><i>accumuler</i><t>aim:er</t><en>accumulate</en></v>
<v><i>accuser</i><t>aim:er</t><en>accuse</en></v>
<v><i>acérer</i><t>réf:érer</t><en>acérer</en></v>
<v><i>acétifier</i><t>aim:er</t><en>acetify</en></v>
<v><i>acétyler</i><t>aim:er</t><en>acetylate</en></v>
<v><i>achalander</i><t>aim:er</t><en>achalander</en></v>
<v><i>achaler</i><t>aim:er</t><en>achaler</en></v>
<v><i>acharner</i><t>aim:er</t><en>acharner</en></v>
<v><i>acheminer</i><t>aim:er</t><en>route</en></v>
<v><i>acheter</i><t>ach:eter</t><en>buy</en></v>
<v><i>achever</i><t>l:ever</t><en>finish</en></v>
<v><i>achopper</i><t>aim:er</t><en>stumble</en></v>
<v><i>achromatiser</i><t>aim:er</t><en>achromatiser</en></v>
<v><i>acidifier</i><t>aim:er</t><en>acidify</en></v>
<v><i>aciduler</i><t>aim:er</t><en>acidulate</en></v>
<v><i>aciérer</i><t>réf:érer</t><en>aciérer</en></v>
<v><i>aciseler</i><t>p:eler</t><en>aciseler</en></v>
<v><i>acoquiner</i><t>aim:er</t><en>cozy up</en></v>
<v><i>acquérir</i><t>acqu:érir</t><en>acquire</en></v>
<v><i>acquiescer</i><t>pla:cer</t><en>acquiesce</en></v>
<v><i>acquitter</i><t>aim:er</t><en>discharge</en></v>
<v><i>acter</i><t>aim:er</t><en>record</en></v>
<v><i>actionner</i><t>aim:er</t><en>activate</en></v>
<v><i>activer</i><t>aim:er</t><en>activate</en></v>
<v><i>actualiser</i><t>aim:er</t><en>actualize</en></v>
<v><i>adapter</i><t>aim:er</t><en>adapt</en></v>
<v><i>additionner</i><t>aim:er</t><en>add</en></v>
<v><i>adhérer</i><t>réf:érer</t><en>join</en></v>
<v><i>adjectiver</i><t>aim:er</t><en>adjectiver</en></v>
<v><i>adjectiviser</i><t>aim:er</t><en>adjectiviser</en></v>
<v><i>adjoindre</i><t>crai:ndre</t><en>adjoin</en></v>
<v><i>adjuger</i><t>man:ger</t><en>award</en></v>
<v><i>adjurer</i><t>aim:er</t><en>adjure</en></v>
<v><i>admettre</i><t>m:ettre</t><en>admit</en></v>
<v><i>administrer</i><t>aim:er</t><en>administer</en></v>
<v><i>admirer</i><t>aim:er</t><en>admire</en></v>
<v><i>admonester</i><t>aim:er</t><en>admonish</en></v>
<v><i>adonner</i><t>aim:er</t><en>engage</en></v>
<v><i>adopter</i><t>aim:er</t><en>adopt</en></v>
<v><i>adorer</i><t>aim:er</t><en>worship</en></v>
<v><i>adosser</i><t>aim:er</t><en>lean</en></v>
<v><i>adouber</i><t>aim:er</t><en>adouber</en></v>
<v><i>adoucir</i><t>fin:ir</t><en>soften</en></v>
<v><i>adresser</i><t>aim:er</t><en>address</en></v>
<v><i>adsorber</i><t>aim:er</t><en>adsorb</en></v>
<v><i>aduler</i><t>aim:er</t><en>adulate</en></v>
<v><i>adultérer</i><t>réf:érer</t><en>adulterate</en></v>
<v><i>advenir</i><t>adv:enir</t><en>happen</en></v>
<v><i>aérer</i><t>réf:érer</t><en>air</en></v>
<v><i>affabuler</i><t>aim:er</t><en>fantasize</en></v>
<v><i>affadir</i><t>fin:ir</t><en>fade</en></v>
<v><i>affaiblir</i><t>fin:ir</t><en>weaken</en></v>
<v><i>affairer</i><t>aim:er</t><en>bustling</en></v>
<v><i>affaisser</i><t>aim:er</t><en>subside</en></v>
<v><i>affaler</i><t>aim:er</t><en>haul down</en></v>
<v><i>affamer</i><t>aim:er</t><en>starve</en></v>
<v><i>afféager</i><t>man:ger</t><en>afféager</en></v>
<v><i>affecter</i><t>aim:er</t><en>affect</en></v>
<v><i>affectionner</i><t>aim:er</t><en>affectionner</en></v>
<v><i>affermer</i><t>aim:er</t><en>lease</en></v>
<v><i>affermir</i><t>fin:ir</t><en>firm</en></v>
<v><i>afficher</i><t>aim:er</t><en>display</en></v>
<v><i>affiler</i><t>aim:er</t><en>sharpen</en></v>
<v><i>affilier</i><t>aim:er</t><en>affiliate</en></v>
<v><i>affiner</i><t>aim:er</t><en>refine</en></v>
<v><i>affirmer</i><t>aim:er</t><en>assert</en></v>
<v><i>affleurer</i><t>aim:er</t><en>outcrop</en></v>
<v><i>affliger</i><t>man:ger</t><en>afflict</en></v>
<v><i>afflouer</i><t>aim:er</t><en>afflouer</en></v>
<v><i>affluer</i><t>aim:er</t><en>flow</en></v>
<v><i>affoler</i><t>aim:er</t><en>panic</en></v>
<v><i>affouager</i><t>man:ger</t><en>affouager</en></v>
<v><i>affouiller</i><t>aim:er</t><en>scour</en></v>
<v><i>affourager</i><t>man:ger</t><en>affourager</en></v>
<v><i>affourcher</i><t>aim:er</t><en>affourcher</en></v>
<v><i>affourrager</i><t>man:ger</t><en>affourrager</en></v>
<v><i>affranchir</i><t>fin:ir</t><en>frank</en></v>
<v><i>affréter</i><t>décr:éter</t><en>charter</en></v>
<v><i>affriander</i><t>aim:er</t><en>affriander</en></v>
<v><i>affricher</i><t>aim:er</t><en>affricher</en></v>
<v><i>affrioler</i><t>aim:er</t><en>affrioler</en></v>
<v><i>affriter</i><t>aim:er</t><en>affriter</en></v>
<v><i>affronter</i><t>aim:er</t><en>confront</en></v>
<v><i>affruiter</i><t>aim:er</t><en>affruiter</en></v>
<v><i>affubler</i><t>aim:er</t><en>dress up</en></v>
<v><i>affurer</i><t>aim:er</t><en>fecure</en></v>
<v><i>affûter</i><t>aim:er</t><en>grind</en></v>
<v><i>africaniser</i><t>aim:er</t><en>Africanize</en></v>
<v><i>agacer</i><t>pla:cer</t><en>annoy</en></v>
<v><i>agencer</i><t>pla:cer</t><en>match</en></v>
<v><i>agender</i><t>aim:er</t><en>agender</en></v>
<v><i>agenouiller</i><t>aim:er</t><en>kneel</en></v>
<v><i>agglomérer</i><t>réf:érer</t><en>agglomerate</en></v>
<v><i>agglutiner</i><t>aim:er</t><en>agglutinate</en></v>
<v><i>aggraver</i><t>aim:er</t><en>aggravate</en></v>
<v><i>agioter</i><t>aim:er</t><en>agioter</en></v>
<v><i>agir</i><t>fin:ir</t><en>act</en></v>
<v><i>agiter</i><t>aim:er</t><en>shake</en></v>
<v><i>agneler</i><t>app:eler</t><en>lamb</en></v>
<v><i>agoniser</i><t>aim:er</t><en>agonize</en></v>
<v><i>agrafer</i><t>aim:er</t><en>staple</en></v>
<v><i>agrainer</i><t>aim:er</t><en>agrainer</en></v>
<v><i>agrandir</i><t>fin:ir</t><en>enlarge</en></v>
<v><i>agréer</i><t>aim:er</t><en>accredit</en></v>
<v><i>agréger</i><t>abr:éger</t><en>aggregate</en></v>
<v><i>agrémenter</i><t>aim:er</t><en>embellish</en></v>
<v><i>agresser</i><t>aim:er</t><en>attack</en></v>
<v><i>agricher</i><t>aim:er</t><en>Agricher</en></v>
<v><i>agriffer</i><t>aim:er</t><en>agriffer</en></v>
<v><i>agripper</i><t>aim:er</t><en>grab</en></v>
<v><i>aguerrir</i><t>fin:ir</t><en>harden</en></v>
<v><i>aguicher</i><t>aim:er</t><en>tease</en></v>
<v><i>ahaner</i><t>aim:er</t><en>ahaner</en></v>
<v><i>ahurir</i><t>fin:ir</t><en>astonish</en></v>
<v><i>aider</i><t>aim:er</t><en>help</en></v>
<v><i>aigrir</i><t>fin:ir</t><en>sour</en></v>
<v><i>aiguiller</i><t>aim:er</t><en>switch</en></v>
<v><i>aiguilleter</i><t>j:eter</t><en>needling</en></v>
<v><i>aiguillonner</i><t>aim:er</t><en>goad</en></v>
<v><i>aiguiser</i><t>aim:er</t><en>whet</en></v>
<v><i>ailler</i><t>aim:er</t><en>ork</en></v>
<v><i>aimanter</i><t>aim:er</t><en>magnetize</en></v>
<v><i>aimer</i><t>aim:er</t><en>love</en></v>
<v><i>airer</i><t>aim:er</t><en>airer</en></v>
<v><i>ajointer</i><t>aim:er</t><en>ajointer</en></v>
<v><i>ajourer</i><t>aim:er</t><en>ajourer</en></v>
<v><i>ajourner</i><t>aim:er</t><en>adjourn</en></v>
<v><i>ajouter</i><t>aim:er</t><en>add</en></v>
<v><i>ajuster</i><t>aim:er</t><en>adjust</en></v>
<v><i>alambiquer</i><t>aim:er</t><en>alambiquer</en></v>
<v><i>alanguir</i><t>fin:ir</t><en>languish</en></v>
<v><i>alarmer</i><t>aim:er</t><en>alarm</en></v>
<v><i>alcaliniser</i><t>aim:er</t><en>alkalize</en></v>
<v><i>alcaliser</i><t>aim:er</t><en>alkalize</en></v>
<v><i>alcooliser</i><t>aim:er</t><en>alcooliser</en></v>
<v><i>alentir</i><t>fin:ir</t><en>alentir</en></v>
<v><i>alerter</i><t>aim:er</t><en>alert</en></v>
<v><i>aléser</i><t>l:éser</t><en>boring</en></v>
<v><i>aleviner</i><t>aim:er</t><en>aleviner</en></v>
<v><i>aliéner</i><t>ali:éner</t><en>alienate</en></v>
<v><i>aligner</i><t>aim:er</t><en>align</en></v>
<v><i>alimenter</i><t>aim:er</t><en>feed</en></v>
<v><i>aliter</i><t>aim:er</t><en>aliter</en></v>
<v><i>allaiter</i><t>aim:er</t><en>nurse</en></v>
<v><i>allécher</i><t>s:écher</t><en>entice</en></v>
<v><i>alléger</i><t>abr:éger</t><en>alleviate</en></v>
<v><i>allégir</i><t>fin:ir</t><en>allégir</en></v>
<v><i>allégoriser</i><t>aim:er</t><en>allegorize</en></v>
<v><i>alléguer</i><t>l:éguer</t><en>allege</en></v>
<v><i>aller</i><t>:aller</t><en>go</en></v>
<v><i>allier</i><t>aim:er</t><en>mix</en></v>
<v><i>allonger</i><t>man:ger</t><en>lengthen</en></v>
<v><i>allotir</i><t>fin:ir</t><en>allotir</en></v>
<v><i>allouer</i><t>aim:er</t><en>allocate</en></v>
<v><i>allumer</i><t>aim:er</t><en>turn on</en></v>
<v><i>alluvionner</i><t>aim:er</t><en>silt up</en></v>
<v><i>alourdir</i><t>fin:ir</t><en>heavier</en></v>
<v><i>alpaguer</i><t>aim:er</t><en>alpaguer</en></v>
<v><i>alphabétiser</i><t>aim:er</t><en>literacy</en></v>
<v><i>altérer</i><t>réf:érer</t><en>alter</en></v>
<v><i>alterner</i><t>aim:er</t><en>alternate</en></v>
<v><i>aluminer</i><t>aim:er</t><en>aluminized</en></v>
<v><i>aluner</i><t>aim:er</t><en>aluner</en></v>
<v><i>alunir</i><t>fin:ir</t><en>land on the moon</en></v>
<v><i>amadouer</i><t>aim:er</t><en>coax</en></v>
<v><i>amaigrir</i><t>fin:ir</t><en>thin</en></v>
<v><i>amalgamer</i><t>aim:er</t><en>amalgamate</en></v>
<v><i>amancher</i><t>aim:er</t><en>amancher</en></v>
<v><i>amariner</i><t>aim:er</t><en>to get one's sea legs</en></v>
<v><i>amarrer</i><t>aim:er</t><en>moor</en></v>
<v><i>amasser</i><t>aim:er</t><en>accumulate</en></v>
<v><i>amatir</i><t>fin:ir</t><en>amatir</en></v>
<v><i>ambiancer</i><t>pla:cer</t><en>ambiancer</en></v>
<v><i>ambitionner</i><t>aim:er</t><en>aspire</en></v>
<v><i>ambler</i><t>aim:er</t><en>amble</en></v>
<v><i>ambrer</i><t>aim:er</t><en>ambrer</en></v>
<v><i>améliorer</i><t>aim:er</t><en>improve</en></v>
<v><i>aménager</i><t>man:ger</t><en>develop</en></v>
<v><i>amender</i><t>aim:er</t><en>amend</en></v>
<v><i>amener</i><t>m:ener</t><en>bring</en></v>
<v><i>amenuiser</i><t>aim:er</t><en>diminish</en></v>
<v><i>américaniser</i><t>aim:er</t><en>Americanize</en></v>
<v><i>amerrir</i><t>fin:ir</t><en>ditch</en></v>
<v><i>ameublir</i><t>fin:ir</t><en>loosen</en></v>
<v><i>ameuter</i><t>aim:er</t><en>stir</en></v>
<v><i>amidonner</i><t>aim:er</t><en>starch</en></v>
<v><i>amincir</i><t>fin:ir</t><en>thin</en></v>
<v><i>amnistier</i><t>aim:er</t><en>amnesty</en></v>
<v><i>amocher</i><t>aim:er</t><en>amocher</en></v>
<v><i>amodier</i><t>aim:er</t><en>amodier</en></v>
<v><i>amoindrir</i><t>fin:ir</t><en>lessen</en></v>
<v><i>amollir</i><t>fin:ir</t><en>soften</en></v>
<v><i>amonceler</i><t>app:eler</t><en>pile</en></v>
<v><i>amorcer</i><t>pla:cer</t><en>initiate</en></v>
<v><i>amordancer</i><t>pla:cer</t><en>amordancer</en></v>
<v><i>amortir</i><t>fin:ir</t><en>cushion</en></v>
<v><i>amouracher</i><t>aim:er</t><en>amouracher</en></v>
<v><i>amplifier</i><t>aim:er</t><en>amplify</en></v>
<v><i>amputer</i><t>aim:er</t><en>amputate</en></v>
<v><i>amuïr</i><t>amu:ïr</t><en>become mute</en></v>
<v><i>amurer</i><t>aim:er</t><en>amurer</en></v>
<v><i>amuser</i><t>aim:er</t><en>entertain</en></v>
<v><i>analgésier</i><t>aim:er</t><en>analgésier</en></v>
<v><i>analyser</i><t>aim:er</t><en>analyze</en></v>
<v><i>anastomoser</i><t>aim:er</t><en>anastomose</en></v>
<v><i>anathématiser</i><t>aim:er</t><en>anathematize</en></v>
<v><i>anatomiser</i><t>aim:er</t><en>anatomize</en></v>
<v><i>ancrer</i><t>aim:er</t><en>anchor</en></v>
<v><i>anéantir</i><t>fin:ir</t><en>annihilate</en></v>
<v><i>anémier</i><t>aim:er</t><en>anemic</en></v>
<v><i>anesthésier</i><t>aim:er</t><en>anesthetize</en></v>
<v><i>anglaiser</i><t>aim:er</t><en>anglaiser</en></v>
<v><i>angliciser</i><t>aim:er</t><en>Anglicize</en></v>
<v><i>angoisser</i><t>aim:er</t><en>anxious</en></v>
<v><i>anhéler</i><t>rév:éler</t><en>anhéler</en></v>
<v><i>animaliser</i><t>aim:er</t><en>animalize</en></v>
<v><i>animer</i><t>aim:er</t><en>animate</en></v>
<v><i>aniser</i><t>aim:er</t><en>aniser</en></v>
<v><i>ankyloser</i><t>aim:er</t><en>ankyloser</en></v>
<v><i>anneler</i><t>app:eler</t><en>annealing</en></v>
<v><i>annexer</i><t>aim:er</t><en>annex</en></v>
<v><i>annihiler</i><t>aim:er</t><en>annihilate</en></v>
<v><i>annoncer</i><t>pla:cer</t><en>announce</en></v>
<v><i>annoter</i><t>aim:er</t><en>annotate</en></v>
<v><i>annualiser</i><t>aim:er</t><en>annualize</en></v>
<v><i>annuler</i><t>aim:er</t><en>cancel</en></v>
<v><i>anoblir</i><t>fin:ir</t><en>ennoble</en></v>
<v><i>anodiser</i><t>aim:er</t><en>anodizing</en></v>
<v><i>ânonner</i><t>aim:er</t><en>mumble</en></v>
<v><i>anordir</i><t>fin:ir</t><en>anordir</en></v>
<v><i>antéposer</i><t>aim:er</t><en>antéposer</en></v>
<v><i>anticiper</i><t>aim:er</t><en>anticipate</en></v>
<v><i>anticommuter</i><t>aim:er</t><en>anticommuter</en></v>
<v><i>antidater</i><t>aim:er</t><en>antedate</en></v>
<v><i>antiparasiter</i><t>aim:er</t><en>suppressors</en></v>
<v><i>antiquer</i><t>aim:er</t><en>antiquer</en></v>
<v><i>aoûter</i><t>aim:er</t><en>harden</en></v>
<v><i>apaiser</i><t>aim:er</t><en>appease</en></v>
<v><i>apanager</i><t>man:ger</t><en>apanager</en></v>
<v><i>apercevoir</i><t>dé:cevoir</t><en>see</en></v>
<v><i>apeurer</i><t>aim:er</t><en>scare</en></v>
<v><i>apiquer</i><t>aim:er</t><en>apiquer</en></v>
<v><i>apitoyer</i><t>netto:yer</t><en>sorry</en></v>
<v><i>aplanir</i><t>fin:ir</t><en>flatten</en></v>
<v><i>aplatir</i><t>fin:ir</t><en>flatten</en></v>
<v><i>apostasier</i><t>aim:er</t><en>apostatize</en></v>
<v><i>aposter</i><t>aim:er</t><en>aposter</en></v>
<v><i>apostiller</i><t>aim:er</t><en>apostille</en></v>
<v><i>apostropher</i><t>aim:er</t><en>apostrophize</en></v>
<v><i>appairer</i><t>aim:er</t><en>pair</en></v>
<v><i>apparaître</i><t>rep:aître</t><en>appear</en></v>
<v><i>appareiller</i><t>aim:er</t><en>pair</en></v>
<v><i>apparenter</i><t>aim:er</t><en>resemble</en></v>
<v><i>apparier</i><t>aim:er</t><en>pair</en></v>
<v><i>apparoir</i><t>app:aroir</t><en>prove</en></v>
<v><i>appartenir</i><t>t:enir</t><en>belong</en></v>
<v><i>appâter</i><t>aim:er</t><en>bait</en></v>
<v><i>appauvrir</i><t>fin:ir</t><en>impoverish</en></v>
<v><i>appeler</i><t>app:eler</t><en>call</en></v>
<v><i>appendre</i><t>ten:dre</t><en>appendre</en></v>
<v><i>appesantir</i><t>fin:ir</t><en>dwell</en></v>
<v><i>applaudir</i><t>fin:ir</t><en>cheer</en></v>
<v><i>appliquer</i><t>aim:er</t><en>apply</en></v>
<v><i>appointer</i><t>aim:er</t><en>appointer</en></v>
<v><i>appointir</i><t>fin:ir</t><en>appointir</en></v>
<v><i>appondre</i><t>ten:dre</t><en>Stitch</en></v>
<v><i>apponter</i><t>aim:er</t><en>put down</en></v>
<v><i>apporter</i><t>aim:er</t><en>bring</en></v>
<v><i>apposer</i><t>aim:er</t><en>affix</en></v>
<v><i>apprécier</i><t>aim:er</t><en>appreciate</en></v>
<v><i>appréhender</i><t>aim:er</t><en>apprehend</en></v>
<v><i>apprendre</i><t>pr:endre</t><en>learn</en></v>
<v><i>apprêter</i><t>aim:er</t><en>ready</en></v>
<v><i>apprivoiser</i><t>aim:er</t><en>tame</en></v>
<v><i>approcher</i><t>aim:er</t><en>approach</en></v>
<v><i>approfondir</i><t>fin:ir</t><en>deepen</en></v>
<v><i>approprier</i><t>aim:er</t><en>appropriate</en></v>
<v><i>approuver</i><t>aim:er</t><en>approve</en></v>
<v><i>approvisionner</i><t>aim:er</t><en>provision</en></v>
<v><i>approximer</i><t>aim:er</t><en>approximate</en></v>
<v><i>appuyer</i><t>netto:yer</t><en>support</en></v>
<v><i>apurer</i><t>aim:er</t><en>audit</en></v>
<v><i>arabiser</i><t>aim:er</t><en>Arabize</en></v>
<v><i>araser</i><t>aim:er</t><en>Screed</en></v>
<v><i>arbitrer</i><t>aim:er</t><en>arbitrate</en></v>
<v><i>arborer</i><t>aim:er</t><en>sport</en></v>
<v><i>arboriser</i><t>aim:er</t><en>arboriser</en></v>
<v><i>arc-bouter</i><t>aim:er</t><en>buttress</en></v>
<v><i>archaïser</i><t>aim:er</t><en>archaize</en></v>
<v><i>architecturer</i><t>aim:er</t><en>architecting</en></v>
<v><i>archiver</i><t>aim:er</t><en>archive</en></v>
<v><i>arçonner</i><t>aim:er</t><en>arçonner</en></v>
<v><i>ardoiser</i><t>aim:er</t><en>ardoiser</en></v>
<v><i>argenter</i><t>aim:er</t><en>silver</en></v>
<v><i>arguer</i><t>aim:er</t><en>argue</en></v>
<v><i>argumenter</i><t>aim:er</t><en>argue</en></v>
<v><i>ariser</i><t>aim:er</t><en>rippling</en></v>
<v><i>armer</i><t>aim:er</t><en>arm</en></v>
<v><i>armorier</i><t>aim:er</t><en>armorier</en></v>
<v><i>arnaquer</i><t>aim:er</t><en>rip off</en></v>
<v><i>aromatiser</i><t>aim:er</t><en>flavor</en></v>
<v><i>arpéger</i><t>abr:éger</t><en>arpeggiate</en></v>
<v><i>arpenter</i><t>aim:er</t><en>survey</en></v>
<v><i>arquer</i><t>aim:er</t><en>arch</en></v>
<v><i>arracher</i><t>aim:er</t><en>snatch</en></v>
<v><i>arraisonner</i><t>aim:er</t><en>boarding</en></v>
<v><i>arranger</i><t>man:ger</t><en>arrange</en></v>
<v><i>arrenter</i><t>aim:er</t><en>arrenter</en></v>
<v><i>arrérager</i><t>man:ger</t><en>arrérager</en></v>
<v><i>arrêter</i><t>aim:er</t><en>stop</en></v>
<v><i>arriérer</i><t>réf:érer</t><en>arrear</en></v>
<v><i>arrimer</i><t>aim:er</t><en>stow</en></v>
<v><i>arriser</i><t>aim:er</t><en>reefing</en></v>
<v><i>arriver</i><t>aim:er</t><en>arrive</en></v>
<v><i>arroger</i><t>man:ger</t><en>assume</en></v>
<v><i>arrondir</i><t>fin:ir</t><en>round</en></v>
<v><i>arroser</i><t>aim:er</t><en>water</en></v>
<v><i>articuler</i><t>aim:er</t><en>articulate</en></v>
<v><i>ascensionner</i><t>aim:er</t><en>ascend</en></v>
<v><i>aseptiser</i><t>aim:er</t><en>sanitize</en></v>
<v><i>aspecter</i><t>aim:er</t><en>aspecter</en></v>
<v><i>asperger</i><t>man:ger</t><en>spray</en></v>
<v><i>asphalter</i><t>aim:er</t><en>asphalt</en></v>
<v><i>asphyxier</i><t>aim:er</t><en>asphyxiate</en></v>
<v><i>aspirer</i><t>aim:er</t><en>aspire</en></v>
<v><i>assagir</i><t>fin:ir</t><en>chasten</en></v>
<v><i>assaillir</i><t>assaill:ir</t><en>assail</en></v>
<v><i>assainir</i><t>fin:ir</t><en>sanitize</en></v>
<v><i>assaisonner</i><t>aim:er</t><en>season</en></v>
<v><i>assarmenter</i><t>aim:er</t><en>assarmenter</en></v>
<v><i>assassiner</i><t>aim:er</t><en>murder</en></v>
<v><i>assécher</i><t>s:écher</t><en>drain</en></v>
<v><i>assembler</i><t>aim:er</t><en>assemble</en></v>
<v><i>asséner</i><t>ali:éner</t><en>Klitschko</en></v>
<v><i>assener</i><t>m:ener</t><en>thump</en></v>
<v><i>asseoir</i><t>ass:eoir</t><en>seat</en></v>
<v><i>assermenter</i><t>aim:er</t><en>swear</en></v>
<v><i>asservir</i><t>fin:ir</t><en>enslave</en></v>
<v><i>assibiler</i><t>aim:er</t><en>assibiler</en></v>
<v><i>assiéger</i><t>abr:éger</t><en>besiege</en></v>
<v><i>assigner</i><t>aim:er</t><en>assign</en></v>
<v><i>assimiler</i><t>aim:er</t><en>assimilate</en></v>
<v><i>assister</i><t>aim:er</t><en>assist</en></v>
<v><i>associer</i><t>aim:er</t><en>associate</en></v>
<v><i>assoiffer</i><t>aim:er</t><en>thirsty</en></v>
<v><i>assoir</i><t>ass:oir</t><en>sit</en></v>
<v><i>assoler</i><t>aim:er</t><en>assoler</en></v>
<v><i>assombrir</i><t>fin:ir</t><en>darken</en></v>
<v><i>assommer</i><t>aim:er</t><en>knock</en></v>
<v><i>assoner</i><t>aim:er</t><en>assoner</en></v>
<v><i>assortir</i><t>fin:ir</t><en>match</en></v>
<v><i>assoupir</i><t>fin:ir</t><en>asleep</en></v>
<v><i>assouplir</i><t>fin:ir</t><en>relax</en></v>
<v><i>assourdir</i><t>fin:ir</t><en>mute</en></v>
<v><i>assouvir</i><t>fin:ir</t><en>quench</en></v>
<v><i>assujettir</i><t>fin:ir</t><en>subject</en></v>
<v><i>assumer</i><t>aim:er</t><en>assume</en></v>
<v><i>assurer</i><t>aim:er</t><en>ensure</en></v>
<v><i>asticoter</i><t>aim:er</t><en>tease</en></v>
<v><i>astiquer</i><t>aim:er</t><en>polish</en></v>
<v><i>astreindre</i><t>crai:ndre</t><en>compel</en></v>
<v><i>atermoyer</i><t>netto:yer</t><en>temporize</en></v>
<v><i>atomiser</i><t>aim:er</t><en>atomize</en></v>
<v><i>atrophier</i><t>aim:er</t><en>atrophy</en></v>
<v><i>attabler</i><t>aim:er</t><en>dine</en></v>
<v><i>attacher</i><t>aim:er</t><en>attach</en></v>
<v><i>attaquer</i><t>aim:er</t><en>attack</en></v>
<v><i>attarder</i><t>aim:er</t><en>linger</en></v>
<v><i>atteindre</i><t>crai:ndre</t><en>achieve</en></v>
<v><i>atteler</i><t>app:eler</t><en>harness</en></v>
<v><i>attendre</i><t>ten:dre</t><en>expect</en></v>
<v><i>attendrir</i><t>fin:ir</t><en>tender</en></v>
<v><i>attenter</i><t>aim:er</t><en>attempt</en></v>
<v><i>atténuer</i><t>aim:er</t><en>mitigate</en></v>
<v><i>atterrer</i><t>aim:er</t><en>stagger</en></v>
<v><i>atterrir</i><t>fin:ir</t><en>touch down</en></v>
<v><i>attester</i><t>aim:er</t><en>attest</en></v>
<v><i>attiédir</i><t>fin:ir</t><en>lukewarm</en></v>
<v><i>attifer</i><t>aim:er</t><en>attifer</en></v>
<v><i>attiger</i><t>man:ger</t><en>Attiger</en></v>
<v><i>attirer</i><t>aim:er</t><en>attract</en></v>
<v><i>attiser</i><t>aim:er</t><en>stir</en></v>
<v><i>attitrer</i><t>aim:er</t><en>attitrer</en></v>
<v><i>attraire</i><t>extra:ire</t><en>sue</en></v>
<v><i>attraper</i><t>aim:er</t><en>catch</en></v>
<v><i>attribuer</i><t>aim:er</t><en>assign</en></v>
<v><i>attriquer</i><t>aim:er</t><en>attriquer</en></v>
<v><i>attrister</i><t>aim:er</t><en>sadden</en></v>
<v><i>attrouper</i><t>aim:er</t><en>attrouper</en></v>
<v><i>auditer</i><t>aim:er</t><en>audit</en></v>
<v><i>auditionner</i><t>aim:er</t><en>audition</en></v>
<v><i>augmenter</i><t>aim:er</t><en>increase</en></v>
<v><i>augurer</i><t>aim:er</t><en>bode</en></v>
<v><i>auréoler</i><t>aim:er</t><en>glorify</en></v>
<v><i>aurifier</i><t>aim:er</t><en>aurifier</en></v>
<v><i>ausculter</i><t>aim:er</t><en>listen</en></v>
<v><i>authentifier</i><t>aim:er</t><en>authenticate</en></v>
<v><i>authentiquer</i><t>aim:er</t><en>authenticate</en></v>
<v><i>autocensurer</i><t>aim:er</t><en>censor</en></v>
<v><i>autodétruire</i><t>condui:re</t><en>self-destruct</en></v>
<v><i>autodissoudre</i><t>disso:udre</t><en>dissolve itself</en></v>
<v><i>autofinancer</i><t>pla:cer</t><en>self-financing</en></v>
<v><i>autographier</i><t>aim:er</t><en>autograph</en></v>
<v><i>automatiser</i><t>aim:er</t><en>automate</en></v>
<v><i>autoproclamer</i><t>aim:er</t><en>proclaim</en></v>
<v><i>autopsier</i><t>aim:er</t><en>autopsy</en></v>
<v><i>autoriser</i><t>aim:er</t><en>allow</en></v>
<v><i>avachir</i><t>fin:ir</t><en>slouching</en></v>
<v><i>avaler</i><t>aim:er</t><en>swallow</en></v>
<v><i>avaliser</i><t>aim:er</t><en>endorse</en></v>
<v><i>avancer</i><t>pla:cer</t><en>advance</en></v>
<v><i>avantager</i><t>man:ger</t><en>advantage</en></v>
<v><i>avarier</i><t>aim:er</t><en>spoil</en></v>
<v><i>aventurer</i><t>aim:er</t><en>adventure</en></v>
<v><i>avérer</i><t>réf:érer</t><en>be</en></v>
<v><i>avertir</i><t>fin:ir</t><en>warn</en></v>
<v><i>aveugler</i><t>aim:er</t><en>blind</en></v>
<v><i>aveulir</i><t>fin:ir</t><en>aveulir</en></v>
<v><i>avilir</i><t>fin:ir</t><en>degrade</en></v>
<v><i>aviner</i><t>aim:er</t><en>Aviner</en></v>
<v><i>aviser</i><t>aim:er</t><en>notice</en></v>
<v><i>avitailler</i><t>aim:er</t><en>refuel</en></v>
<v><i>aviver</i><t>aim:er</t><en>heighten</en></v>
<v><i>avoir</i><t>:avoir</t><en>have</en></v>
<v><i>avoisiner</i><t>aim:er</t><en>be around</en></v>
<v><i>avorter</i><t>aim:er</t><en>abort</en></v>
<v><i>avouer</i><t>aim:er</t><en>admit</en></v>
<v><i>axer</i><t>aim:er</t><en>focus</en></v>
<v><i>axiomatiser</i><t>aim:er</t><en>axiomatize</en></v>
<v><i>azorer</i><t>aim:er</t><en>azorer</en></v>
<v><i>azurer</i><t>aim:er</t><en>brightened</en></v>
<v><i>babiller</i><t>aim:er</t><en>babble</en></v>
<v><i>baboler</i><t>aim:er</t><en>baboler</en></v>
<v><i>bâcher</i><t>aim:er</t><en>bâcher</en></v>
<v><i>bachoter</i><t>aim:er</t><en>cram</en></v>
<v><i>bâcler</i><t>aim:er</t><en>scamp</en></v>
<v><i>badauder</i><t>aim:er</t><en>gawk</en></v>
<v><i>bader</i><t>aim:er</t><en>bader</en></v>
<v><i>badger</i><t>man:ger</t><en>badger</en></v>
<v><i>badigeonner</i><t>aim:er</t><en>Brush</en></v>
<v><i>badiner</i><t>aim:er</t><en>banter</en></v>
<v><i>baffer</i><t>aim:er</t><en>slap</en></v>
<v><i>bafouer</i><t>aim:er</t><en>trample</en></v>
<v><i>bafouiller</i><t>aim:er</t><en>sputter</en></v>
<v><i>bâfrer</i><t>aim:er</t><en>gobble</en></v>
<v><i>bagarrer</i><t>aim:er</t><en>brawl</en></v>
<v><i>baguenauder</i><t>aim:er</t><en>stroll</en></v>
<v><i>baguer</i><t>aim:er</t><en>banding</en></v>
<v><i>baigner</i><t>aim:er</t><en>bathe</en></v>
<v><i>bailler</i><t>aim:er</t><en>yawn</en></v>
<v><i>bâiller</i><t>aim:er</t><en>yawn</en></v>
<v><i>bâillonner</i><t>aim:er</t><en>gag</en></v>
<v><i>baiser</i><t>aim:er</t><en>kiss (old-fashioned); to outdo, to be had; to have sex (vulgar slang)</en></v>
<v><i>baisoter</i><t>aim:er</t><en>baisoter</en></v>
<v><i>baisser</i><t>aim:er</t><en>lower</en></v>
<v><i>balader</i><t>aim:er</t><en>stroll</en></v>
<v><i>balafrer</i><t>aim:er</t><en>slash</en></v>
<v><i>balancer</i><t>pla:cer</t><en>swing</en></v>
<v><i>balayer</i><t>pa:yer</t><en>sweep</en></v>
<v><i>balbutier</i><t>aim:er</t><en>stammer</en></v>
<v><i>baleiner</i><t>aim:er</t><en>baleiner</en></v>
<v><i>baliser</i><t>aim:er</t><en>mark</en></v>
<v><i>balkaniser</i><t>aim:er</t><en>balkanize</en></v>
<v><i>ballaster</i><t>aim:er</t><en>ballast</en></v>
<v><i>baller</i><t>aim:er</t><en>baller</en></v>