<?xml version='1.0' encoding='utf-8'?>
<!--
	conjugation-pt.xml - List of Portuguese conjugation templates.
	The templates were generated by Sekou Diao using Unsupervised Learning,
	and follow the xml schema defined by Pierre Sarrazin in conjug_manager.
	Further improved by Brett Tolbert:
	- Removed uncessary compound tenses, as they can be conjugated with 
	  only the helping verb and participle. 
	- Improved DTD, made number of p elements strict, fixed some tenses
	  with incorrect number of p elements
	- Removed mood name from tense names to eliminate redundancy
	- Converted tense tag names to lowercase for ease of use
	- Fixed issues with Portuguese verbs like andar, ficar, amar, odiar, arguir

	Coypright (C) 2023 Brett Tolbert <https://github.com/bretttolbert/verbecc>
	Copyright (C) 2018 Sekou Diao <https://github.com/SekouD>
	Copyright (C) 2003-2016 Pierre Sarrazin <http://sarrazip.com/>

	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with this program; if not, write to the Free Software
	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
	02110-1301, USA.
-->
<!DOCTYPE conjugation-pt [
<!ELEMENT conjugation-pt (template)+>
<!ATTLIST conjugation-pt xmlns CDATA #FIXED "">
<!ELEMENT template (Indicativo , Condicional , Subjuntivo , Infinitivo , Imperativo , Gerúndio , Particípio)>
<!ATTLIST template xmlns CDATA #FIXED "">
<!ATTLIST template name NMTOKEN #REQUIRED>
<!ELEMENT Indicativo (presente , pretérito-imperfeito , pretérito-mais-que-perfeito , pretérito-perfeito , futuro-do-presente)>
<!ELEMENT Condicional (futuro-do-pretérito)>
<!ELEMENT Subjuntivo (presente , pretérito-imperfeito , futuro)>
<!ELEMENT Infinitivo (infinitivo-pessoal-presente , infinitivo)>
<!ELEMENT Imperativo (afirmativo , negativo)>
<!ELEMENT Gerúndio (gerúndio)>
<!ELEMENT Particípio (particípio)>
<!ELEMENT presente (p , p , p , p , p , p)>
<!ELEMENT pretérito-imperfeito (p , p , p , p , p , p)>
<!ELEMENT pretérito-mais-que-perfeito (p , p , p , p , p , p)>
<!ELEMENT pretérito-perfeito (p , p , p , p , p , p)>
<!ELEMENT futuro-do-presente (p , p , p , p , p , p)>
<!ELEMENT futuro-do-pretérito (p , p , p , p , p , p)>
<!ELEMENT futuro (p , p , p , p , p , p)>
<!ELEMENT infinitivo-pessoal-presente (p , p , p , p , p , p)>
<!ELEMENT infinitivo (p , p)>
<!ELEMENT afirmativo (p , p , p , p , p , p)>
<!ELEMENT negativo (p , p , p , p , p , p)>
<!ELEMENT gerúndio (p , p)>
<!ELEMENT particípio (p)>
<!ELEMENT p (i)>
<!ELEMENT i (#PCDATA)>
]>
<conjugation-pt>

<template name="aque:cer">
	<Indicativo>
		<presente>
			<p><i>ço</i></p>
			<p><i>ces</i></p>
			<p><i>ce</i></p>
			<p><i>cemos</i></p>
			<p><i>ceis</i></p>
			<p><i>cem</i></p>
		</presente>
		<pretérito-imperfeito>
			<p><i>cia</i></p>
			<p><i>cias</i></p>
			<p><i>cia</i></p>
			<p><i>cíamos</i></p>
			<p><i>cíeis</i></p>
			<p><i>ciam</i></p>
		</pretérito-imperfeito>
		<pretérito-mais-que-perfeito>
			<p><i>cera</i></p>
			<p><i>ceras</i></p>
			<p><i>cera</i></p>
			<p><i>cêramos</i></p>
			<p><i>cêreis</i></p>
			<p><i>ceram</i></p>
		</pretérito-mais-que-perfeito>
		<pretérito-perfeito>
			<p><i>ci</i></p>
			<p><i>ceste</i></p>
			<p><i>ceu</i></p>
			<p><i>cemos</i></p>
			<p><i>cestes</i></p>
			<p><i>ceram</i></p>
		</pretérito-perfeito>
		<futuro-do-presente>
			<p><i>cerei</i></p>
			<p><i>cerás</i></p>
			<p><i>cerá</i></p>
			<p><i>ceremos</i></p>
			<p><i>cereis</i></p>
			<p><i>cerão</i></p>
		</futuro-do-presente>
		</Indicativo>
	<Condicional>
		<futuro-do-pretérito>
			<p><i>ceria</i></p>
			<p><i>cerias</i></p>
			<p><i>ceria</i></p>
			<p><i>ceríamos</i></p>
			<p><i>ceríeis</i></p>
			<p><i>ceriam</i></p>
		</futuro-do-pretérito>
		</Condicional>
	<Subjuntivo>
		<presente>
			<p><i>ça</i></p>
			<p><i>ças</i></p>
			<p><i>ça</i></p>
			<p><i>çamos</i></p>
			<p><i>çais</i></p>
			<p><i>çam</i></p>
		</presente>
		<pretérito-imperfeito>
			<p><i>cesse</i></p>
			<p><i>cesses</i></p>
			<p><i>cesse</i></p>
			<p><i>cêssemos</i></p>
			<p><i>cêsseis</i></p>
			<p><i>cessem</i></p>
		</pretérito-imperfeito>
		<futuro>
			<p><i>cer</i></p>
			<p><i>ceres</i></p>
			<p><i>cer</i></p>
			<p><i>cermos</i></p>
			<p><i>cerdes</i></p>
			<p><i>cerem</i></p>
		</futuro>
		</Subjuntivo>
	<Infinitivo>
		<infinitivo-pessoal-presente>
			<p><i>cer</i></p>
			<p><i>ceres</i></p>
			<p><i>cer</i></p>
			<p><i>cermos</i></p>
			<p><i>cerdes</i></p>
			<p><i>cerem</i></p>
		</infinitivo-pessoal-presente>
		<infinitivo>
			<p><i>cer</i></p>
			<p><i>cido</i></p>
		</infinitivo>
	</Infinitivo>
	<Imperativo>
		<afirmativo>
			<p><i>-</i></p>
			<p><i>ce</i></p>
			<p><i>ça</i></p>
			<p><i>çamos</i></p>
			<p><i>cei</i></p>
			<p><i>çam</i></p>
		</afirmativo>
		<negativo>
			<p><i>-</i></p>
			<p><i>ças</i></p>
			<p><i>ça</i></p>
			<p><i>çamos</i></p>
			<p><i>çais</i></p>
			<p><i>çam</i></p>
		</negativo>
	</Imperativo>
	<Gerúndio>
		<gerúndio>
			<p><i>cendo</i></p>
			<p><i>cido</i></p>
		</gerúndio>
	</Gerúndio>
	<Particípio>
		<particípio>
			<p><i>cido</i></p>
		</particípio>
	</Particípio>
</template>

<template name="ac:udir">
	<Indicativo>
		<presente>
			<p><i>udo</i></p>
			<p><i>odes</i></p>
			<p><i>ode</i></p>
			<p><i>udimos</i></p>
			<p><i>udis</i></p>
			<p><i>odem</i></p>
		</presente>
		<pretérito-imperfeito>
			<p><i>udia</i></p>
			<p><i>udias</i></p>
			<p><i>udia</i></p>
			<p><i>udíamos</i></p>
			<p><i>udíeis</i></p>
			<p><i>udiam</i></p>
		</pretérito-imperfeito>
		<pretérito-mais-que-perfeito>
			<p><i>udira</i></p>
			<p><i>udiras</i></p>
			<p><i>udira</i></p>
			<p><i>udíramos</i></p>
			<p><i>udíreis</i></p>
			<p><i>udiram</i></p>
		</pretérito-mais-que-perfeito>
		<pretérito-perfeito>
			<p><i>udi</i></p>
			<p><i>udiste</i></p>
			<p><i>udiu</i></p>
			<p><i>udimos</i></p>
			<p><i>udistes</i></p>
			<p><i>udiram</i></p>
		</pretérito-perfeito>
		<futuro-do-presente>
			<p><i>udirei</i></p>
			<p><i>udirás</i></p>
			<p><i>udirá</i></p>
			<p><i>udiremos</i></p>
			<p><i>udireis</i></p>
			<p><i>udirão</i></p>
		</futuro-do-presente>
		</Indicativo>
	<Condicional>
		<futuro-do-pretérito>
			<p><i>udiria</i></p>
			<p><i>udirias</i></p>
			<p><i>udiria</i></p>
			<p><i>udiríamos</i></p>
			<p><i>udiríeis</i></p>
			<p><i>udiriam</i></p>
		</futuro-do-pretérito>
		</Condicional>
	<Subjuntivo>
		<presente>
			<p><i>uda</i></p>
			<p><i>udas</i></p>
			<p><i>uda</i></p>
			<p><i>udamos</i></p>
			<p><i>udais</i></p>
			<p><i>udam</i></p>
		</presente>
		<pretérito-imperfeito>
			<p><i>udisse</i></p>
			<p><i>udisses</i></p>
			<p><i>udisse</i></p>
			<p><i>udíssemos</i></p>
			<p><i>udísseis</i></p>
			<p><i>udissem</i></p>
		</pretérito-imperfeito>
		<futuro>
			<p><i>udir</i></p>
			<p><i>udires</i></p>
			<p><i>udir</i></p>
			<p><i>udirmos</i></p>
			<p><i>udirdes</i></p>
			<p><i>udirem</i></p>
		</futuro>
		</Subjuntivo>
	<Infinitivo>
		<infinitivo-pessoal-presente>
			<p><i>udir</i></p>
			<p><i>udires</i></p>
			<p><i>udir</i></p>
			<p><i>udirmos</i></p>
			<p><i>udirdes</i></p>
			<p><i>udirem</i></p>
		</infinitivo-pessoal-presente>
		<infinitivo>
			<p><i>udir</i></p>
			<p><i>udido</i></p>
		</infinitivo>
	</Infinitivo>
	<Imperativo>
		<afirmativo>
			<p><i>-</i></p>
			<p><i>ode</i></p>
			<p><i>uda</i></p>
			<p><i>udamos</i></p>
			<p><i>udi</i></p>
			<p><i>udam</i></p>
		</afirmativo>
		<negativo>
			<p><i>-</i></p>
			<p><i>udas</i></p>
			<p><i>uda</i></p>
			<p><i>udamos</i></p>
			<p><i>udais</i></p>
			<p><i>udam</i></p>
		</negativo>
	</Imperativo>
	<Gerúndio>
		<gerúndio>
			<p><i>udindo</i></p>
			<p><i>udido</i></p>
		</gerúndio>
	</Gerúndio>
	<Particípio>
		<particípio>
			<p><i>udido</i></p>
		</particípio>
	</Particípio>
</template>

<template name="adeq:uar">
	<Indicativo>
		<presente>
			<p><i>uo</i></p>
			<p><i>uas</i></p>
			<p><i>ua</i></p>
			<p><i>uamos</i></p>
			<p><i>uais</i></p>
			<p><i>uam</i></p>
		</presente>
		<pretérito-imperfeito>
			<p><i>uava</i></p>
			<p><i>uavas</i></p>
			<p><i>uava</i></p>
			<p><i>uávamos</i></p>
			<p><i>uáveis</i></p>
			<p><i>uavam</i></p>
		</pretérito-imperfeito>
		<pretérito-mais-que-perfeito>
			<p><i>uara</i></p>
			<p><i>uaras</i></p>
			<p><i>uara</i></p>
			<p><i>uáramos</i></p>
			<p><i>uáreis</i></p>
			<p><i>uaram</i></p>
		</pretérito-mais-que-perfeito>
		<pretérito-perfeito>
			<p><i>uei</i></p>
			<p><i>uaste</i></p>
			<p><i>uou</i></p>
			<p><i/></p>
			<p><i>uastes</i></p>
			<p><i>uaram</i></p>
		</pretérito-perfeito>
		<futuro-do-presente>
			<p><i>uarei</i></p>
			<p><i>uarás</i></p>
			<p><i>uará</i></p>
			<p><i>uaremos</i></p>
			<p><i>uareis</i></p>
			<p><i>uarão</i></p>
		</futuro-do-presente>
		</Indicativo>
	<Condicional>
		<futuro-do-pretérito>
			<p><i>uaria</i></p>
			<p><i>uarias</i></p>
			<p><i>uaria</i></p>
			<p><i>uaríamos</i></p>
			<p><i>uaríeis</i></p>
			<p><i>uariam</i></p>
		</futuro-do-pretérito>
		</Condicional>
	<Subjuntivo>
		<presente>
			<p><i>úe</i></p>
			<p><i>úes</i></p>
			<p><i>úe</i></p>
			<p><i>uemos</i></p>
			<p><i>ueis</i></p>
			<p><i>úem</i></p>
		</presente>
		<pretérito-imperfeito>
			<p><i>uasse</i></p>
			<p><i>uasses</i></p>
			<p><i>uasse</i></p>
			<p><i>uássemos</i></p>
			<p><i>uásseis</i></p>
			<p><i>uassem</i></p>
		</pretérito-imperfeito>
		<futuro>
			<p><i>uar</i></p>
			<p><i>uares</i></p>
			<p><i>uar</i></p>
			<p><i>uarmos</i></p>
			<p><i>uardes</i></p>
			<p><i>uarem</i></p>
		</futuro>
		</Subjuntivo>
	<Infinitivo>
		<infinitivo-pessoal-presente>
			<p><i>uar</i></p>
			<p><i>uares</i></p>
			<p><i>uar</i></p>
			<p><i>uarmos</i></p>
			<p><i>uardes</i></p>
			<p><i>uarem</i></p>
		</infinitivo-pessoal-presente>
		<infinitivo>
			<p><i>uar</i></p>
			<p><i>uado</i></p>
		</infinitivo>
	</Infinitivo>
	<Imperativo>
		<afirmativo>
			<p><i>-</i></p>
			<p><i>ua</i></p>
			<p><i>úe</i></p>
			<p><i>uemos</i></p>
			<p><i>uai</i></p>
			<p><i>úem</i></p>
		</afirmativo>
		<negativo>
			<p><i>-</i></p>
			<p><i>úes</i></p>
			<p><i>úe</i></p>
			<p><i>uemos</i></p>
			<p><i>ueis</i></p>
			<p><i>úem</i></p>
		</negativo>
	</Imperativo>
	<Gerúndio>
		<gerúndio>
			<p><i>uando</i></p>
			<p><i>uado</i></p>
		</gerúndio>
	</Gerúndio>
	<Particípio>
		<particípio>
			<p><i>uado</i></p>
		</particípio>
	</Particípio>
</template>

<template name="agr:edir">
	<Indicativo>
		<presente>
			<p><i>ido</i></p>
			<p><i>ides</i></p>
			<p><i>ide</i></p>
			<p><i>edimos</i></p>
			<p><i>edis</i></p>
			<p><i>idem</i></p>
		</presente>
		<pretérito-imperfeito>
			<p><i>edia</i></p>
			<p><i>edias</i></p>
			<p><i>edia</i></p>
			<p><i>edíamos</i></p>
			<p><i>edíeis</i></p>
			<p><i>ediam</i></p>
		</pretérito-imperfeito>
		<pretérito-mais-que-perfeito>
			<p><i>edira</i></p>
			<p><i>ediras</i></p>
			<p><i>edira</i></p>
			<p><i>edíramos</i></p>
			<p><i>edíreis</i></p>
			<p><i>ediram</i></p>
		</pretérito-mais-que-perfeito>
		<pretérito-perfeito>
			<p><i>edi</i></p>
			<p><i>ediste</i></p>
			<p><i>ediu</i></p>
			<p><i>edimos</i></p>
			<p><i>edistes</i></p>
			<p><i>ediram</i></p>
		</pretérito-perfeito>
		<futuro-do-presente>
			<p><i>edirei</i></p>
			<p><i>edirás</i></p>
			<p><i>edirá</i></p>
			<p><i>ediremos</i></p>
			<p><i>edireis</i></p>
			<p><i>edirão</i></p>
		</futuro-do-presente>
		</Indicativo>
	<Condicional>
		<futuro-do-pretérito>
			<p><i>ediria</i></p>
			<p><i>edirias</i></p>
			<p><i>ediria</i></p>
			<p><i>ediríamos</i></p>
			<p><i>ediríeis</i></p>
			<p><i>ediriam</i></p>
		</futuro-do-pretérito>
		</Condicional>
	<Subjuntivo>
		<presente>
			<p><i>ida</i></p>
			<p><i>idas</i></p>
			<p><i>ida</i></p>
			<p><i>idamos</i></p>
			<p><i>idais</i></p>
			<p><i>idam</i></p>
		</presente>
		<pretérito-imperfeito>
			<p><i>edisse</i></p>
			<p><i>edisses</i></p>
			<p><i>edisse</i></p>
			<p><i>edíssemos</i></p>
			<p><i>edísseis</i></p>
			<p><i>edissem</i></p>
		</pretérito-imperfeito>
		<futuro>
			<p><i>edir</i></p>
			<p><i>edires</i></p>
			<p><i>edir</i></p>
			<p><i>edirmos</i></p>
			<p><i>edirdes</i></p>
			<p><i>edirem</i></p>
		</futuro>
		</Subjuntivo>
	<Infinitivo>
		<infinitivo-pessoal-presente>
			<p><i>edir</i></p>
			<p><i>edires</i></p>
			<p><i>edir</i></p>
			<p><i>edirmos</i></p>
			<p><i>edirdes</i></p>
			<p><i>edirem</i></p>
		</infinitivo-pessoal-presente>
		<infinitivo>
			<p><i>edir</i></p>
			<p><i>edido</i></p>
		</infinitivo>
	</Infinitivo>
	<Imperativo>
		<afirmativo>
			<p><i>-</i></p>
			<p><i>ide</i></p>
			<p><i>ida</i></p>
			<p><i>idamos</i></p>
			<p><i>idi</i></p>
			<p><i>idam</i></p>
		</afirmativo>
		<negativo>
			<p><i>-</i></p>
			<p><i>idas</i></p>
			<p><i>ida</i></p>
			<p><i>idamos</i></p>
			<p><i>idais</i></p>
			<p><i>idam</i></p>
		</negativo>
	</Imperativo>
	<Gerúndio>
		<gerúndio>
			<p><i>edindo</i></p>
			<p><i>edido</i></p>
		</gerúndio>
	</Gerúndio>
	<Particípio>
		<particípio>
			<p><i>edido</i></p>
		</particípio>
	</Particípio>
</template>

<template name="compr:ar">
	<Indicativo>
		<presente>
			<p><i>o</i></p>
			<p><i>as</i></p>
			<p><i>a</i></p>
			<p><i>amos</i></p>
			<p><i>ais</i></p>
			<p><i>am</i></p>
		</presente>
		<pretérito-imperfeito>
			<p><i>ava</i></p>
			<p><i>avas</i></p>
			<p><i>ava</i></p>
			<p><i>ávamos</i></p>
			<p><i>áveis</i></p>
			<p><i>avam</i></p>
		</pretérito-imperfeito>
		<pretérito-mais-que-perfeito>
			<p><i>ara</i></p>
			<p><i>aras</i></p>
			<p><i>ara</i></p>
			<p><i>áramos</i></p>
			<p><i>áreis</i></p>
			<p><i>aram</i></p>
		</pretérito-mais-que-perfeito>
		<pretérito-perfeito>
			<p><i>ei</i></p>
			<p><i>aste</i></p>
			<p><i>ou</i></p>
			<p><i/></p>
			<p><i>astes</i></p>
			<p><i>aram</i></p>
		</pretérito-perfeito>
		<futuro-do-presente>
			<p><i>arei</i></p>
			<p><i>arás</i></p>
			<p><i>ará</i></p>
			<p><i>aremos</i></p>
			<p><i>areis</i></p>
			<p><i>arão</i></p>
		</futuro-do-presente>
		</Indicativo>
	<Condicional>
		<futuro-do-pretérito>
			<p><i>aria</i></p>
			<p><i>arias</i></p>
			<p><i>aria</i></p>
			<p><i>aríamos</i></p>
			<p><i>aríeis</i></p>
			<p><i>ariam</i></p>
		</futuro-do-pretérito>
		</Condicional>
	<Subjuntivo>
		<presente>
			<p><i>e</i></p>
			<p><i>es</i></p>
			<p><i>e</i></p>
			<p><i>emos</i></p>
			<p><i>eis</i></p>
			<p><i>em</i></p>
		</presente>
		<pretérito-imperfeito>
			<p><i>asse</i></p>
			<p><i>asses</i></p>
			<p><i>asse</i></p>
			<p><i>ássemos</i></p>
			<p><i>ásseis</i></p>
			<p><i>assem</i></p>
		</pretérito-imperfeito>
		<futuro>
			<p><i>ar</i></p>
			<p><i>ares</i></p>
			<p><i>ar</i></p>
			<p><i>armos</i></p>
			<p><i>ardes</i></p>
			<p><i>arem</i></p>
		</futuro>
		</Subjuntivo>
	<Infinitivo>
		<infinitivo-pessoal-presente>
			<p><i>ar</i></p>
			<p><i>ares</i></p>
			<p><i>ar</i></p>
			<p><i>armos</i></p>
			<p><i>ardes</i></p>
			<p><i>arem</i></p>
		</infinitivo-pessoal-presente>
		<infinitivo>
			<p><i>ar</i></p>
			<p><i>ado</i></p>
		</infinitivo>
	</Infinitivo>
	<Imperativo>
		<afirmativo>
			<p><i>-</i></p>
			<p><i>a</i></p>
			<p><i>e</i></p>
			<p><i>emos</i></p>
			<p><i>ai</i></p>
			<p><i>em</i></p>
		</afirmativo>
		<negativo>
			<p><i>-</i></p>
			<p><i>es</i></p>
			<p><i>e</i></p>
			<p><i>emos</i></p>
			<p><i>eis</i></p>
			<p><i>em</i></p>
		</negativo>
	</Imperativo>
	<Gerúndio>
		<gerúndio>
			<p><i>ando</i></p>
			<p><i>ado</i></p>
		</gerúndio>
	</Gerúndio>
	<Particípio>
		<particípio>
			<p><i>ado</i></p>
		</particípio>
	</Particípio>
</template>

<template name="pr:azer">
	<Indicativo>
		<presente>
			<p><i>azo</i></p>
			<p><i>azes</i></p>
			<p><i>az</i></p>
			<p><i>azemos</i></p>
			<p><i>azeis</i></p>
			<p><i>azem</i></p>
		</presente>
		<pretérito-imperfeito>
			<p><i>azia</i></p>
			<p><i>azias</i></p>
			<p><i>azia</i></p>
			<p><i>azíamos</i></p>
			<p><i>azíeis</i></p>
			<p><i>aziam</i></p>
		</pretérito-imperfeito>
		<pretérito-mais-que-perfeito>
			<p><i>ouvera</i></p>
			<p><i>ouveras</i></p>
			<p><i>ouvera</i></p>
			<p><i>ouvéramos</i></p>
			<p><i>ouvéreis</i></p>
			<p><i>ouveram</i></p>
		</pretérito-mais-que-perfeito>
		<pretérito-perfeito>
			<p><i>ouve</i></p>
			<p><i>ouveste</i></p>
			<p><i>ouve</i></p>
			<p><i>ouvemos</i></p>
			<p><i>ouvestes</i></p>
			<p><i>ouveram</i></p>
		</pretérito-perfeito>
		<futuro-do-presente>
			<p><i>azerei</i></p>
			<p><i>azerás</i></p>
			<p><i>azerá</i></p>
			<p><i>azeremos</i></p>
			<p><i>azereis</i></p>
			<p><i>azerão</i></p>
		</futuro-do-presente>
		</Indicativo>
	<Condicional>
		<futuro-do-pretérito>
			<p><i>azeria</i></p>
			<p><i>azerias</i></p>
			<p><i>azeria</i></p>
			<p><i>azeríamos</i></p>
			<p><i>azeríeis</i></p>
			<p><i>azeriam</i></p>
		</futuro-do-pretérito>
		</Condicional>
	<Subjuntivo>
		<presente>
			<p><i>aza</i></p>
			<p><i>azas</i></p>
			<p><i>aza</i></p>
			<p><i>azamos</i></p>
			<p><i>azais</i></p>
			<p><i>azam</i></p>
		</presente>
		<pretérito-imperfeito>
			<p><i>ouvesse</i></p>
			<p><i>ouvesses</i></p>
			<p><i>ouvesse</i></p>
			<p><i>ouvéssemos</i></p>
			<p><i>ouvésseis</i></p>
			<p><i>ouvessem</i></p>
		</pretérito-imperfeito>
		<futuro>
			<p><i>ouver</i></p>
			<p><i>ouveres</i></p>
			<p><i>ouver</i></p>
			<p><i>ouvermos</i></p>
			<p><i>ouverdes</i></p>
			<p><i>ouverem</i></p>
		</futuro>
		</Subjuntivo>
	<Infinitivo>
		<infinitivo-pessoal-presente>
			<p><i>azer</i></p>
			<p><i>azeres</i></p>
			<p><i>azer</i></p>
			<p><i>azermos</i></p>
			<p><i>azerdes</i></p>
			<p><i>azerem</i></p>
		</infinitivo-pessoal-presente>
		<infinitivo>
			<p><i>azer</i></p>
			<p><i>azido</i></p>
		</infinitivo>
	</Infinitivo>
	<Imperativo>
		<afirmativo>
			<p><i>-</i></p>
			<p><i>aze</i></p>
			<p><i>aza</i></p>
			<p><i>azamos</i></p>
			<p><i>azei</i></p>
			<p><i>azam</i></p>
		</afirmativo>
		<negativo>
			<p><i>-</i></p>
			<p><i>azas</i></p>
			<p><i>aza</i></p>
			<p><i>azamos</i></p>
			<p><i>azais</i></p>
			<p><i>azam</i></p>
		</negativo>
	</Imperativo>
	<Gerúndio>
		<gerúndio>
			<p><i>azendo</i></p>
			<p><i>azido</i></p>
		</gerúndio>
	</Gerúndio>
	<Particípio>
		<particípio>
			<p><i>azido</i></p>
		</particípio>
	</Particípio>
</template>

<template name="arg:uir">
	<Indicativo>
		<presente>
			<p><i>uo</i></p>
			<p><i>úis</i></p>
			<p><i>úi</i></p>
			<p><i>uimos</i></p>
			<p><i>uistes</i></p>
			<p><i>úem</i></p>
		</presente>
		<pretérito-imperfeito>
			<p><i>uia</i></p>
			<p><i>uas</i></p>
			<p><i>uia</i></p>
			<p><i>uíamos</i></p>
			<p><i>uíeis</i></p>
			<p><i>uiam</i></p>
		</pretérito-imperfeito>
		<pretérito-mais-que-perfeito>
			<p><i>uira</i></p>
			<p><i>uiras</i></p>
			<p><i>uira</i></p>
			<p><i>uíramos</i></p>
			<p><i>uíreis</i></p>
			<p><i>uiram</i></p>
		</pretérito-mais-que-perfeito>
		<pretérito-perfeito>
			<p><i>ui</i></p>
			<p><i>uiste</i></p>
			<p><i>uiu</i></p>
			<p><i>uimos</i></p>
			<p><i>uistes</i></p>
			<p><i>uiram</i></p>
		</pretérito-perfeito>
		<futuro-do-presente>
			<p><i>uirei</i></p>
			<p><i>uirás</i></p>
			<p><i>uirá</i></p>
			<p><i>uiremos</i></p>
			<p><i>uireis</i></p>
			<p><i>uirão</i></p>
		</futuro-do-presente>
		</Indicativo>
	<Condicional>
		<futuro-do-pretérito>
			<p><i>uiria</i></p>
			<p><i>uirias</i></p>
			<p><i>uiria</i></p>
			<p><i>uiríamos</i></p>
			<p><i>uiríeis</i></p>
			<p><i>uiriam</i></p>
		</futuro-do-pretérito>
		</Condicional>
	<Subjuntivo>
		<presente>
			<p><i>ua</i></p>
			<p><i>uas</i></p>
			<p><i>ua</i></p>
			<p><i>uamos</i></p>
			<p><i>uais</i></p>
			<p><i>uam</i></p>
		</presente>
		<pretérito-imperfeito>
			<p><i>uisse</i></p>
			<p><i>uisses</i></p>
			<p><i>uisse</i></p>
			<p><i>uíssemos</i></p>
			<p><i>uísseis</i></p>
			<p><i>uissem</i></p>
		</pretérito-imperfeito>
		<futuro>
			<p><i>uir</i></p>
			<p><i>uires</i></p>
			<p><i>uir</i></p>
			<p><i>uirmos</i></p>
			<p><i>uirdes</i></p>
			<p><i>uirem</i></p>
		</futuro>
		</Subjuntivo>
	<Infinitivo>
		<infinitivo-pessoal-presente>
			<p><i>uir</i></p>
			<p><i>uíres</i></p>
			<p><i>uir</i></p>
			<p><i>uirmos</i></p>
			<p><i>uirdes</i></p>
			<p><i>uírem</i></p>
		</infinitivo-pessoal-presente>
		<infinitivo>
			<p><i>uir</i></p>
			<p><i>uido</i></p>
		</infinitivo>
	</Infinitivo>
	<Imperativo>
		<afirmativo>
			<p><i>-</i></p>
			<p><i>úi</i></p>
			<p><i>ua</i></p>
			<p><i>uamos</i></p>
			<p><i>uí</i></p>
			<p><i>uam</i></p>
		</afirmativo>
		<negativo>
			<p><i>-</i></p>
			<p><i>uas</i></p>
			<p><i>ua</i></p>
			<p><i>uamos</i></p>
			<p><i>uais</i></p>
			<p><i>uam</i></p>
		</negativo>
	</Imperativo>
	<Gerúndio>
		<gerúndio>
			<p><i>uindo</i></p>
			<p><i>uido</i></p>
		</gerúndio>
	</Gerúndio>
	<Particípio>
		<particípio>
			<p><i>uido</i></p>
		</particípio>
	</Particípio>
</template>

<template name="averig:uar">
	<Indicativo>
		<presente>
			<p><i>uo</i></p>
			<p><i>uas</i></p>
			<p><i>ua</i></p>
			<p><i>uamos</i></p>
			<p><i>uais</i></p>
			<p><i>uam</i></p>
		</presente>
		<pretérito-imperfeito>
			<p><i>uava</i></p>
			<p><i>uavas</i></p>
			<p><i>uava</i></p>
			<p><i>uávamos</i></p>
			<p><i>uáveis</i></p>
			<p><i>uavam</i></p>
		</pretérito-imperfeito>
		<pretérito-mais-que-perfeito>
			<p><i>uara</i></p>
			<p><i>uaras</i></p>
			<p><i>uara</i></p>
			<p><i>uáramos</i></p>
			<p><i>uáreis</i></p>
			<p><i>uaram</i></p>
		</pretérito-mais-que-perfeito>
		<pretérito-perfeito>
			<p><i/></p>
			<p><i>uaste</i></p>
			<p><i>uou</i></p>
			<p><i/></p>
			<p><i>uastes</i></p>
			<p><i>uaram</i></p>
		</pretérito-perfeito>
		<futuro-do-presente>
			<p><i>uarei</i></p>
			<p><i>uarás</i></p>
			<p><i>uará</i></p>
			<p><i>uaremos</i></p>
			<p><i>uareis</i></p>
			<p><i>uarão</i></p>
		</futuro-do-presente>
		</Indicativo>
	<Condicional>
		<futuro-do-pretérito>
			<p><i>uaria</i></p>
			<p><i>uarias</i></p>
			<p><i>uaria</i></p>
			<p><i>uaríamos</i></p>
			<p><i>uaríeis</i></p>
			<p><i>uariam</i></p>
		</futuro-do-pretérito>
		</Condicional>
	<Subjuntivo>
		<presente>
			<p><i>úe</i></p>
			<p><i>úes</i></p>
			<p><i>úe</i></p>
			<p><i/></p>
			<p><i/></p>
			<p><i/></p>
		</presente>
		<pretérito-imperfeito>
			<p><i>uasse</i></p>
			<p><i>uasses</i></p>
			<p><i>uasse</i></p>
			<p><i>uássemos</i></p>
			<p><i>uásseis</i></p>
			<p><i>uassem</i></p>
		</pretérito-imperfeito>
		<futuro>
			<p><i>uar</i></p>
			<p><i>uares</i></p>
			<p><i>uar</i></p>
			<p><i>uarmos</i></p>
			<p><i>uardes</i></p>
			<p><i>uarem</i></p>
		</futuro>
		</Subjuntivo>
	<Infinitivo>
		<infinitivo-pessoal-presente>
			<p><i>uar</i></p>
			<p><i>uares</i></p>
			<p><i>uar</i></p>
			<p><i>uarmos</i></p>
			<p><i>uardes</i></p>
			<p><i>uarem</i></p>
		</infinitivo-pessoal-presente>
		<infinitivo>
			<p><i>uar</i></p>
			<p><i>uado</i></p>
		</infinitivo>
	</Infinitivo>
	<Imperativo>
		<afirmativo>
			<p><i>-</i></p>
			<p><i>ua</i></p>
			<p><i>úe</i></p>
			<p><i/></p>
			<p><i>uai</i></p>
			<p><i>úem</i></p>
		</afirmativo>
		<negativo>
			<p><i>-</i></p>
			<p><i>úes</i></p>
			<p><i>úe</i></p>
			<p><i/></p>
			<p><i/></p>
			<p><i/></p>
		</negativo>
	</Imperativo>
	<Gerúndio>
		<gerúndio>
			<p><i>uando</i></p>
			<p><i>uado</i></p>
		</gerúndio>
	</Gerúndio>
	<Particípio>
		<particípio>
			<p><i>uado</i></p>
		</particípio>
	</Particípio>
</template>

<template name="av:ir">
	<Indicativo>
		<presente>
			<p><i>enho</i></p>
			<p><i>éns</i></p>
			<p><i>ém</i></p>
			<p><i>imos</i></p>
			<p><i>indes</i></p>
			<p><i>êm</i></p>
		</presente>
		<pretérito-imperfeito>
			<p><i>inha</i></p>
			<p><i>inhas</i></p>
			<p><i>inha</i></p>
			<p><i>ínhamos</i></p>
			<p><i>ínheis</i></p>
			<p><i>inham</i></p>
		</pretérito-imperfeito>
		<pretérito-mais-que-perfeito>
			<p><i>iera</i></p>
			<p><i>ieras</i></p>
			<p><i>iera</i></p>
			<p><i>iéramos</i></p>
			<p><i>iéreis</i></p>
			<p><i>ieram</i></p>
		</pretérito-mais-que-perfeito>
		<pretérito-perfeito>
			<p><i>im</i></p>
			<p><i>ieste</i></p>
			<p><i>eio</i></p>
			<p><i>iemos</i></p>
			<p><i>iestes</i></p>
			<p><i>ieram</i></p>
		</pretérito-perfeito>
		<futuro-do-presente>
			<p><i>irei</i></p>
			<p><i>irás</i></p>
			<p><i>irá</i></p>
			<p><i>iremos</i></p>
			<p><i>ireis</i></p>
			<p><i>irão</i></p>
		</futuro-do-presente>
		</Indicativo>
	<Condicional>
		<futuro-do-pretérito>
			<p><i>iria</i></p>
			<p><i>irias</i></p>
			<p><i>iria</i></p>
			<p><i>iríamos</i></p>
			<p><i>iríeis</i></p>
			<p><i>iriam</i></p>
		</futuro-do-pretérito>
		</Condicional>
	<Subjuntivo>
		<presente>
			<p><i>enha</i></p>
			<p><i>enhas</i></p>
			<p><i>enha</i></p>
			<p><i>enhamos</i></p>
			<p><i>enhais</i></p>
			<p><i>enham</i></p>
		</presente>
		<pretérito-imperfeito>
			<p><i>iesse</i></p>
			<p><i>iesses</i></p>
			<p><i>iesse</i></p>
			<p><i>iéssemos</i></p>
			<p><i>iésseis</i></p>
			<p><i>iessem</i></p>
		</pretérito-imperfeito>
		<futuro>
			<p><i>ier</i></p>
			<p><i>ieres</i></p>
			<p><i>ier</i></p>
			<p><i>iermos</i></p>
			<p><i>ierdes</i></p>
			<p><i>ierem</i></p>
		</futuro>
		</Subjuntivo>
	<Infinitivo>
		<infinitivo-pessoal-presente>
			<p><i>ir</i></p>
			<p><i>ires</i></p>
			<p><i>ir</i></p>
			<p><i>irmos</i></p>
			<p><i>irdes</i></p>
			<p><i>irem</i></p>
		</infinitivo-pessoal-presente>
		<infinitivo>
			<p><i>ir</i></p>
			<p><i>indo</i></p>
		</infinitivo>
	</Infinitivo>
	<Imperativo>
		<afirmativo>
			<p><i>-</i></p>
			<p><i>ém</i></p>
			<p><i>enha</i></p>
			<p><i>enhamos</i></p>
			<p><i>inde</i></p>
			<p><i>enham</i></p>
		</afirmativo>
		<negativo>
			<p><i>-</i></p>
			<p><i>enhas</i></p>
			<p><i>enha</i></p>
			<p><i>enhamos</i></p>
			<p><i>enhais</i></p>
			<p><i>enham</i></p>
		</negativo>
	</Imperativo>
	<Gerúndio>
		<gerúndio>
			<p><i>indo</i></p>
			<p><i>indo</i></p>
		</gerúndio>
	</Gerúndio>
	<Particípio>
		<particípio>
			<p><i>indo</i></p>
		</particípio>
	</Particípio>
</template>

<template name="c:aber">
	<Indicativo>
		<presente>
			<p><i>aibo</i></p>
			<p><i>abes</i></p>
			<p><i>abe</i></p>
			<p><i>abemos</i></p>
			<p><i>abeis</i></p>
			<p><i>abem</i></p>
		</presente>
		<pretérito-imperfeito>
			<p><i>abia</i></p>
			<p><i>abias</i></p>
			<p><i>abia</i></p>
			<p><i>abíamos</i></p>
			<p><i>abíeis</i></p>
			<p><i>abiam</i></p>
		</pretérito-imperfeito>
		<pretérito-mais-que-perfeito>
			<p><i>oubera</i></p>
			<p><i>ouberas</i></p>
			<p><i>oubera</i></p>
			<p><i>oubéramos</i></p>
			<p><i>oubéreis</i></p>
			<p><i>ouberam</i></p>
		</pretérito-mais-que-perfeito>
		<pretérito-perfeito>
			<p><i>oube</i></p>
			<p><i>oubeste</i></p>
			<p><i>oube</i></p>
			<p><i>oubemos</i></p>
			<p><i>oubestes</i></p>
			<p><i>ouberam</i></p>
		</pretérito-perfeito>
		<futuro-do-presente>
			<p><i>aberei</i></p>
			<p><i>aberás</i></p>
			<p><i>aberá</i></p>
			<p><i>aberemos</i></p>
			<p><i>abereis</i></p>
			<p><i>aberão</i></p>
		</futuro-do-presente>
		</Indicativo>
	<Condicional>
		<futuro-do-pretérito>
			<p><i>aberia</i></p>
			<p><i>aberias</i></p>
			<p><i>aberia</i></p>
			<p><i>aberíamos</i></p>
			<p><i>aberíeis</i></p>
			<p><i>aberiam</i></p>
		</futuro-do-pretérito>
		</Condicional>
	<Subjuntivo>
		<presente>
			<p><i>aiba</i></p>
			<p><i>aibas</i></p>
			<p><i>aiba</i></p>
			<p><i>aibamos</i></p>
			<p><i>aibais</i></p>
			<p><i>aibam</i></p>
		</presente>
		<pretérito-imperfeito>
			<p><i>oubesse</i></p>
			<p><i>oubesses</i></p>
			<p><i>oubesse</i></p>
			<p><i>oubéssemos</i></p>
			<p><i>oubésseis</i></p>
			<p><i>oubessem</i></p>
		</pretérito-imperfeito>
		<futuro>
			<p><i>ouber</i></p>
			<p><i>ouberes</i></p>
			<p><i>ouber</i></p>
			<p><i>oubermos</i></p>
			<p><i>ouberdes</i></p>
			<p><i>ouberem</i></p>
		</futuro>
		</Subjuntivo>
	<Infinitivo>
		<infinitivo-pessoal-presente>
			<p><i>aber</i></p>
			<p><i>aberes</i></p>
			<p><i>aber</i></p>
			<p><i>abermos</i></p>
			<p><i>aberdes</i></p>
			<p><i>aberem</i></p>
		</infinitivo-pessoal-presente>
		<infinitivo>
			<p><i>aber</i></p>
			<p><i>abido</i></p>
		</infinitivo>
	</Infinitivo>
	<Imperativo>
		<afirmativo>
			<p><i>-</i></p>
			<p><i>abe</i></p>
			<p><i>aiba</i></p>
			<p><i>aibamos</i></p>
			<p><i>abei</i></p>
			<p><i>aibam</i></p>
		</afirmativo>
		<negativo>
			<p><i>-</i></p>
			<p><i>aibas</i></p>
			<p><i>aiba</i></p>
			<p><i>aibamos</i></p>
			<p><i>aibais</i></p>
			<p><i>aibam</i></p>
		</negativo>
	</Imperativo>
	<Gerúndio>
		<gerúndio>
			<p><i>abendo</i></p>
			<p><i>abido</i></p>
		</gerúndio>
	</Gerúndio>
	<Particípio>
		<particípio>
			<p><i>abido</i></p>
		</particípio>
	</Particípio>
</template>

<template name="c:erzir">
	<Indicativo>
		<presente>
			<p><i>irzo</i></p>
			<p><i>erzes</i></p>
			<p><i>erze</i></p>
			<p><i>erzimos</i></p>
			<p><i>erziz</i></p>
			<p><i>erzem</i></p>
		</presente>
		<pretérito-imperfeito>
			<p><i>erzia</i></p>
			<p><i>erzias</i></p>
			<p><i>erzia</i></p>
			<p><i>erzíamos</i></p>
			<p><i>erzíeis</i></p>
			<p><i>erziam</i></p>
		</pretérito-imperfeito>
		<pretérito-mais-que-perfeito>
			<p><i>erzira</i></p>
			<p><i>erziras</i></p>
			<p><i>erzira</i></p>
			<p><i>erzíramos</i></p>
			<p><i>erzíreis</i></p>
			<p><i>erziram</i></p>
		</pretérito-mais-que-perfeito>
		<pretérito-perfeito>
			<p><i>erzi</i></p>
			<p><i>erziste</i></p>
			<p><i>erziu</i></p>
			<p><i>erzimos</i></p>
			<p><i>erzistes</i></p>
			<p><i>erziram</i></p>
		</pretérito-perfeito>
		<futuro-do-presente>
			<p><i>erzirei</i></p>
			<p><i>erzirás</i></p>
			<p><i>erzirá</i></p>
			<p><i>erziremos</i></p>
			<p><i>erzireis</i></p>
			<p><i>erzirão</i></p>
		</futuro-do-presente>
		</Indicativo>
	<Condicional>
		<futuro-do-pretérito>
			<p><i>erziria</i></p>
			<p><i>erzirias</i></p>