<?xml version='1.0' encoding='utf-8'?>
<!--
	conjugation-ca.xml - List of Catalan conjugation templates.
	The templates follow the xml schema defined by Pierre Sarrazin in verbiste.

	Coypright (C) 2023 Brett Tolbert <https://github.com/bretttolbert/verbecc>
	Copyright (C) 2003-2016 Pierre Sarrazin <http://sarrazip.com/>

	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with this program; if not, write to the Free Software
	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
	02110-1301, USA.
-->
<!DOCTYPE conjugation-ca [
<!ELEMENT conjugation-ca (template)+>
<!ATTLIST conjugation-ca xmlns CDATA #FIXED "">
<!ELEMENT template (Indicatiu , Subjuntiu , Imperatiu , (Condicional , Infinitiu , Gerundi , Particip)?)>
<!ATTLIST template name NMTOKEN #REQUIRED>
<!ELEMENT Indicatiu (present , imperfet , pretèrit , futur)?>
<!ELEMENT Subjuntiu (present , imperfet)?>
<!ELEMENT Imperatiu (imperatiu-present)>
<!ELEMENT Condicional (present)>
<!ELEMENT Infinitiu (infinitiu-present)>
<!ELEMENT Gerundi (gerundi)>
<!ELEMENT Particip (particip)>
<!ELEMENT present (p , p , p , p , p , p)>
<!ELEMENT imperfet (p , p , p , p , p , p)>
<!ELEMENT pretèrit (p , p , p , p , p , p)>
<!ELEMENT futur (p , p , p , p , p , p)>
<!ELEMENT imperatiu-present (p , p , p , p , p)>
<!ELEMENT infinitiu-present (p)+>
<!ELEMENT gerundi (p)+>
<!ELEMENT particip (p, p, p, p)>
<!ELEMENT p (i)+>
<!ELEMENT i (#PCDATA)>
]>
<conjugation-ca>

<!--
Differences between Catalan and Spanish:

1. Spanish has two subjunctive imperfect tenses:
imperfet e.g. nosotros habláramos
DELETE_ME e.g. nosotros hablásemos
AFAIK, Catalan has only one. Observe: Transalation is the same:
nosotros habláramos, nosotros hablásemos = nosaltres parléssim, nosaltres parléssim

2. Spanish has a subjunctive future tense. AFAIK Catalan doesn't.

3. Spanish imperative tense is divided into affirmativo and negativo. AFAIK Catalan doesn't have this.

4. Spanish always has two <p> in <infinitive>, Catalan may have only one

5. Spanish only has one <p> elem in <particip> (How? Thought it was m, f, pm, pf)

6. Spanish always has two <p> in <gerund>

7. Some verbs e.g. 'ser' have 'Indicatif '

8. Some verbs contain a median point e.g. 'sol·licitar'

-->

<template name="malv:eure">
	<Indicatiu>
		<present>
			<p><i>eig</i></p>
			<p><i>eus</i></p>
			<p><i>eu</i></p>
			<p><i>eiem</i></p>
			<p><i>eieu</i></p>
			<p><i>euen</i></p>
		</present>
		<imperfet> <!-- Pretèrit imperfet d'indicatiu aka Imparfait-->
			<p><i>eia</i></p>
			<p><i>eies</i></p>
			<p><i>eia</i></p>
			<p><i>èiem</i></p>
			<p><i>èieu</i></p>
			<p><i>eien</i></p>
		</imperfet>
		<pretèrit> <!-- Preterite (Indicative Past) aka Passé simple -->
			<p><i>iu</i></p>
			<p><i>eieres</i><i>eres</i></p>
			<p><i>eié</i><i>eu</i></p>
			<p><i>eiérem</i><i>érem</i></p>
			<p><i>eiéreu</i><i>éreu</i></p>
			<p><i>eieren</i><i>eren</i></p>
		</pretèrit>
		<futur>
			<p><i>euré</i></p>
			<p><i>euràs</i></p>
			<p><i>eurà</i></p>
			<p><i>eurem</i></p>
			<p><i>eureu</i></p>
			<p><i>euran</i></p>
		</futur>
		</Indicatiu>
	<Subjuntiu>
		<present>
			<p><i>egi</i></p>
			<p><i>egis</i></p>
			<p><i>egi</i></p>
			<p><i>egem</i></p>
			<p><i>egeu</i></p>
			<p><i>egin</i></p>
		</present>
		<imperfet>
			<p><i>eiés</i></p>
			<p><i>eiessis</i></p>
			<p><i>eiés</i></p>
			<p><i>eiéssim</i></p>
			<p><i>eiéssiu</i></p>
			<p><i>eiessin</i></p>
		</imperfet>
	</Subjuntiu>
	<Imperatiu>
		<imperatiu-present>
			<p><i>eges</i><i>es</i></p>
			<p><i>egi</i></p>
			<p><i>egem</i></p>
			<p><i>egeu</i><i>eieu</i></p>
			<p><i>egin</i></p>
		</imperatiu-present>
	</Imperatiu>
	<Condicional>
		<present>
			<p><i>euria</i></p>
			<p><i>euries</i></p>
			<p><i>euria</i></p>
			<p><i>euríem</i></p>
			<p><i>euríeu</i></p>
			<p><i>eurien</i></p>
		</present>
	</Condicional>
	<Infinitiu>
		<infinitiu-present>
			<p><i>eure</i></p>
		</infinitiu-present>
	</Infinitiu>
	<Gerundi>
		<gerundi>
			<p><i>eient</i></p>
		</gerundi>
	</Gerundi>
	<Particip>
		<particip>
			<p><i>ist</i></p> <!-- m participle, alt m participle? -->
			<p><i>ista</i></p> <!-- f participle, alt f participle? -->
			<p><i>ists</i><i>istos</i></p> <!-- pm participle, alt pm participle? -->
			<p><i>istes</i></p> <!-- pf participle, alt pf participle? -->
		</particip>
	</Particip>
</template>

<!-- Second-conjugation (-re, -er) verbs
This is the third-largest group of verbs in Catalan, 
encompassing about four percent of the verbs in the dictionary. 
It includes most of the irregular verbs, the most-frequently-used: 
ser ("to be"), haver ("to have"), fer ("to do"), veure ("to see"), poder ("can"), 
voler ("to want"), caldre ("must"), dir ("to say") and dur ("to take/get"). 
-->
<template name="és:ser">
	<Indicatiu>
		<present>
			<p><i>sóc</i></p>
			<p><i>ets</i></p>
			<p><i>és</i></p>
			<p><i>som</i></p>
			<p><i>sou</i></p>
			<p><i>són</i></p>
		</present>
		<imperfet> <!-- Pretèrit imperfet d'indicatiu aka Imparfait-->
			<p><i>era</i></p>
			<p><i>eres</i></p>
			<p><i>era</i></p>
			<p><i>érem</i></p>
			<p><i>éreu</i></p>
			<p><i>eren</i></p>
		</imperfet>
		<pretèrit> <!-- Preterite (Indicative Past) aka Passé simple -->
			<p><i>fui</i></p>
			<p><i>fores</i></p>
			<p><i>fou</i></p>
			<p><i>fórem</i></p>
			<p><i>fóreu</i></p>
			<p><i>foren</i></p>
		</pretèrit>
		<futur>
			<p><i>seré</i></p>
			<p><i>seràs</i></p>
			<p><i>serà</i></p>
			<p><i>serem</i></p>
			<p><i>sereu</i></p>
			<p><i>seran</i></p>
		</futur>
		</Indicatiu>
	<Subjuntiu>
		<present>
			<p><i>sigui</i></p>
			<p><i>siguis</i></p>
			<p><i>sigui</i></p>
			<p><i>siguem</i></p>
			<p><i>sigueu</i></p>
			<p><i>siguin</i></p>
		</present>
		<imperfet>
			<p><i>fos</i></p>
			<p><i>fossis</i></p>
			<p><i>fos</i></p>
			<p><i>fóssim</i></p>
			<p><i>fóssiu</i></p>
			<p><i>fossin</i></p>
		</imperfet>
	</Subjuntiu>
	<Imperatiu>
		<imperatiu-present>
			<p><i>sigues</i></p>
			<p><i>sigui</i></p>
			<p><i>siguem</i></p>
			<p><i>sigueu</i></p>
			<p><i>siguin</i></p>
		</imperatiu-present>
	</Imperatiu>
	<Condicional>
		<present>
			<p><i>seria</i><i>fora</i></p>
			<p><i>series</i><i>fores</i></p>
			<p><i>seria</i><i>fora</i></p>
			<p><i>seríem</i><i>fórem</i></p>
			<p><i>seríeu</i><i>fóreu</i></p>
			<p><i>serien</i><i>foren</i></p>
		</present>
		</Condicional>
	<Infinitiu>
		<infinitiu-present>
			<p><i>ser</i></p>
			<p><i>ésser</i></p>
		</infinitiu-present>
	</Infinitiu>
	<Gerundi>
		<gerundi>
			<p><i>sent</i></p>
			<p><i>essent</i></p>
		</gerundi>
	</Gerundi>
	<Particip>
		<!-- Should particip be divided as with French into participe-présent and participe-passé? -->
		<particip>
			<p><i>estat</i><i>sigut</i></p> <!-- m participle, alt m participle? -->
			<p><i>estada</i><i>siguda</i></p> <!-- f participle, alt f participle? -->
			<p><i>estats</i><i>siguts</i></p> <!-- pm participle, alt pm participle? -->
			<p><i>estades</i><i>sigudes</i></p> <!-- pf participle, alt pf participle? -->
		</particip>
	</Particip>
</template>

<template name="re:bre">
	<Indicatiu>
		<present>
			<p><i>bo</i></p>
			<p><i>ps</i></p>
			<p><i>p</i></p>
			<p><i>bem</i></p>
			<p><i>beu</i></p>
			<p><i>ben</i></p>
		</present>
		<imperfet>
			<p><i>bia</i></p>
			<p><i>bies</i></p>
			<p><i>bia</i></p>
			<p><i>bíem</i></p>
			<p><i>bíeu</i></p>
			<p><i>bien</i></p>
		</imperfet>
		<pretèrit>
			<p><i>bí</i></p>
			<p><i>beres</i></p>
			<p><i>bé</i></p>
			<p><i>bérem</i></p>
			<p><i>béreu</i></p>
			<p><i>beren</i></p>
		</pretèrit>
		<futur>
			<p><i>bré</i></p>
			<p><i>bràs</i></p>
			<p><i>brà</i></p>
			<p><i>brem</i></p>
			<p><i>breu</i></p>
			<p><i>bran</i></p>
		</futur>
		</Indicatiu>
	<Subjuntiu>
		<present>
			<p><i>bi</i></p>
			<p><i>bis</i></p>
			<p><i>bi</i></p>
			<p><i>bem</i></p>
			<p><i>beu</i></p>
			<p><i>bin</i></p>
		</present>
		<imperfet>
			<p><i>bés</i></p>
			<p><i>bessis</i></p>
			<p><i>bés</i></p>
			<p><i>béssim</i></p>
			<p><i>béssiu</i></p>
			<p><i>bessin</i></p>
		</imperfet>
	</Subjuntiu>
	<Imperatiu>
		<imperatiu-present>
			<p><i>p</i></p>
			<p><i>bi</i></p>
			<p><i>bem</i></p>
			<p><i>beu</i></p>
			<p><i>bin</i></p>
		</imperatiu-present>
	</Imperatiu>
	<Condicional>
		<present>
			<p><i>bria</i></p>
			<p><i>bries</i></p>
			<p><i>bria</i></p>
			<p><i>bríem</i></p>
			<p><i>bríeu</i></p>
			<p><i>brien</i></p>
		</present>
		</Condicional>
	<Infinitiu>
		<infinitiu-present>
			<p><i>bre</i></p>
		</infinitiu-present>
	</Infinitiu>
	<Gerundi>
		<gerundi>
			<p><i>bent</i></p>
		</gerundi>
	</Gerundi>
	<Particip>
		<particip>
			<p><i>but</i></p>
			<p><i>buda</i></p>
			<p><i>buts</i></p>
			<p><i>budes</i></p>
		</particip>
	</Particip>
</template>

<template name="perd:re">
	<Indicatiu>
		<present>
			<p><i>o</i></p>
			<p><i>s</i></p>
			<p><i></i></p>
			<p><i>em</i></p>
			<p><i>eu</i></p>
			<p><i>en</i></p>
		</present>
		<imperfet>
			<p><i>ia</i></p>
			<p><i>ies</i></p>
			<p><i>ia</i></p>
			<p><i>íem</i></p>
			<p><i>íeu</i></p>
			<p><i>ien</i></p>
		</imperfet>
		<pretèrit>
			<p><i>í</i></p>
			<p><i>eres</i></p>
			<p><i>é</i></p>
			<p><i>érem</i></p>
			<p><i>éreu</i></p>
			<p><i>eren</i></p>
		</pretèrit>
		<futur>
			<p><i>é</i></p>
			<p><i>às</i></p>
			<p><i>à</i></p>
			<p><i>em</i></p>
			<p><i>eu</i></p>
			<p><i>an</i></p>
		</futur>
		</Indicatiu>
	<Subjuntiu>
		<present>
			<p><i>i</i></p>
			<p><i>is</i></p>
			<p><i>i</i></p>
			<p><i>em</i></p>
			<p><i>eu</i></p>
			<p><i>in</i></p>
		</present>
		<imperfet>
			<p><i>és</i></p>
			<p><i>essis</i></p>
			<p><i>és</i></p>
			<p><i>éssim</i></p>
			<p><i>éssiu</i></p>
			<p><i>essin</i></p>
		</imperfet>
	</Subjuntiu>
	<Imperatiu>
		<imperatiu-present>
			<p><i></i></p>
			<p><i>i</i></p>
			<p><i>em</i></p>
			<p><i>eu</i></p>
			<p><i>in</i></p>
		</imperatiu-present>
	</Imperatiu>
	<Condicional>
		<present>
			<p><i>ria</i></p>
			<p><i>ries</i></p>
			<p><i>ria</i></p>
			<p><i>ríem</i></p>
			<p><i>ríeu</i></p>
			<p><i>rien</i></p>
		</present>
		</Condicional>
	<Infinitiu>
		<infinitiu-present>
			<p><i>re</i></p>
		</infinitiu-present>
	</Infinitiu>
	<Gerundi>
		<gerundi>
			<p><i>ent</i></p>
		</gerundi>
	</Gerundi>
	<Particip>
		<particip>
			<p><i>ut</i></p>
			<p><i>uda</i></p>
			<p><i>uts</i></p>
			<p><i>udes</i></p>
		</particip>
	</Particip>
</template>

<template name=":caure">
	<Indicatiu>
		<present>
			<p><i>caic</i></p>
			<p><i>caus</i></p>
			<p><i>cau</i></p>
			<p><i>caiem</i></p>
			<p><i>caieu</i></p>
			<p><i>cauen</i></p>
		</present>
		<imperfet>
			<p><i>queia</i></p>
			<p><i>queies</i></p>
			<p><i>queia</i></p>
			<p><i>quèiem</i></p>
			<p><i>quèieu</i></p>
			<p><i>queien</i></p>
		</imperfet>
		<pretèrit>
			<p><i>caiguí</i></p>
			<p><i>caigueres</i></p>
			<p><i>caigué</i></p>
			<p><i>caiguérem</i></p>
			<p><i>caiguéreu</i></p>
			<p><i>caigueren</i></p>
		</pretèrit>
		<futur>
			<p><i>cauré</i></p>
			<p><i>cauràs</i></p>
			<p><i>caurà</i></p>
			<p><i>caurem</i></p>
			<p><i>caureu</i></p>
			<p><i>cauran</i></p>
		</futur>
		</Indicatiu>
	<Subjuntiu>
		<present>
			<p><i>caigui</i></p>
			<p><i>caiguis</i></p>
			<p><i>caigui</i></p>
			<p><i>caiguem</i></p>
			<p><i>caigueu</i></p>
			<p><i>caiguin</i></p>
		</present>
		<imperfet>
			<p><i>caigués</i></p>
			<p><i>caiguessis</i></p>
			<p><i>caigués</i></p>
			<p><i>caiguéssim</i></p>
			<p><i>caiguéssiu</i></p>
			<p><i>caiguessin</i></p>
		</imperfet>
	</Subjuntiu>
	<Imperatiu>
		<imperatiu-present>
			<p><i>cau</i></p>
			<p><i>caigui</i></p>
			<p><i>caiguem</i></p>
			<p><i>caieu</i></p>
			<p><i>caiguin</i></p>
		</imperatiu-present>
	</Imperatiu>
	<Condicional>
		<present>
			<p><i>cauria</i></p>
			<p><i>cauries</i></p>
			<p><i>cauria</i></p>
			<p><i>cauríem</i></p>
			<p><i>cauríeu</i></p>
			<p><i>caurien</i></p>
		</present>
		</Condicional>
	<Infinitiu>
		<infinitiu-present>
			<p><i>caure</i></p>
		</infinitiu-present>
	</Infinitiu>
	<Gerundi>
		<gerundi>
			<p><i>caient</i></p>
		</gerundi>
	</Gerundi>
	<Particip>
		<particip>
			<p><i>caigut</i></p>
			<p><i>caiguda</i></p>
			<p><i>caiguts</i></p>
			<p><i>caigudes</i></p>
		</particip>
	</Particip>
</template>

<template name=":collir">
	<Indicatiu>
		<present>
			<p><i>cullo</i></p>
			<p><i>culls</i></p>
			<p><i>cull</i></p>
			<p><i>collim</i></p>
			<p><i>colliu</i></p>
			<p><i>cullen</i></p>
		</present>
		<imperfet>
			<p><i>collmia</i></p>
			<p><i>collmies</i></p>
			<p><i>collmia</i></p>
			<p><i>collmiem</i></p>
			<p><i>collmieu</i></p>
			<p><i>collmien</i></p>
		</imperfet>
		<pretèrit>
			<p><i>collí</i></p>
			<p><i>collires</i></p>
			<p><i>collí</i></p>
			<p><i>collírem</i></p>
			<p><i>collíreu</i></p>
			<p><i>colliren</i></p>
		</pretèrit>
		<futur>
			<p><i>colliré</i></p>
			<p><i>colliràs</i></p>
			<p><i>collirà</i></p>
			<p><i>collirem</i></p>
			<p><i>collireu</i></p>
			<p><i>colliran</i></p>
		</futur>
		</Indicatiu>
	<Subjuntiu>
		<present>
			<p><i>colli</i></p>
			<p><i>collis</i></p>
			<p><i>colli</i></p>
			<p><i>collim</i></p>
			<p><i>colliu</i></p>
			<p><i>collin</i></p>
		</present>
		<imperfet>
			<p><i>collís</i></p>
			<p><i>collissis</i></p>
			<p><i>collís</i></p>
			<p><i>collíssim</i></p>
			<p><i>collíssiu</i></p>
			<p><i>collissin</i></p>
		</imperfet>
	</Subjuntiu>
	<Imperatiu>
		<imperatiu-present>
			<p><i>coll</i></p>
			<p><i>colli</i></p>
			<p><i>collim</i></p>
			<p><i>colliu</i></p>
			<p><i>collin</i></p>
		</imperatiu-present>
	</Imperatiu>
	<Condicional>
		<present>
			<p><i>colliria</i></p>
			<p><i>colliries</i></p>
			<p><i>colliria</i></p>
			<p><i>colliríem</i></p>
			<p><i>colliríeu</i></p>
			<p><i>collirien</i></p>
		</present>
		</Condicional>
	<Infinitiu>
		<infinitiu-present>
			<p><i>collir</i></p>
		</infinitiu-present>
	</Infinitiu>
	<Gerundi>
		<gerundi>
			<p><i>collint</i></p>
		</gerundi>
	</Gerundi>
	<Particip>
		<particip>
			<p><i>collit</i></p>
			<p><i>collida</i></p>
			<p><i>collits</i></p>
			<p><i>collides</i></p>
		</particip>
	</Particip>
</template>

<template name="desf:er">
	<Indicatiu>
		<present>
			<p><i>aig</i></p>
			<p><i>as</i></p>
			<p><i>a</i></p>
			<p><i>em</i></p>
			<p><i>eu</i></p>
			<p><i>an</i></p>
		</present>
		<imperfet>
			<p><i>eia</i></p>
			<p><i>eies</i></p>
			<p><i>eia</i></p>
			<p><i>èiem</i></p>
			<p><i>èieu</i></p>
			<p><i>eien</i></p>
		</imperfet>
		<pretèrit>
			<p><i>iu</i></p>
			<p><i>eres</i></p>
			<p><i>eu</i></p>
			<p><i>érem</i></p>
			<p><i>éreu</i></p>
			<p><i>eren</i></p>
		</pretèrit>
		<futur>
			<p><i>aré</i></p>
			<p><i>aràs</i></p>
			<p><i>arà</i></p>
			<p><i>arem</i></p>
			<p><i>areu</i></p>
			<p><i>aran</i></p>
		</futur>
		</Indicatiu>
	<Subjuntiu>
		<present>
			<p><i>aci</i></p>
			<p><i>acis</i></p>
			<p><i>aci</i></p>
			<p><i>em</i></p>
			<p><i>eu</i></p>
			<p><i>acin</i></p>
		</present>
		<imperfet>
			<p><i>es</i></p>
			<p><i>essis</i></p>
			<p><i>es</i></p>
			<p><i>éssim</i></p>
			<p><i>éssiu</i></p>
			<p><i>essin</i></p>
		</imperfet>
	</Subjuntiu>
	<Imperatiu>
		<imperatiu-present>
			<p><i>es</i></p>
			<p><i>aci</i></p>
			<p><i>em</i></p>
			<p><i>eu</i></p>
			<p><i>acin</i></p>
		</imperatiu-present>
	</Imperatiu>
	<Condicional>
		<present>
			<p><i>aria</i></p>
			<p><i>aries</i></p>
			<p><i>aria</i></p>
			<p><i>aríem</i></p>
			<p><i>aríeu</i></p>
			<p><i>arien</i></p>
		</present>
		</Condicional>
	<Infinitiu>
		<infinitiu-present>
			<p><i>er</i></p>
		</infinitiu-present>
	</Infinitiu>
	<Gerundi>
		<gerundi>
			<p><i>ent</i></p>
		</gerundi>
	</Gerundi>
	<Particip>
		<particip>
			<p><i>et</i></p>
			<p><i>eta</i></p>
			<p><i>ets</i></p>
			<p><i>etes</i></p>
		</particip>
	</Particip>
</template>

<template name="est:ar">
	<Indicatiu>
		<present>
			<p><i>ic</i></p>
			<p><i>às</i></p>
			<p><i>à</i></p>
			<p><i>em</i></p>
			<p><i>eu</i></p>
			<p><i>an</i></p>
		</present>
		<imperfet>
			<p><i>ava</i></p>
			<p><i>aves</i></p>
			<p><i>ava</i></p>
			<p><i>àvem</i></p>
			<p><i>àveu</i></p>
			<p><i>aven</i></p>
		</imperfet>
		<pretèrit>
			<p><i>iguí</i></p>
			<p><i>igueres</i></p>
			<p><i>igué</i></p>
			<p><i>iguérem</i></p>
			<p><i>iguéreu</i></p>
			<p><i>igueren</i></p>
		</pretèrit>
		<futur>
			<p><i>aré</i></p>
			<p><i>aràs</i></p>
			<p><i>arà</i></p>
			<p><i>arem</i></p>
			<p><i>areu</i></p>
			<p><i>aran</i></p>
		</futur>
		</Indicatiu>
	<Subjuntiu>
		<present>
			<p><i>igui</i></p>
			<p><i>iguis</i></p>
			<p><i>igui</i></p>
			<p><i>iguem</i></p>
			<p><i>igueu</i></p>
			<p><i>iguin</i></p>
		</present>
		<imperfet>
			<p><i>igués</i></p>
			<p><i>iguessis</i></p>
			<p><i>igués</i></p>
			<p><i>iguéssim</i></p>
			<p><i>iguéssiu</i></p>
			<p><i>iguessin</i></p>
		</imperfet>
	</Subjuntiu>
	<Imperatiu>
		<imperatiu-present>
			<p><i>á</i></p>
			<p><i>é</i></p>
			<p><i>emos</i></p>
			<p><i>ad</i></p>
			<p><i>én</i></p>
		</imperatiu-present>
	</Imperatiu>
	<Condicional>
		<present>
			<p><i>aria</i></p>
			<p><i>aries</i></p>
			<p><i>aria</i></p>
			<p><i>aríem</i></p>
			<p><i>aríeu</i></p>
			<p><i>arien</i></p>
		</present>
		</Condicional>
	<Infinitiu>
		<infinitiu-present>
			<p><i>ar</i></p>
			<p><i>ado</i></p>
		</infinitiu-present>
	</Infinitiu>
	<Gerundi>
		<gerundi>
			<p><i>ando</i></p>
			<p><i>ado</i></p>
		</gerundi>
	</Gerundi>
	<Particip>
		<particip>
			<p><i>at</i></p>
			<p><i>ada</i></p>
			<p><i>ats</i></p>
			<p><i>ades</i></p>
		</particip>
	</Particip>
</template>


<!-- First-conjugation (-ar) verbs 
About 86 percent of Catalan verbs belong to this group. 
-->
<!-- [es] hablar = [ca] parlar -->
<!-- [es] hablar, cantar use template "cor:tar" -->
<!-- [ca] parlar uses template "cant:ar"-->
<template name="cant:ar">
	<Indicatiu>
		<present>
			<p><i>o</i></p>
			<p><i>es</i></p>
			<p><i>a</i></p>
			<p><i>em</i></p>
			<p><i>eu</i></p>
			<p><i>en</i></p>
		</present>
		<imperfet>
			<p><i>ava</i></p>
			<p><i>aves</i></p>
			<p><i>ava</i></p>
			<p><i>àvem</i></p>
			<p><i>àveu</i></p>
			<p><i>aven</i></p>
		</imperfet>
		<pretèrit>
			<p><i>í</i></p>
			<p><i>ares</i></p>
			<p><i>à</i></p>
			<p><i>àrem</i></p>
			<p><i>àreu</i></p>
			<p><i>aren</i></p>
		</pretèrit> 
		<futur>
			<p><i>aré</i></p>
			<p><i>aràs</i></p>
			<p><i>arà</i></p>
			<p><i>arem</i></p>
			<p><i>areu</i></p>
			<p><i>aran</i></p>
		</futur>
	</Indicatiu>
	<Subjuntiu>
		<present>
			<p><i>i</i></p>
			<p><i>is</i></p>
			<p><i>i</i></p>
			<p><i>em</i></p>
			<p><i>eu</i></p>
			<p><i>in</i></p>
		</present>
		<imperfet>
			<p><i>és</i></p>
			<p><i>essis</i></p>
			<p><i>és</i></p>
			<p><i>éssim</i></p>
			<p><i>éssiu</i></p>
			<p><i>essin</i></p>
		</imperfet>
	</Subjuntiu>
	<Imperatiu>
		<imperatiu-present>
			<p><i>a</i></p>
			<p><i>i</i></p>
			<p><i>em</i></p>
			<p><i>eu</i></p>
			<p><i>in</i></p>
		</imperatiu-present>
	</Imperatiu>
	<Condicional>
		<present>
			<p><i>aria</i></p>
			<p><i>aries</i></p>
			<p><i>aria</i></p>
			<p><i>aríem</i></p>
			<p><i>aríeu</i></p>
			<p><i>arien</i></p>
		</present>
	</Condicional>
	<Infinitiu>
		<infinitiu-present>
			<p><i>ar</i></p>
		</infinitiu-present>
	</Infinitiu>
	<Gerundi>
		<gerundi>
			<p><i>ant</i></p>
		</gerundi>
	</Gerundi>
	<Particip>
		<particip>
			<p><i>at</i></p>
			<p><i>ada</i></p>
			<p><i>ats</i></p>
			<p><i>ades</i></p>
		</particip>
	</Particip>
</template>

<!-- TODO: This template should inherit from base template "cant:ar"-->
<template name="comen:çar">
	<Indicatiu>
		<present>
			<p><i>ço</i></p>
			<p><i>ces</i></p>
			<p><i>ça</i></p>
			<p><i>cem</i></p>
			<p><i>ceu</i></p>
			<p><i>cen</i></p>
		</present>
		<imperfet>
			<p><i>çava</i></p>
			<p><i>çaves</i></p>
			<p><i>çava</i></p>
			<p><i>çàvem</i></p>
			<p><i>çàveu</i></p>
			<p><i>çaven</i></p>
		</imperfet>
		<pretèrit>
			<p><i>cí</i></p>
			<p><i>çares</i></p>
			<p><i>çà</i></p>
			<p><i>çàrem</i></p>
			<p><i>çàreu</i></p>
			<p><i>çaren</i></p>
		</pretèrit> 
		<futur>
			<p><i>çaré</i></p>
			<p><i>çaràs</i></p>
			<p><i>çarà</i></p>
			<p><i>çarem</i></p>
			<p><i>çareu</i></p>
			<p><i>çaran</i></p>
		</futur>
	</Indicatiu>
	<Subjuntiu>
		<present>
			<p><i>ci</i></p>
			<p><i>cis</i></p>
			<p><i>ci</i></p>
			<p><i>cem</i></p>
			<p><i>ceu</i></p>
			<p><i>cin</i></p>
		</present>
		<imperfet>
			<p><i>cés</i></p>
			<p><i>cessis</i></p>
			<p><i>cés</i></p>
			<p><i>céssim</i></p>
			<p><i>céssiu</i></p>
			<p><i>cessin</i></p>
		</imperfet>
	</Subjuntiu>
	<Imperatiu>
		<imperatiu-present>
			<p><i>ça</i></p>
			<p><i>ci</i></p>
			<p><i>cem</i></p>
			<p><i>ceu</i></p>
			<p><i>cin</i></p>
		</imperatiu-present>
	</Imperatiu>
	<Condicional>
		<present>
			<p><i>çaria</i></p>
			<p><i>çaries</i></p>
			<p><i>çaria</i></p>
			<p><i>çaríem</i></p>
			<p><i>çaríeu</i></p>
			<p><i>çarien</i></p>
		</present>
	</Condicional>
	<Infinitiu>
		<infinitiu-present>
			<p><i>çar</i></p>
		</infinitiu-present>
	</Infinitiu>
	<Gerundi>
		<gerundi>
			<p><i>çant</i></p>
		</gerundi>
	</Gerundi>
	<Particip>
		<particip>
			<p><i>çat</i></p>
			<p><i>çada</i></p>
			<p><i>çats</i></p>
			<p><i>çades</i></p>
		</particip>
	</Particip>
</template>

<!-- TODO: This template should inherit from base template "cant:ar"-->
<template name="enaig:uar">
	<Indicatiu>
		<present>
			<p><i>uo</i></p>
			<p><i>ües</i></p>
			<p><i>ua</i></p>
			<p><i>üem</i></p>
			<p><i>üeu</i></p>
			<p><i>üen</i></p>
		</present>
		<imperfet>
			<p><i>uava</i></p>
			<p><i>uaves</i></p>
			<p><i>uava</i></p>
			<p><i>uàvem</i></p>
			<p><i>uàveu</i></p>
			<p><i>uaven</i></p>
		</imperfet>
		<pretèrit>
			<p><i>üí</i></p>
			<p><i>uares</i></p>
			<p><i>uà</i></p>
			<p><i>uàrem</i></p>
			<p><i>uàreu</i></p>
			<p><i>uaren</i></p>
		</pretèrit> 
		<futur>
			<p><i>uaré</i></p>
			<p><i>uaràs</i></p>
			<p><i>uarà</i></p>
			<p><i>uarem</i></p>
			<p><i>uareu</i></p>
			<p><i>uaran</i></p>
		</futur>
	</Indicatiu>
	<Subjuntiu>
		<present>
			<p><i>üi</i></p>
			<p><i>üis</i></p>
			<p><i>üi</i></p>
			<p><i>üem</i></p>
			<p><i>üeu</i></p>
			<p><i>üin</i></p>
		</present>
		<imperfet>
			<p><i>üés</i></p>
			<p><i>üessis</i></p>
			<p><i>üés</i></p>
			<p><i>üéssim</i></p>
			<p><i>üéssiu</i></p>
			<p><i>üessin</i></p>
		</imperfet>
	</Subjuntiu>
	<Imperatiu>
		<imperatiu-present>
			<p><i>ua</i></p>
			<p><i>üi</i></p>
			<p><i>üem</i></p>
			<p><i>üeu</i></p>
			<p><i>üin</i></p>
		</imperatiu-present>
	</Imperatiu>
	<Condicional>
		<present>
			<p><i>uaria</i></p>
			<p><i>uaries</i></p>
			<p><i>uaria</i></p>
			<p><i>uaríem</i></p>
			<p><i>uaríeu</i></p>
			<p><i>uarien</i></p>
		</present>
	</Condicional>
	<Infinitiu>
		<infinitiu-present>
			<p><i>uar</i></p>
		</infinitiu-present>
	</Infinitiu>
	<Gerundi>
		<gerundi>
			<p><i>uant</i></p>
		</gerundi>
	</Gerundi>
	<Particip>
		<particip>
			<p><i>uat</i></p>
			<p><i>uada</i></p>
			<p><i>uats</i></p>
			<p><i>uades</i></p>
		</particip>
	</Particip>
</template>

<!-- TODO: This template should inherit from base template "cant:ar"-->
<template name="enve:jar">
	<Indicatiu>
		<present>
			<p><i>jo</i></p>
			<p><i>ges</i></p>
			<p><i>ja</i></p>
			<p><i>gem</i></p>
			<p><i>geu</i></p>
			<p><i>gen</i></p>
		</present>
		<imperfet>
			<p><i>java</i></p>
			<p><i>javes</i></p>
			<p><i>java</i></p>
			<p><i>jàvem</i></p>
			<p><i>jàveu</i></p>
			<p><i>javen</i></p>
		</imperfet>
		<pretèrit>
			<p><i>gí</i></p>
			<p><i>jares</i></p>
			<p><i>jà</i></p>
			<p><i>jàrem</i></p>
			<p><i>jàreu</i></p>
			<p><i>jaren</i></p>
		</pretèrit> 
		<futur>
			<p><i>jaré</i></p>
			<p><i>jaràs</i></p>
			<p><i>jarà</i></p>
			<p><i>jarem</i></p>
			<p><i>jareu</i></p>
			<p><i>jaran</i></p>
		</futur>
	</Indicatiu>
	<Subjuntiu>
		<present>
			<p><i>gi</i></p>
			<p><i>gis</i></p>
			<p><i>gi</i></p>
			<p><i>gem</i></p>
			<p><i>geu</i></p>
			<p><i>gin</i></p>
		</present>
		<imperfet>
			<p><i>gés</i></p>
			<p><i>gessis</i></p>
			<p><i>gés</i></p>
			<p><i>géssim</i></p>
			<p><i>géssiu</i></p>
			<p><i>gessin</i></p>
		</imperfet>
	</Subjuntiu>
	<Imperatiu>
		<imperatiu-present>
			<p><i>ja</i></p>
			<p><i>gi</i></p>
			<p><i>gem</i></p>
			<p><i>geu</i></p>
			<p><i>gin</i></p>
		</imperatiu-present>
	</Imperatiu>
	<Condicional>
		<present>
			<p><i>jaria</i></p>
			<p><i>jaries</i></p>
			<p><i>jaria</i></p>
			<p><i>jaríem</i></p>
			<p><i>jaríeu</i></p>
			<p><i>jarien</i></p>
		</present>
	</Condicional>
	<Infinitiu>
		<infinitiu-present>
			<p><i>jar</i></p>
		</infinitiu-present>
	</Infinitiu>
	<Gerundi>
		<gerundi>
			<p><i>jant</i></p>
		</gerundi>
	</Gerundi>
	<Particip>
		<particip>
			<p><i>jat</i></p>
			<p><i>jada</i></p>
			<p><i>jats</i></p>
			<p><i>jades</i></p>
		</particip>
	</Particip>
</template>

<!-- TODO: This template should inherit from the base template "cant:ar" -->
<template name="tren:car">
	<Indicatiu>
		<present>
			<p><i>co</i></p>
			<p><i>ques</i></p>
			<p><i>ca</i></p>
			<p><i>quem</i></p>
			<p><i>queu</i></p>
			<p><i>quen</i></p>
		</present>
		<imperfet>
			<p><i>cava</i></p>
			<p><i>caves</i></p>
			<p><i>cava</i></p>
			<p><i>càvem</i></p>
			<p><i>càveu</i></p>
			<p><i>caven</i></p>
		</imperfet>
		<pretèrit>
			<p><i>quí</i></p>
			<p><i>cares</i></p>
			<p><i>cà</i></p>
			<p><i>càrem</i></p>
			<p><i>càreu</i></p>
			<p><i>caren</i></p>
		</pretèrit> 
		<futur>
			<p><i>caré</i></p>
			<p><i>caràs</i></p>
			<p><i>carà</i></p>
			<p><i>carem</i></p>
			<p><i>careu</i></p>
			<p><i>caran</i></p>
		</futur>
	</Indicatiu>
	<Subjuntiu>
		<present>
			<p><i>qi</i></p>
			<p><i>quis</i></p>
			<p><i>qui</i></p>
			<p><i>quem</i></p>
			<p><i>queu</i></p>
			<p><i>quin</i></p>
		</present>
		<imperfet>
			<p><i>qués</i></p>
			<p><i>quessis</i></p>
			<p><i>qués</i></p>
			<p><i>quéssim</i></p>
			<p><i>quéssiu</i></p>
			<p><i>quessin</i></p>
		</imperfet>
	</Subjuntiu>
	<Imperatiu>
		<imperatiu-present>
			<p><i>ca</i></p>
			<p><i>qui</i></p>
			<p><i>quem</i></p>
			<p><i>queu</i></p>
			<p><i>quin</i></p>
		</imperatiu-present>
	</Imperatiu>
	<Condicional>
		<present>
			<p><i>caria</i></p>
			<p><i>caries</i></p>
			<p><i>caria</i></p>
			<p><i>caríem</i></p>
			<p><i>caríeu</i></p>
			<p><i>carien</i></p>
		</present>
	</Condicional>
	<Infinitiu>
		<infinitiu-present>
			<p><i>car</i></p>
		</infinitiu-present>
	</Infinitiu>
	<Gerundi>
		<gerundi>
			<p><i>cant</i></p>
		</gerundi>
	</Gerundi>
	<Particip>
		<particip>
			<p><i>cat</i></p>
			<p><i>cada</i></p>
			<p><i>cats</i></p>
			<p><i>cades</i></p>
		</particip>
	</Particip>
</template>

<!--
Spanish 'haber' uses 'h:aber'
so Catalan 'haver' should use 'h:aver'
-->
<template name="h:aver">
	<Indicatiu>
		<present>
			<p><i>e</i><i>aig</i></p>
			<p><i>as</i></p>
			<p><i>a</i></p>
			<p><i>avem</i><i>em</i></p>
			<p><i>aveu</i><i>eu</i></p>
			<p><i>an</i></p>
		</present>
		<imperfet>
			<p><i>avia</i></p>
			<p><i>avies</i></p>
			<p><i>avia</i></p>
			<p><i>avíem</i></p>
			<p><i>avíeu</i></p>
			<p><i>avien</i></p>
		</imperfet>
		<pretèrit>
			<p><i>aguí</i></p>
			<p><i>agueres</i></p>
			<p><i>agué</i></p>
			<p><i>aguérem</i></p>
			<p><i>aguéreu</i></p>
			<p><i>agueren</i></p>
		</pretèrit>
		<futur>
			<p><i>auré</i></p>
			<p><i>auràs</i></p>
			<p><i>aurà</i></p>
			<p><i>aurem</i></p>
			<p><i>aureu</i></p>
			<p><i>auran</i></p>
		</futur>
		</Indicatiu>
	<Subjuntiu>
		<present>
			<p><i>agi</i></p>
			<p><i>agis</i></p>
			<p><i>agi</i></p>
			<p><i>àgim</i><i>aguem</i></p>
			<p><i>àgiu</i><i>agueu</i></p>
			<p><i>agin</i></p>
		</present>
		<imperfet>
			<p><i>agués</i></p>
			<p><i>aguessis</i><i>aguesses</i></p>
			<p><i>agués</i></p>
			<p><i>aguéssim</i><i>aguéssem</i></p>
			<p><i>aguéssiu</i><i>aguésseu</i></p>
			<p><i>aguessin</i><i>aguessen</i></p>
		</imperfet>
	</Subjuntiu>
	<Imperatiu>
		<imperatiu-present>
			<p><i></i></p>
			<p><i></i></p>
			<p><i></i></p>
			<p><i></i></p>
			<p><i></i></p>
		</imperatiu-present>
	</Imperatiu>
	<Condicional>
		<present>
			<p><i>auria</i><i>aguera</i></p>
			<p><i>auries</i><i>agueras</i></p>
			<p><i>auria</i><i>aguera</i></p>
			<p><i>auríem</i><i>aguérem</i></p>
			<p><i>auríeu</i><i>aguéreu</i></p>
			<p><i>aurien</i><i>agueren</i></p>
		</present>
		</Condicional>
	<Infinitiu>
		<infinitiu-present>
			<p><i>aver</i></p>
		</infinitiu-present>
	</Infinitiu>
	<Gerundi>
		<gerundi>
			<p><i>avent</i></p>
		</gerundi>
	</Gerundi>
	<Particip>
		<particip>
			<p><i>agut</i></p>
			<p><i>aguda</i></p>
			<p><i>aguts</i></p>
			<p><i>agudes</i></p>
		</particip>
	</Particip>
</template>

<!--
Spanish 'tener' uses template 't:ener'
so Catalan 'tenir' should use 't:enir'
-->
<template name="obt:enir">
	<Indicatiu>
		<present>
			<p><i>inc</i></p>
			<p><i>ens</i></p>
			<p><i>é</i></p>
			<p><i>enim</i></p>
			<p><i>eniu</i></p>
			<p><i>enen</i></p>
		</present>
		<imperfet>
			<p><i>enia</i></p>
			<p><i>enies</i></p>
			<p><i>enia</i></p>
			<p><i>eníem</i></p>
			<p><i>eníeu</i></p>
			<p><i>enien</i></p>
		</imperfet>
		<pretèrit>
			<p><i>inguí</i></p>
			<p><i>ingueres</i></p>
			<p><i>ingué</i></p>
			<p><i>inguérem</i></p>
			<p><i>inguéreu</i></p>
			<p><i>ingueren</i></p>
		</pretèrit>
		<futur>
			<p><i>indré</i></p>
			<p><i>indràs</i></p>
			<p><i>indrà</i></p>
			<p><i>indrem</i></p>
			<p><i>indreu</i></p>
			<p><i>indran</i></p>
		</futur>
		</Indicatiu>
	<Subjuntiu>
		<present>
			<p><i>ingui</i></p>
			<p><i>inguis</i></p>
			<p><i>ingui</i></p>
			<p><i>inguem</i></p>
			<p><i>ingueu</i></p>