<?xml version="1.0" encoding="UTF-8"?>

<!--
	conjugation-fr.xml - French conjugation templates
	Created by Pierre Sarrazin
	Further improved by Brett Tolbert:
	- Converted tense tag names to lowercase for ease of use
	- Added templates for impersonal verbs, e.g. "pl:euvoir"
	Coypright (C) 2023 Brett Tolbert <https://github.com/bretttolbert/verbecc>
	Copyright (C) 2003-2016 Pierre Sarrazin <http://sarrazip.com/>

	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with this program; if not, write to the Free Software
	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
	02110-1301, USA.
-->

<!DOCTYPE conjugation-fr [
	<!ELEMENT conjugation-fr (template+)>
	<!ELEMENT template (Infinitif, Indicatif, Conditionnel, Subjonctif, Imperatif, Participe)>
	<!ATTLIST template name CDATA #REQUIRED>

	<!ELEMENT Infinitif (infinitif-présent)>
	<!ELEMENT Indicatif (présent, imparfait, futur-simple, passé-simple)>
	<!ELEMENT Conditionnel (présent)>
	<!ELEMENT Subjonctif (présent, imparfait)>
	<!ELEMENT Imperatif (imperatif-présent)>
	<!ELEMENT Participe (participe-présent, participe-passé)>

	<!ELEMENT infinitif-présent (p)>
	<!ELEMENT présent (p, p, p, p, p, p)>
	<!ELEMENT imparfait (p, p, p, p, p, p)>
	<!ELEMENT futur-simple (p, p, p, p, p, p)>
	<!ELEMENT passé-simple (p, p, p, p, p, p)>
	<!ELEMENT imperatif-présent (p, p, p)>
	<!ELEMENT participe-présent (p)>
	<!ELEMENT participe-passé (p, p, p, p)>

	<!ELEMENT p (i*)>
	<!ELEMENT i (#PCDATA)>
]>

<conjugation-fr>

<template name="pla:cer">
	<Infinitif>
		<infinitif-présent>
			<p><i>cer</i></p>
		</infinitif-présent>
	</Infinitif>
	<Indicatif>
		<présent>
			<p><i>ce</i></p>
			<p><i>ces</i></p>
			<p><i>ce</i></p>
			<p><i>çons</i></p>
			<p><i>cez</i></p>
			<p><i>cent</i></p>
		</présent>
		<imparfait>
			<p><i>çais</i></p>
			<p><i>çais</i></p>
			<p><i>çait</i></p>
			<p><i>cions</i></p>
			<p><i>ciez</i></p>
			<p><i>çaient</i></p>
		</imparfait>
		<futur-simple>
			<p><i>cerai</i></p>
			<p><i>ceras</i></p>
			<p><i>cera</i></p>
			<p><i>cerons</i></p>
			<p><i>cerez</i></p>
			<p><i>ceront</i></p>
		</futur-simple>
		<passé-simple>
			<p><i>çai</i></p>
			<p><i>ças</i></p>
			<p><i>ça</i></p>
			<p><i>çâmes</i></p>
			<p><i>çâtes</i></p>
			<p><i>cèrent</i></p>
		</passé-simple>
	</Indicatif>
	<Conditionnel>
		<présent>
			<p><i>cerais</i></p>
			<p><i>cerais</i></p>
			<p><i>cerait</i></p>
			<p><i>cerions</i></p>
			<p><i>ceriez</i></p>
			<p><i>ceraient</i></p>
		</présent>
	</Conditionnel>
	<Subjonctif>
		<présent>
			<p><i>ce</i></p>
			<p><i>ces</i></p>
			<p><i>ce</i></p>
			<p><i>cions</i></p>
			<p><i>ciez</i></p>
			<p><i>cent</i></p>
		</présent>
		<imparfait>
			<p><i>çasse</i></p>
			<p><i>çasses</i></p>
			<p><i>çât</i></p>
			<p><i>çassions</i></p>
			<p><i>çassiez</i></p>
			<p><i>çassent</i></p>
		</imparfait>
	</Subjonctif>
	<Imperatif>
		<imperatif-présent>
			<p><i>ce</i></p>
			<p><i>çons</i></p>
			<p><i>cez</i></p>
		</imperatif-présent>
	</Imperatif>
	<Participe>
		<participe-présent>
			<p><i>çant</i></p>
		</participe-présent>
		<participe-passé>
			<p><i>cé</i></p>
			<p><i>cés</i></p>
			<p><i>cée</i></p>
			<p><i>cées</i></p>
		</participe-passé>
	</Participe>
</template>

<template name="référenci:er">
	<Infinitif>
		<infinitif-présent>
			<p><i>er</i></p>
		</infinitif-présent>
	</Infinitif>
	<Indicatif>
		<présent>
			<p><i>e</i></p>
			<p><i>es</i></p>
			<p><i>e</i></p>
			<p><i>ons</i></p>
			<p><i>ez</i></p>
			<p><i>ent</i></p>
		</présent>
		<imparfait>
			<p><i>ais</i></p>
			<p><i>ais</i></p>
			<p><i>ait</i></p>
			<p><i>ons</i></p>
			<p><i>ez</i></p>
			<p><i>aient</i></p>
		</imparfait>
		<futur-simple>
			<p><i>erai</i></p>
			<p><i>eras</i></p>
			<p><i>era</i></p>
			<p><i>erons</i></p>
			<p><i>erez</i></p>
			<p><i>eront</i></p>
		</futur-simple>
		<passé-simple>
			<p><i>ai</i></p>
			<p><i>as</i></p>
			<p><i>a</i></p>
			<p><i>âmes</i></p>
			<p><i>âtes</i></p>
			<p><i>èrent</i></p>
		</passé-simple>
	</Indicatif>
	<Conditionnel>
		<présent>
			<p><i>erais</i></p>
			<p><i>erais</i></p>
			<p><i>erait</i></p>
			<p><i>erions</i></p>
			<p><i>eriez</i></p>
			<p><i>eraient</i></p>
		</présent>
	</Conditionnel>
	<Subjonctif>
		<présent>
			<p><i>e</i></p>
			<p><i>es</i></p>
			<p><i>e</i></p>
			<p><i>ions</i></p>
			<p><i>iez</i></p>
			<p><i>ent</i></p>
		</présent>
		<imparfait>
			<p><i>asse</i></p>
			<p><i>asses</i></p>
			<p><i>ât</i></p>
			<p><i>assions</i></p>
			<p><i>assiez</i></p>
			<p><i>assent</i></p>
		</imparfait>
	</Subjonctif>
	<Imperatif>
		<imperatif-présent>
			<p><i>e</i></p>
			<p><i>ons</i></p>
			<p><i>ez</i></p>
		</imperatif-présent>
	</Imperatif>
	<Participe>
		<participe-présent>
			<p><i>ant</i></p>
		</participe-présent>
		<participe-passé>
			<p><i>é</i></p>
			<p><i>és</i></p>
			<p><i>ée</i></p>
			<p><i>ées</i></p>
		</participe-passé>
	</Participe>
</template>

<template name="dép:ecer">
	<Infinitif>
		<infinitif-présent>
			<p><i>ecer</i></p>
		</infinitif-présent>
	</Infinitif>
	<Indicatif>
		<présent>
			<p><i>ece</i><i>èce</i></p>
			<p><i>eces</i><i>èces</i></p>
			<p><i>ece</i><i>èce</i></p>
			<p><i>eçons</i></p>
			<p><i>ecez</i></p>
			<p><i>ecent</i><i>ècent</i></p>
		</présent>
		<imparfait>
			<p><i>eçais</i></p>
			<p><i>eçais</i></p>
			<p><i>eçait</i></p>
			<p><i>ecions</i></p>
			<p><i>eciez</i></p>
			<p><i>eçaient</i></p>
		</imparfait>
		<futur-simple>
			<p><i>ecerai</i><i>ècerai</i></p>
			<p><i>eceras</i><i>èceras</i></p>
			<p><i>ecera</i><i>ècera</i></p>
			<p><i>ecerons</i><i>ècerons</i></p>
			<p><i>ecerez</i><i>ècerez</i></p>
			<p><i>eceront</i><i>èceront</i></p>
		</futur-simple>
		<passé-simple>
			<p><i>eçai</i></p>
			<p><i>eças</i></p>
			<p><i>eça</i></p>
			<p><i>eçâmes</i></p>
			<p><i>eçâtes</i></p>
			<p><i>ecèrent</i></p>
		</passé-simple>
	</Indicatif>
	<Conditionnel>
		<présent>
			<p><i>ecerais</i><i>ècerais</i></p>
			<p><i>ecerais</i><i>ècerais</i></p>
			<p><i>ecerait</i><i>ècerait</i></p>
			<p><i>ecerions</i><i>ècerions</i></p>
			<p><i>eceriez</i><i>èceriez</i></p>
			<p><i>eceraient</i><i>èceraient</i></p>
		</présent>
	</Conditionnel>
	<Subjonctif>
		<présent>
			<p><i>ece</i><i>èce</i></p>
			<p><i>eces</i><i>èces</i></p>
			<p><i>ece</i><i>èce</i></p>
			<p><i>ecions</i></p>
			<p><i>eciez</i></p>
			<p><i>ecent</i><i>ècent</i></p>
		</présent>
		<imparfait>
			<p><i>eçasse</i></p>
			<p><i>eçasses</i></p>
			<p><i>eçât</i></p>
			<p><i>eçassions</i></p>
			<p><i>eçassiez</i></p>
			<p><i>eçassent</i></p>
		</imparfait>
	</Subjonctif>
	<Imperatif>
		<imperatif-présent>
			<p><i>ece</i><i>èce</i></p>
			<p><i>eçons</i></p>
			<p><i>ecez</i></p>
		</imperatif-présent>
	</Imperatif>
	<Participe>
		<participe-présent>
			<p><i>eçant</i></p>
		</participe-présent>
		<participe-passé>
			<p><i>ecé</i></p>
			<p><i>ecés</i></p>
			<p><i>ecée</i></p>
			<p><i>ecées</i></p>
		</participe-passé>
	</Participe>
</template>

<template name="man:ger">
	<Infinitif>
		<infinitif-présent>
			<p><i>ger</i></p>
		</infinitif-présent>
	</Infinitif>
	<Indicatif>
		<présent>
			<p><i>ge</i></p>
			<p><i>ges</i></p>
			<p><i>ge</i></p>
			<p><i>geons</i></p>
			<p><i>gez</i></p>
			<p><i>gent</i></p>
		</présent>
		<imparfait>
			<p><i>geais</i></p>
			<p><i>geais</i></p>
			<p><i>geait</i></p>
			<p><i>gions</i></p>
			<p><i>giez</i></p>
			<p><i>geaient</i></p>
		</imparfait>
		<futur-simple>
			<p><i>gerai</i></p>
			<p><i>geras</i></p>
			<p><i>gera</i></p>
			<p><i>gerons</i></p>
			<p><i>gerez</i></p>
			<p><i>geront</i></p>
		</futur-simple>
		<passé-simple>
			<p><i>geai</i></p>
			<p><i>geas</i></p>
			<p><i>gea</i></p>
			<p><i>geâmes</i></p>
			<p><i>geâtes</i></p>
			<p><i>gèrent</i></p>
		</passé-simple>
	</Indicatif>
	<Conditionnel>
		<présent>
			<p><i>gerais</i></p>
			<p><i>gerais</i></p>
			<p><i>gerait</i></p>
			<p><i>gerions</i></p>
			<p><i>geriez</i></p>
			<p><i>geraient</i></p>
		</présent>
	</Conditionnel>
	<Subjonctif>
		<présent>
			<p><i>ge</i></p>
			<p><i>ges</i></p>
			<p><i>ge</i></p>
			<p><i>gions</i></p>
			<p><i>giez</i></p>
			<p><i>gent</i></p>
		</présent>
		<imparfait>
			<p><i>geasse</i></p>
			<p><i>geasses</i></p>
			<p><i>geât</i></p>
			<p><i>geassions</i></p>
			<p><i>geassiez</i></p>
			<p><i>geassent</i></p>
		</imparfait>
	</Subjonctif>
	<Imperatif>
		<imperatif-présent>
			<p><i>ge</i></p>
			<p><i>geons</i></p>
			<p><i>gez</i></p>
		</imperatif-présent>
	</Imperatif>
	<Participe>
		<participe-présent>
			<p><i>geant</i></p>
		</participe-présent>
		<participe-passé>
			<p><i>gé</i></p>
			<p><i>gés</i></p>
			<p><i>gée</i></p>
			<p><i>gées</i></p>
		</participe-passé>
	</Participe>
</template>

<template name="nei:ger">
	<Infinitif>
		<infinitif-présent>
			<p><i>ger</i></p>
		</infinitif-présent>
	</Infinitif>
	<Indicatif>
		<présent>
			<p></p>
			<p></p>
			<p><i>ge</i></p>
			<p></p>
			<p></p>
			<p></p>
		</présent>
		<imparfait>
			<p></p>
			<p></p>
			<p><i>geait</i></p>
			<p></p>
			<p></p>
			<p></p>
		</imparfait>
		<futur-simple>
			<p></p>
			<p></p>
			<p><i>gera</i></p>
			<p></p>
			<p></p>
			<p></p>
		</futur-simple>
		<passé-simple>
			<p></p>
			<p></p>
			<p><i>gea</i></p>
			<p></p>
			<p></p>
			<p></p>
		</passé-simple>
	</Indicatif>
	<Conditionnel>
		<présent>
			<p></p>
			<p></p>
			<p><i>gerait</i></p>
			<p></p>
			<p></p>
			<p></p>
		</présent>
	</Conditionnel>
	<Subjonctif>
		<présent>
			<p></p>
			<p></p>
			<p><i>ge</i></p>
			<p></p>
			<p></p>
			<p></p>
		</présent>
		<imparfait>
			<p></p>
			<p></p>
			<p><i>geât</i></p>
			<p></p>
			<p></p>
			<p></p>
		</imparfait>
	</Subjonctif>
	<Imperatif>
		<imperatif-présent>
			<p></p>
			<p></p>
			<p></p>
		</imperatif-présent>
	</Imperatif>
	<Participe>
		<participe-présent>
			<p><i>geant</i></p>
		</participe-présent>
		<participe-passé>
			<p><i>gé</i></p>
			<p><i>gés</i></p>
			<p><i>gée</i></p>
			<p><i>gées</i></p>
		</participe-passé>
	</Participe>
</template>

<template name="pa:yer">
	<Infinitif>
		<infinitif-présent>
			<p><i>yer</i></p>
		</infinitif-présent>
	</Infinitif>
	<Indicatif>
		<présent>
			<p><i>ie</i><i>ye</i></p>
			<p><i>ies</i><i>yes</i></p>
			<p><i>ie</i><i>ye</i></p>
			<p><i>yons</i></p>
			<p><i>yez</i></p>
			<p><i>ient</i><i>yent</i></p>
		</présent>
		<imparfait>
			<p><i>yais</i></p>
			<p><i>yais</i></p>
			<p><i>yait</i></p>
			<p><i>yions</i></p>
			<p><i>yiez</i></p>
			<p><i>yaient</i></p>
		</imparfait>
		<futur-simple>
			<p><i>ierai</i><i>yerai</i></p>
			<p><i>ieras</i><i>yeras</i></p>
			<p><i>iera</i><i>yera</i></p>
			<p><i>ierons</i><i>yerons</i></p>
			<p><i>ierez</i><i>yerez</i></p>
			<p><i>ieront</i><i>yeront</i></p>
		</futur-simple>
		<passé-simple>
			<p><i>yai</i></p>
			<p><i>yas</i></p>
			<p><i>ya</i></p>
			<p><i>yâmes</i></p>
			<p><i>yâtes</i></p>
			<p><i>yèrent</i></p>
		</passé-simple>
	</Indicatif>
	<Conditionnel>
		<présent>
			<p><i>ierais</i><i>yerais</i></p>
			<p><i>ierais</i><i>yerais</i></p>
			<p><i>ierait</i><i>yerait</i></p>
			<p><i>ierions</i><i>yerions</i></p>
			<p><i>ieriez</i><i>yeriez</i></p>
			<p><i>ieraient</i><i>yeraient</i></p>
		</présent>
	</Conditionnel>
	<Subjonctif>
		<présent>
			<p><i>ie</i><i>ye</i></p>
			<p><i>ies</i><i>yes</i></p>
			<p><i>ie</i><i>ye</i></p>
			<p><i>yions</i></p>
			<p><i>yiez</i></p>
			<p><i>ient</i><i>yent</i></p>
		</présent>
		<imparfait>
			<p><i>yasse</i></p>
			<p><i>yasses</i></p>
			<p><i>yât</i></p>
			<p><i>yassions</i></p>
			<p><i>yassiez</i></p>
			<p><i>yassent</i></p>
		</imparfait>
	</Subjonctif>
	<Imperatif>
		<imperatif-présent>
			<p><i>ie</i><i>ye</i></p>
			<p><i>yons</i></p>
			<p><i>yez</i></p>
		</imperatif-présent>
	</Imperatif>
	<Participe>
		<participe-présent>
			<p><i>yant</i></p>
		</participe-présent>
		<participe-passé>
			<p><i>yé</i></p>
			<p><i>yés</i></p>
			<p><i>yée</i></p>
			<p><i>yées</i></p>
		</participe-passé>
	</Participe>
</template>

<template name="netto:yer">
	<Infinitif>
		<infinitif-présent>
			<p><i>yer</i></p>
		</infinitif-présent>
	</Infinitif>
	<Indicatif>
		<présent>
			<p><i>ie</i></p>
			<p><i>ies</i></p>
			<p><i>ie</i></p>
			<p><i>yons</i></p>
			<p><i>yez</i></p>
			<p><i>ient</i></p>
		</présent>
		<imparfait>
			<p><i>yais</i></p>
			<p><i>yais</i></p>
			<p><i>yait</i></p>
			<p><i>yions</i></p>
			<p><i>yiez</i></p>
			<p><i>yaient</i></p>
		</imparfait>
		<futur-simple>
			<p><i>ierai</i></p>
			<p><i>ieras</i></p>
			<p><i>iera</i></p>
			<p><i>ierons</i></p>
			<p><i>ierez</i></p>
			<p><i>ieront</i></p>
		</futur-simple>
		<passé-simple>
			<p><i>yai</i></p>
			<p><i>yas</i></p>
			<p><i>ya</i></p>
			<p><i>yâmes</i></p>
			<p><i>yâtes</i></p>
			<p><i>yèrent</i></p>
		</passé-simple>
	</Indicatif>
	<Conditionnel>
		<présent>
			<p><i>ierais</i></p>
			<p><i>ierais</i></p>
			<p><i>ierait</i></p>
			<p><i>ierions</i></p>
			<p><i>ieriez</i></p>
			<p><i>ieraient</i></p>
		</présent>
	</Conditionnel>
	<Subjonctif>
		<présent>
			<p><i>ie</i></p>
			<p><i>ies</i></p>
			<p><i>ie</i></p>
			<p><i>yions</i></p>
			<p><i>yiez</i></p>
			<p><i>ient</i></p>
		</présent>
		<imparfait>
			<p><i>yasse</i></p>
			<p><i>yasses</i></p>
			<p><i>yât</i></p>
			<p><i>yassions</i></p>
			<p><i>yassiez</i></p>
			<p><i>yassent</i></p>
		</imparfait>
	</Subjonctif>
	<Imperatif>
		<imperatif-présent>
			<p><i>ie</i></p>
			<p><i>yons</i></p>
			<p><i>yez</i></p>
		</imperatif-présent>
	</Imperatif>
	<Participe>
		<participe-présent>
			<p><i>yant</i></p>
		</participe-présent>
		<participe-passé>
			<p><i>yé</i></p>
			<p><i>yés</i></p>
			<p><i>yée</i></p>
			<p><i>yées</i></p>
		</participe-passé>
	</Participe>
</template>

<template name="grasse:yer">
	<Infinitif>
		<infinitif-présent>
			<p><i>yer</i></p>
		</infinitif-présent>
	</Infinitif>
	<Indicatif>
		<présent>
			<p><i>ye</i></p>
			<p><i>yes</i></p>
			<p><i>ye</i></p>
			<p><i>yons</i></p>
			<p><i>yez</i></p>
			<p><i>yent</i></p>
		</présent>
		<imparfait>
			<p><i>yais</i></p>
			<p><i>yais</i></p>
			<p><i>yait</i></p>
			<p><i>yions</i></p>
			<p><i>yiez</i></p>
			<p><i>yaient</i></p>
		</imparfait>
		<futur-simple>
			<p><i>yerai</i></p>
			<p><i>yeras</i></p>
			<p><i>yera</i></p>
			<p><i>yerons</i></p>
			<p><i>yerez</i></p>
			<p><i>yeront</i></p>
		</futur-simple>
		<passé-simple>
			<p><i>yai</i></p>
			<p><i>yas</i></p>
			<p><i>ya</i></p>
			<p><i>yâmes</i></p>
			<p><i>yâtes</i></p>
			<p><i>yèrent</i></p>
		</passé-simple>
	</Indicatif>
	<Conditionnel>
		<présent>
			<p><i>yerais</i></p>
			<p><i>yerais</i></p>
			<p><i>yerait</i></p>
			<p><i>yerions</i></p>
			<p><i>yeriez</i></p>
			<p><i>yeraient</i></p>
		</présent>
	</Conditionnel>
	<Subjonctif>
		<présent>
			<p><i>ye</i></p>
			<p><i>yes</i></p>
			<p><i>ye</i></p>
			<p><i>yions</i></p>
			<p><i>yiez</i></p>
			<p><i>yent</i></p>
		</présent>
		<imparfait>
			<p><i>yasse</i></p>
			<p><i>yasses</i></p>
			<p><i>yât</i></p>
			<p><i>yassions</i></p>
			<p><i>yassiez</i></p>
			<p><i>yassent</i></p>
		</imparfait>
	</Subjonctif>
	<Imperatif>
		<imperatif-présent>
			<p><i>ye</i></p>
			<p><i>yons</i></p>
			<p><i>yez</i></p>
		</imperatif-présent>
	</Imperatif>
	<Participe>
		<participe-présent>
			<p><i>yant</i></p>
		</participe-présent>
		<participe-passé>
			<p><i>yé</i></p>
			<p><i>yés</i></p>
			<p><i>yée</i></p>
			<p><i>yées</i></p>
		</participe-passé>
	</Participe>
</template>

<template name="app:eler">
	<Infinitif>
		<infinitif-présent>
			<p><i>eler</i></p>
		</infinitif-présent>
	</Infinitif>
	<Indicatif>
		<présent>
			<p><i>elle</i></p>
			<p><i>elles</i></p>
			<p><i>elle</i></p>
			<p><i>elons</i></p>
			<p><i>elez</i></p>
			<p><i>ellent</i></p>
		</présent>
		<imparfait>
			<p><i>elais</i></p>
			<p><i>elais</i></p>
			<p><i>elait</i></p>
			<p><i>elions</i></p>
			<p><i>eliez</i></p>
			<p><i>elaient</i></p>
		</imparfait>
		<futur-simple>
			<p><i>ellerai</i></p>
			<p><i>elleras</i></p>
			<p><i>ellera</i></p>
			<p><i>ellerons</i></p>
			<p><i>ellerez</i></p>
			<p><i>elleront</i></p>
		</futur-simple>
		<passé-simple>
			<p><i>elai</i></p>
			<p><i>elas</i></p>
			<p><i>ela</i></p>
			<p><i>elâmes</i></p>
			<p><i>elâtes</i></p>
			<p><i>elèrent</i></p>
		</passé-simple>
	</Indicatif>
	<Conditionnel>
		<présent>
			<p><i>ellerais</i></p>
			<p><i>ellerais</i></p>
			<p><i>ellerait</i></p>
			<p><i>ellerions</i></p>
			<p><i>elleriez</i></p>
			<p><i>elleraient</i></p>
		</présent>
	</Conditionnel>
	<Subjonctif>
		<présent>
			<p><i>elle</i></p>
			<p><i>elles</i></p>
			<p><i>elle</i></p>
			<p><i>elions</i></p>
			<p><i>eliez</i></p>
			<p><i>ellent</i></p>
		</présent>
		<imparfait>
			<p><i>elasse</i></p>
			<p><i>elasses</i></p>
			<p><i>elât</i></p>
			<p><i>elassions</i></p>
			<p><i>elassiez</i></p>
			<p><i>elassent</i></p>
		</imparfait>
	</Subjonctif>
	<Imperatif>
		<imperatif-présent>
			<p><i>elle</i></p>
			<p><i>elons</i></p>
			<p><i>elez</i></p>
		</imperatif-présent>
	</Imperatif>
	<Participe>
		<participe-présent>
			<p><i>elant</i></p>
		</participe-présent>
		<participe-passé>
			<p><i>elé</i></p>
			<p><i>elés</i></p>
			<p><i>elée</i></p>
			<p><i>elées</i></p>
		</participe-passé>
	</Participe>
</template>

<template name="p:eler">
	<Infinitif>
		<infinitif-présent>
			<p><i>eler</i></p>
		</infinitif-présent>
	</Infinitif>
	<Indicatif>
		<présent>
			<p><i>èle</i></p>
			<p><i>èles</i></p>
			<p><i>èle</i></p>
			<p><i>elons</i></p>
			<p><i>elez</i></p>
			<p><i>èlent</i></p>
		</présent>
		<imparfait>
			<p><i>elais</i></p>
			<p><i>elais</i></p>
			<p><i>elait</i></p>
			<p><i>elions</i></p>
			<p><i>eliez</i></p>
			<p><i>elaient</i></p>
		</imparfait>
		<futur-simple>
			<p><i>èlerai</i></p>
			<p><i>èleras</i></p>
			<p><i>èlera</i></p>
			<p><i>èlerons</i></p>
			<p><i>èlerez</i></p>
			<p><i>èleront</i></p>
		</futur-simple>
		<passé-simple>
			<p><i>elai</i></p>
			<p><i>elas</i></p>
			<p><i>ela</i></p>
			<p><i>elâmes</i></p>
			<p><i>elâtes</i></p>
			<p><i>elèrent</i></p>
		</passé-simple>
	</Indicatif>
	<Conditionnel>
		<présent>
			<p><i>èlerais</i></p>
			<p><i>èlerais</i></p>
			<p><i>èlerait</i></p>
			<p><i>èlerions</i></p>
			<p><i>èleriez</i></p>
			<p><i>èleraient</i></p>
		</présent>
	</Conditionnel>
	<Subjonctif>
		<présent>
			<p><i>èle</i></p>
			<p><i>èles</i></p>
			<p><i>èle</i></p>
			<p><i>elions</i></p>
			<p><i>eliez</i></p>
			<p><i>èlent</i></p>
		</présent>
		<imparfait>
			<p><i>elasse</i></p>
			<p><i>elasses</i></p>
			<p><i>elât</i></p>
			<p><i>elassions</i></p>
			<p><i>elassiez</i></p>
			<p><i>elassent</i></p>
		</imparfait>
	</Subjonctif>
	<Imperatif>
		<imperatif-présent>
			<p><i>èle</i></p>
			<p><i>elons</i></p>
			<p><i>elez</i></p>
		</imperatif-présent>
	</Imperatif>
	<Participe>
		<participe-présent>
			<p><i>elant</i></p>
		</participe-présent>
		<participe-passé>
			<p><i>elé</i></p>
			<p><i>elés</i></p>
			<p><i>elée</i></p>
			<p><i>elées</i></p>
		</participe-passé>
	</Participe>
</template>

<template name="harc:eler">
	<Infinitif>
		<infinitif-présent>
			<p><i>eler</i></p>
		</infinitif-présent>
	</Infinitif>
	<Indicatif>
		<présent>
			<p><i>elle</i><i>èle</i></p>
			<p><i>elles</i><i>èles</i></p>
			<p><i>elle</i><i>èle</i></p>
			<p><i>elons</i></p>
			<p><i>elez</i></p>
			<p><i>ellent</i><i>èlent</i></p>
		</présent>
		<imparfait>
			<p><i>elais</i></p>
			<p><i>elais</i></p>
			<p><i>elait</i></p>
			<p><i>elions</i></p>
			<p><i>eliez</i></p>
			<p><i>elaient</i></p>
		</imparfait>
		<futur-simple>
			<p><i>ellerai</i><i>èlerai</i></p>
			<p><i>elleras</i><i>èleras</i></p>
			<p><i>ellera</i><i>èlera</i></p>
			<p><i>ellerons</i><i>èlerons</i></p>
			<p><i>ellerez</i><i>èlerez</i></p>
			<p><i>elleront</i><i>èleront</i></p>
		</futur-simple>
		<passé-simple>
			<p><i>elai</i></p>
			<p><i>elas</i></p>
			<p><i>ela</i></p>
			<p><i>elâmes</i></p>
			<p><i>elâtes</i></p>
			<p><i>elèrent</i></p>
		</passé-simple>
	</Indicatif>
	<Conditionnel>
		<présent>
			<p><i>ellerais</i><i>èlerais</i></p>
			<p><i>ellerais</i><i>èlerais</i></p>
			<p><i>ellerait</i><i>èlerait</i></p>
			<p><i>ellerions</i><i>èlerions</i></p>
			<p><i>elleriez</i><i>èleriez</i></p>
			<p><i>elleraient</i><i>èleraient</i></p>
		</présent>
	</Conditionnel>
	<Subjonctif>
		<présent>
			<p><i>elle</i><i>èle</i></p>
			<p><i>elles</i><i>èles</i></p>
			<p><i>elle</i><i>èle</i></p>
			<p><i>elions</i></p>
			<p><i>eliez</i></p>
			<p><i>ellent</i><i>èlent</i></p>
		</présent>
		<imparfait>
			<p><i>elasse</i></p>
			<p><i>elasses</i></p>
			<p><i>elât</i></p>
			<p><i>elassions</i></p>
			<p><i>elassiez</i></p>
			<p><i>elassent</i></p>
		</imparfait>
	</Subjonctif>
	<Imperatif>
		<imperatif-présent>
			<p><i>elle</i><i>èle</i></p>
			<p><i>elons</i></p>
			<p><i>elez</i></p>
		</imperatif-présent>
	</Imperatif>
	<Participe>
		<participe-présent>
			<p><i>elant</i></p>
		</participe-présent>
		<participe-passé>
			<p><i>elé</i></p>
			<p><i>elés</i></p>
			<p><i>elée</i></p>
			<p><i>elées</i></p>
		</participe-passé>
	</Participe>
</template>

<template name="j:eter">
	<Infinitif>
		<infinitif-présent>
			<p><i>eter</i></p>
		</infinitif-présent>
	</Infinitif>
	<Indicatif>
		<présent>
			<p><i>ette</i></p>
			<p><i>ettes</i></p>
			<p><i>ette</i></p>
			<p><i>etons</i></p>
			<p><i>etez</i></p>
			<p><i>ettent</i></p>
		</présent>
		<imparfait>
			<p><i>etais</i></p>
			<p><i>etais</i></p>
			<p><i>etait</i></p>
			<p><i>etions</i></p>
			<p><i>etiez</i></p>
			<p><i>etaient</i></p>
		</imparfait>
		<futur-simple>
			<p><i>etterai</i></p>
			<p><i>etteras</i></p>
			<p><i>ettera</i></p>
			<p><i>etterons</i></p>
			<p><i>etterez</i></p>
			<p><i>etteront</i></p>
		</futur-simple>
		<passé-simple>
			<p><i>etai</i></p>
			<p><i>etas</i></p>
			<p><i>eta</i></p>
			<p><i>etâmes</i></p>
			<p><i>etâtes</i></p>
			<p><i>etèrent</i></p>
		</passé-simple>
	</Indicatif>
	<Conditionnel>
		<présent>
			<p><i>etterais</i></p>
			<p><i>etterais</i></p>
			<p><i>etterait</i></p>
			<p><i>etterions</i></p>
			<p><i>etteriez</i></p>
			<p><i>etteraient</i></p>
		</présent>
	</Conditionnel>
	<Subjonctif>
		<présent>
			<p><i>ette</i></p>
			<p><i>ettes</i></p>
			<p><i>ette</i></p>
			<p><i>etions</i></p>
			<p><i>etiez</i></p>
			<p><i>ettent</i></p>
		</présent>
		<imparfait>
			<p><i>etasse</i></p>
			<p><i>etasses</i></p>
			<p><i>etât</i></p>
			<p><i>etassions</i></p>
			<p><i>etassiez</i></p>
			<p><i>etassent</i></p>
		</imparfait>
	</Subjonctif>
	<Imperatif>
		<imperatif-présent>
			<p><i>ette</i></p>
			<p><i>etons</i></p>
			<p><i>etez</i></p>
		</imperatif-présent>
	</Imperatif>
	<Participe>
		<participe-présent>
			<p><i>etant</i></p>
		</participe-présent>
		<participe-passé>
			<p><i>eté</i></p>
			<p><i>etés</i></p>
			<p><i>etée</i></p>
			<p><i>etées</i></p>
		</participe-passé>
	</Participe>
</template>

<template name="ach:eter">
	<Infinitif>
		<infinitif-présent>
			<p><i>eter</i></p>
		</infinitif-présent>
	</Infinitif>
	<Indicatif>
		<présent>
			<p><i>ète</i></p>
			<p><i>ètes</i></p>
			<p><i>ète</i></p>
			<p><i>etons</i></p>
			<p><i>etez</i></p>
			<p><i>ètent</i></p>
		</présent>
		<imparfait>
			<p><i>etais</i></p>
			<p><i>etais</i></p>
			<p><i>etait</i></p>
			<p><i>etions</i></p>
			<p><i>etiez</i></p>
			<p><i>etaient</i></p>
		</imparfait>
		<futur-simple>
			<p><i>èterai</i></p>
			<p><i>èteras</i></p>
			<p><i>ètera</i></p>
			<p><i>èterons</i></p>
			<p><i>èterez</i></p>
			<p><i>èteront</i></p>
		</futur-simple>
		<passé-simple>
			<p><i>etai</i></p>
			<p><i>etas</i></p>
			<p><i>eta</i></p>
			<p><i>etâmes</i></p>
			<p><i>etâtes</i></p>
			<p><i>etèrent</i></p>
		</passé-simple>
	</Indicatif>
	<Conditionnel>
		<présent>
			<p><i>èterais</i></p>
			<p><i>èterais</i></p>
			<p><i>èterait</i></p>
			<p><i>èterions</i></p>
			<p><i>èteriez</i></p>
			<p><i>èteraient</i></p>
		</présent>
	</Conditionnel>
	<Subjonctif>
		<présent>
			<p><i>ète</i></p>
			<p><i>ètes</i></p>
			<p><i>ète</i></p>
			<p><i>etions</i></p>
			<p><i>etiez</i></p>
			<p><i>ètent</i></p>
		</présent>
		<imparfait>
			<p><i>etasse</i></p>
			<p><i>etasses</i></p>
			<p><i>etât</i></p>
			<p><i>etassions</i></p>
			<p><i>etassiez</i></p>
			<p><i>etassent</i></p>
		</imparfait>
	</Subjonctif>
	<Imperatif>
		<imperatif-présent>
			<p><i>ète</i></p>
			<p><i>etons</i></p>
			<p><i>etez</i></p>
		</imperatif-présent>
	</Imperatif>
	<Participe>
		<participe-présent>
			<p><i>etant</i></p>
		</participe-présent>
		<participe-passé>
			<p><i>eté</i></p>
			<p><i>etés</i></p>
			<p><i>etée</i></p>
			<p><i>etées</i></p>
		</participe-passé>
	</Participe>
</template>

<template name="héb:éter">
	<Infinitif>
		<infinitif-présent>
			<p><i>éter</i></p>
		</infinitif-présent>
	</Infinitif>
	<Indicatif>
		<présent>
			<p><i>ète</i></p>
			<p><i>ètes</i></p>
			<p><i>ète</i></p>
			<p><i>étons</i></p>
			<p><i>étez</i></p>
			<p><i>ètent</i></p>
		</présent>
		<imparfait>
			<p><i>étais</i></p>
			<p><i>étais</i></p>
			<p><i>était</i></p>
			<p><i>étions</i></p>
			<p><i>étiez</i></p>
			<p><i>étaient</i></p>
		</imparfait>
		<futur-simple>
			<p><i>èterai</i></p>
			<p><i>èteras</i></p>
			<p><i>ètera</i></p>
			<p><i>èterons</i></p>
			<p><i>èterez</i></p>
			<p><i>èteront</i></p>
		</futur-simple>
		<passé-simple>
			<p><i>étai</i></p>
			<p><i>étas</i></p>
			<p><i>éta</i></p>
			<p><i>étâmes</i></p>
			<p><i>étâtes</i></p>
			<p><i>étèrent</i></p>
		</passé-simple>
	</Indicatif>
	<Conditionnel>
		<présent>
			<p><i>èterais</i></p>
			<p><i>èterais</i></p>
			<p><i>èterait</i></p>
			<p><i>èterions</i></p>
			<p><i>èteriez</i></p>
			<p><i>èteraient</i></p>
		</présent>
	</Conditionnel>
	<Subjonctif>
		<présent>
			<p><i>ète</i></p>
			<p><i>ètes</i></p>
			<p><i>ète</i></p>
			<p><i>étions</i></p>
			<p><i>étiez</i></p>
			<p><i>ètent</i></p>
		</présent>
		<imparfait>
			<p><i>étasse</i></p>
			<p><i>étasses</i></p>
			<p><i>étât</i></p>
			<p><i>étassions</i></p>
			<p><i>étassiez</i></p>
			<p><i>étassent</i></p>
		</imparfait>
	</Subjonctif>
	<Imperatif>
		<imperatif-présent>
			<p><i>ète</i></p>
			<p><i>étons</i></p>
			<p><i>étez</i></p>
		</imperatif-présent>
	</Imperatif>
	<Participe>
		<participe-présent>
			<p><i>étant</i></p>
		</participe-présent>
		<participe-passé>
			<p><i>été</i></p>
			<p><i>étés</i></p>
			<p><i>étée</i></p>
			<p><i>étées</i></p>
		</participe-passé>
	</Participe>
</template>

<template name="s:emer">
	<Infinitif>
		<infinitif-présent>
			<p><i>emer</i></p>
		</infinitif-présent>
	</Infinitif>
	<Indicatif>
		<présent>
			<p><i>ème</i></p>
			<p><i>èmes</i></p>
			<p><i>ème</i></p>
			<p><i>emons</i></p>
			<p><i>emez</i></p>
			<p><i>èment</i></p>
		</présent>
		<imparfait>
			<p><i>emais</i></p>
			<p><i>emais</i></p>
			<p><i>emait</i></p>
			<p><i>emions</i></p>
			<p><i>emiez</i></p>
			<p><i>emaient</i></p>
		</imparfait>
		<futur-simple>
			<p><i>èmerai</i></p>
			<p><i>èmeras</i></p>
			<p><i>èmera</i></p>
			<p><i>èmerons</i></p>
			<p><i>èmerez</i></p>
			<p><i>èmeront</i></p>
		</futur-simple>
		<passé-simple>
			<p><i>emai</i></p>
			<p><i>emas</i></p>
			<p><i>ema</i></p>
			<p><i>emâmes</i></p>
			<p><i>emâtes</i></p>
			<p><i>emèrent</i></p>
		</passé-simple>
	</Indicatif>
	<Conditionnel>
		<présent>
			<p><i>èmerais</i></p>
			<p><i>èmerais</i></p>
			<p><i>èmerait</i></p>
			<p><i>èmerions</i></p>
			<p><i>èmeriez</i></p>
			<p><i>èmeraient</i></p>
		</présent>
	</Conditionnel>
	<Subjonctif>
		<présent>
			<p><i>ème</i></p>
			<p><i>èmes</i></p>
			<p><i>ème</i></p>
			<p><i>emions</i></p>
			<p><i>emiez</i></p>
			<p><i>èment</i></p>
		</présent>
		<imparfait>
			<p><i>emasse</i></p>
			<p><i>emasses</i></p>
			<p><i>emât</i></p>
			<p><i>emassions</i></p>
			<p><i>emassiez</i></p>
			<p><i>emassent</i></p>
		</imparfait>
	</Subjonctif>
	<Imperatif>
		<imperatif-présent>
			<p><i>ème</i></p>
			<p><i>emons</i></p>
			<p><i>emez</i></p>
		</imperatif-présent>
	</Imperatif>
	<Participe>
		<participe-présent>
			<p><i>emant</i></p>
		</participe-présent>
		<participe-passé>
			<p><i>emé</i></p>
			<p><i>emés</i></p>
			<p><i>emée</i></p>
			<p><i>emées</i></p>
		</participe-passé>
	</Participe>
</template>

<template name="l:éguer">
	<Infinitif>
		<infinitif-présent>
			<p><i>éguer</i></p>
		</infinitif-présent>
	</Infinitif>
	<Indicatif>
		<présent>
			<p><i>ègue</i></p>
			<p><i>ègues</i></p>
			<p><i>ègue</i></p>
			<p><i>éguons</i></p>
			<p><i>éguez</i></p>
			<p><i>èguent</i></p>
		</présent>
		<imparfait>
			<p><i>éguais</i></p>
			<p><i>éguais</i></p>
			<p><i>éguait</i></p>
			<p><i>éguions</i></p>
			<p><i>éguiez</i></p>
			<p><i>éguaient</i></p>
		</imparfait>
		<futur-simple>
			<p><i>èguerai</i></p>
			<p><i>ègueras</i></p>
			<p><i>èguera</i></p>
			<p><i>èguerons</i></p>
			<p><i>èguerez</i></p>
			<p><i>ègueront</i></p>
		</futur-simple>
		<passé-simple>
			<p><i>éguai</i></p>
			<p><i>éguas</i></p>
			<p><i>égua</i></p>
			<p><i>éguâmes</i></p>
			<p><i>éguâtes</i></p>
			<p><i>éguèrent</i></p>
		</passé-simple>
	</Indicatif>
	<Conditionnel>
		<présent>
			<p><i>èguerais</i></p>
			<p><i>èguerais</i></p>
			<p><i>èguerait</i></p>
			<p><i>èguerions</i></p>
			<p><i>ègueriez</i></p>
			<p><i>ègueraient</i></p>
		</présent>
	</Conditionnel>
	<Subjonctif>
		<présent>
			<p><i>ègue</i></p>
			<p><i>ègues</i></p>
			<p><i>ègue</i></p>
			<p><i>éguions</i></p>
			<p><i>éguiez</i></p>
			<p><i>èguent</i></p>
		</présent>
		<imparfait>
			<p><i>éguasse</i></p>