<?xml version='1.0' encoding='utf-8'?>
<!--
	verbs-ro.xml - List of Romanian verbs with their conjugation template.
	The templates were generated by SekouD using Unsupervised Learning,
	and follow the xml schema defined by Pierre Sarrazin in conjug_manager.
	Further improved by Brett Tolbert:
	- Removed uncessary compound tenses, as they can be conjugated with 
	  only the helping verb and participle. 
	- Fixed some errors in the templates
	- Adding missing tenses, e.g. in the 'avea' template
	- Grouped prezent, imperfect and Perfectu-simplu under Indicativ mood
	- Removed mood name from tense names to eliminate redundancy
	- Converted tense tag names to lowercase for ease of use

	Coypright (C) 2019 Brett Tolbert <https://github.com/bretttolbert/verbecc>
	Copyright (C) 2018 SekouD <https://github.com/SekouD>
	Copyright (C) 2010 Pierre Sarrazin <http://sarrazip.com/>

	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with this program; if not, write to the Free Software
	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
	02110-1301, USA.
-->
<!DOCTYPE conjugation-ro [
<!ELEMENT conjugation-ro (template)+>
<!ATTLIST conjugation-ro xmlns CDATA #FIXED "">
<!ELEMENT template (Indicativ , Conjunctiv , Infinitiv , (Conditional , Imperativ , Gerunziu , Participiu)?)>
<!ATTLIST template xmlns CDATA #FIXED "">
<!ATTLIST template name NMTOKEN #REQUIRED>
<!ELEMENT Indicativ (prezent , imperfect , perfect-simplu , mai-mult-ca-perfect? , (viitor-2-popular)?)>
<!ATTLIST Indicativ xmlns CDATA #FIXED "">
<!ELEMENT Conjunctiv (prezent , perfect?)>
<!ATTLIST Conjunctiv xmlns CDATA #FIXED "">
<!ELEMENT Infinitiv (afirmativ)>
<!ATTLIST Infinitiv xmlns CDATA #FIXED "">
<!ELEMENT Conditional (prezent , perfect)>
<!ATTLIST Conditional xmlns CDATA #FIXED "">
<!ELEMENT Imperativ (imperativ , negativ)>
<!ATTLIST Imperativ xmlns CDATA #FIXED "">
<!ELEMENT Gerunziu (gerunziu)>
<!ATTLIST Gerunziu xmlns CDATA #FIXED "">
<!ELEMENT Participiu (participiu)>
<!ATTLIST Participiu xmlns CDATA #FIXED "">
<!ELEMENT prezent (p)+>
<!ATTLIST prezent xmlns CDATA #FIXED "">
<!ELEMENT imperfect (p)+>
<!ATTLIST imperfect xmlns CDATA #FIXED "">
<!ELEMENT afirmativ (p)>
<!ATTLIST afirmativ xmlns CDATA #FIXED "">
<!ELEMENT perfect-simplu (p)+>
<!ATTLIST perfect-simplu xmlns CDATA #FIXED "">
<!ELEMENT mai-mult-ca-perfect (p)+>
<!ATTLIST mai-mult-ca-perfect xmlns CDATA #FIXED "">
<!ELEMENT viitor-2-popular (p)+>
<!ATTLIST viitor-2-popular xmlns CDATA #FIXED "">
<!ELEMENT perfect (p)+>
<!ATTLIST perfect xmlns CDATA #FIXED "">
<!ELEMENT imperativ (p)+>
<!ATTLIST imperativ xmlns CDATA #FIXED "">
<!ELEMENT negativ (p)+>
<!ATTLIST negativ xmlns CDATA #FIXED "">
<!ELEMENT gerunziu (p)>
<!ATTLIST gerunziu xmlns CDATA #FIXED "">
<!ELEMENT participiu (p)>
<!ATTLIST participiu xmlns CDATA #FIXED "">
<!ELEMENT p (i)*>
<!ATTLIST p xmlns CDATA #FIXED "">
<!ELEMENT i (#PCDATA)>
<!ATTLIST i xmlns CDATA #FIXED "">
]>
<conjugation-ro>

<template name="a:vea">
	<Indicativ>
		<prezent>
			<p><i>m</i></p>
			<p><i>i</i></p>
			<p><i/></p>
			<p><i>m</i></p>
			<p><i>ţi</i></p>
			<p><i>u</i></p>
		</prezent>
		<imperfect>
			<p><i>veam</i></p>
			<p><i>veai</i></p>
			<p><i>vea</i></p>
			<p><i>veam</i></p>
			<p><i>veaţi</i></p>
			<p><i>veau</i></p>
		</imperfect>
		<perfect-simplu>
			<p><i>vui</i></p>
			<p><i>vuși</i></p>
			<p><i>vu</i></p>
			<p><i>vurăm</i></p>
			<p><i>vurăţi</i></p>
			<p><i>vură</i></p>
		</perfect-simplu>
		<mai-mult-ca-perfect>
			<p><i>vusem</i></p>
			<p><i>vuseși</i></p>
			<p><i>vuse</i></p>
			<p><i>vuserăm</i></p>
			<p><i>vuserăţi</i></p>
			<p><i>vuseră</i></p>
		</mai-mult-ca-perfect>
	</Indicativ>
	<Conjunctiv>
		<prezent>
			<p><i>ș</i></p>
			<p><i>i</i></p>
			<p><i>r</i></p>
			<p><i>m</i></p>
			<p><i>ţi</i></p>
			<p><i>r</i></p>
		</prezent>
	</Conjunctiv>
	<Infinitiv>
		<afirmativ>
			<p><i>vea</i></p>
		</afirmativ>
	</Infinitiv>
	<Conditional>
		<prezent>
			<p><i>vea</i></p>
			<p><i>vea</i></p>
			<p><i>vea</i></p>
			<p><i>vea</i></p>
			<p><i>vea</i></p>
			<p><i>vea</i></p>
		</prezent>
		<perfect>
			<p><i>vut</i></p>
			<p><i>vut</i></p>
			<p><i>vut</i></p>
			<p><i>vut</i></p>
			<p><i>vut</i></p>
			<p><i>vut</i></p>
		</perfect>
	</Conditional>
	<Imperativ>
		<imperativ>
			<p><i>ai</i></p>
			<p><i>eţi</i></p>
		</imperativ>
		<negativ>
			<p><i>ai</i></p>
			<p><i>eţi</i></p>
		</negativ>
	</Imperativ>
	<Gerunziu>
		<gerunziu>
			<p><i>vând</i></p>
		</gerunziu>
	</Gerunziu>
	<Participiu>
		<participiu>
			<p><i>vut</i></p>
		</participiu>
	</Participiu>
</template>

<template name="b:ea">
	<Indicativ>
		<prezent>
			<p><i>eau</i></p>
			<p><i>ei</i></p>
			<p><i>ea</i></p>
			<p><i>em</i></p>
			<p><i>eţi</i></p>
			<p><i>eau</i></p>
		</prezent>
		<imperfect>
			<p><i>eam</i></p>
			<p><i>eai</i></p>
			<p><i>ea</i></p>
			<p><i>eam</i></p>
			<p><i>eaţi</i></p>
			<p><i>eau</i></p>
		</imperfect>
		<perfect-simplu>
			<p><i>ăui</i></p>
			<p><i>ăuși</i></p>
			<p><i>ău</i></p>
			<p><i>ăurăm</i></p>
			<p><i>ăurăţi</i></p>
			<p><i>ăură</i></p>
		</perfect-simplu>
		<mai-mult-ca-perfect>
			<p><i>ăusem</i></p>
			<p><i>ăuseși</i></p>
			<p><i>ăuse</i></p>
			<p><i>ăuserăm</i></p>
			<p><i>ăuserăţi</i></p>
			<p><i>ăuseră</i></p>
		</mai-mult-ca-perfect>
		<viitor-2-popular>
			<p><i>eau</i></p>
			<p><i>ei</i></p>
			<p><i>eie</i></p>
			<p><i>em</i></p>
			<p><i>eţi</i></p>
			<p><i>eie</i></p>
		</viitor-2-popular>
	</Indicativ>
	<Conjunctiv>
		<prezent>
			<p><i>eau</i></p>
			<p><i>ei</i></p>
			<p><i>eie</i></p>
			<p><i>em</i></p>
			<p><i>eţi</i></p>
			<p><i>eie</i></p>
		</prezent>
		<perfect>
			<p><i>ăut</i></p>
			<p><i>ăut</i></p>
			<p><i>ăut</i></p>
			<p><i>ăut</i></p>
			<p><i>ăut</i></p>
			<p><i>ăut</i></p>
		</perfect>
	</Conjunctiv>
	<Infinitiv>
		<afirmativ>
			<p><i>ea</i></p>
		</afirmativ>
	</Infinitiv>
	<Conditional>
		<prezent>
			<p><i>ea</i></p>
			<p><i>ea</i></p>
			<p><i>ea</i></p>
			<p><i>ea</i></p>
			<p><i>ea</i></p>
			<p><i>ea</i></p>
		</prezent>
		<perfect>
			<p><i>ăut</i></p>
			<p><i>ăut</i></p>
			<p><i>ăut</i></p>
			<p><i>ăut</i></p>
			<p><i>ăut</i></p>
			<p><i>ăut</i></p>
		</perfect>
	</Conditional>
	<Imperativ>
		<imperativ>
			<p><i>ea</i></p>
			<p><i>eţi</i></p>
		</imperativ>
		<negativ>
			<p><i>ea</i></p>
			<p><i>eţi</i></p>
		</negativ>
	</Imperativ>
	<Gerunziu>
		<gerunziu>
			<p><i>ând</i></p>
		</gerunziu>
	</Gerunziu>
	<Participiu>
		<participiu>
			<p><i>ăut</i></p>
		</participiu>
	</Participiu>
</template>

<template name="ce:re">
	<Indicativ>
		<prezent>
			<p><i>r</i></p>
			<p><i>ri</i></p>
			<p><i>re</i></p>
			<p><i>rem</i></p>
			<p><i>reţi</i></p>
			<p><i>r</i></p>
		</prezent>
		<imperfect>
			<p><i>ream</i></p>
			<p><i>reai</i></p>
			<p><i>rea</i></p>
			<p><i>ream</i></p>
			<p><i>reaţi</i></p>
			<p><i>reau</i></p>
		</imperfect>
		<perfect-simplu>
			<p><i>rui</i></p>
			<p><i>ruși</i></p>
			<p><i>ru</i></p>
			<p><i>rurăm</i></p>
			<p><i>rurăţi</i></p>
			<p><i>rură</i></p>
		</perfect-simplu>
		<mai-mult-ca-perfect>
			<p><i>rusem</i></p>
			<p><i>ruseși</i></p>
			<p><i>ruse</i></p>
			<p><i>ruserăm</i></p>
			<p><i>ruserăţi</i></p>
			<p><i>ruseră</i></p>
		</mai-mult-ca-perfect>
		<viitor-2-popular>
			<p><i>r</i></p>
			<p><i>ri</i></p>
			<p><i>ară</i></p>
			<p><i>rem</i></p>
			<p><i>reţi</i></p>
			<p><i>ară</i></p>
		</viitor-2-popular>
	</Indicativ>
	<Conjunctiv>
		<prezent>
			<p><i>r</i></p>
			<p><i>ri</i></p>
			<p><i>ară</i></p>
			<p><i>rem</i></p>
			<p><i>reţi</i></p>
			<p><i>ară</i></p>
		</prezent>
		<perfect>
			<p><i>rut</i></p>
			<p><i>rut</i></p>
			<p><i>rut</i></p>
			<p><i>rut</i></p>
			<p><i>rut</i></p>
			<p><i>rut</i></p>
		</perfect>
	</Conjunctiv>
	<Infinitiv>
		<afirmativ>
			<p><i>re</i></p>
		</afirmativ>
	</Infinitiv>
	<Conditional>
		<prezent>
			<p><i>re</i></p>
			<p><i>re</i></p>
			<p><i>re</i></p>
			<p><i>re</i></p>
			<p><i>re</i></p>
			<p><i>re</i></p>
		</prezent>
		<perfect>
			<p><i>rut</i></p>
			<p><i>rut</i></p>
			<p><i>rut</i></p>
			<p><i>rut</i></p>
			<p><i>rut</i></p>
			<p><i>rut</i></p>
		</perfect>
	</Conditional>
	<Imperativ>
		<imperativ>
			<p><i>re</i></p>
			<p><i>reţi</i></p>
		</imperativ>
		<negativ>
			<p><i>re</i></p>
			<p><i>reţi</i></p>
		</negativ>
	</Imperativ>
	<Gerunziu>
		<gerunziu>
			<p><i>rând</i></p>
		</gerunziu>
	</Gerunziu>
	<Participiu>
		<participiu>
			<p><i>rut</i></p>
		</participiu>
	</Participiu>
</template>

<template name="d:a">
	<Indicativ>
		<prezent>
			<p><i>au</i></p>
			<p><i>ai</i></p>
			<p><i>ă</i></p>
			<p><i>ăm</i></p>
			<p><i>aţi</i></p>
			<p><i>au</i></p>
		</prezent>
		<imperfect>
			<p><i>ădeam</i></p>
			<p><i>ădeai</i></p>
			<p><i>ădea</i></p>
			<p><i>ădeam</i></p>
			<p><i>ădeaţi</i></p>
			<p><i>ădeau</i></p>
		</imperfect>
		<perfect-simplu>
			<p><i>ădui</i></p>
			<p><i>ăduși</i></p>
			<p><i>ădu</i></p>
			<p><i>ădurăm</i></p>
			<p><i>ădurăţi</i></p>
			<p><i>ădură</i></p>
		</perfect-simplu>
		<mai-mult-ca-perfect>
			<p><i>ădusem</i></p>
			<p><i>ăduseși</i></p>
			<p><i>ăduse</i></p>
			<p><i>ăduserăm</i></p>
			<p><i>ăduserăţi</i></p>
			<p><i>ăduseră</i></p>
		</mai-mult-ca-perfect>
		<viitor-2-popular>
			<p><i>au</i></p>
			<p><i>ai</i></p>
			<p><i>ea</i></p>
			<p><i>ăm</i></p>
			<p><i>aţi</i></p>
			<p><i>ea</i></p>
		</viitor-2-popular>
	</Indicativ>
	<Conjunctiv>
		<prezent>
			<p><i>au</i></p>
			<p><i>ai</i></p>
			<p><i>ea</i></p>
			<p><i>ăm</i></p>
			<p><i>aţi</i></p>
			<p><i>ea</i></p>
		</prezent>
		<perfect>
			<p><i>at</i></p>
			<p><i>at</i></p>
			<p><i>at</i></p>
			<p><i>at</i></p>
			<p><i>at</i></p>
			<p><i>at</i></p>
		</perfect>
	</Conjunctiv>
	<Infinitiv>
		<afirmativ>
			<p><i>a</i></p>
		</afirmativ>
	</Infinitiv>
	<Conditional>
		<prezent>
			<p><i>a</i></p>
			<p><i>a</i></p>
			<p><i>a</i></p>
			<p><i>a</i></p>
			<p><i>a</i></p>
			<p><i>a</i></p>
		</prezent>
		<perfect>
			<p><i>at</i></p>
			<p><i>at</i></p>
			<p><i>at</i></p>
			<p><i>at</i></p>
			<p><i>at</i></p>
			<p><i>at</i></p>
		</perfect>
	</Conditional>
	<Imperativ>
		<imperativ>
			<p><i>ă</i></p>
			<p><i>aţi</i></p>
		</imperativ>
		<negativ>
			<p><i>a</i></p>
			<p><i>aţi</i></p>
		</negativ>
	</Imperativ>
	<Gerunziu>
		<gerunziu>
			<p><i>ând</i></p>
		</gerunziu>
	</Gerunziu>
	<Participiu>
		<participiu>
			<p><i>at</i></p>
		</participiu>
	</Participiu>
</template>

<template name="dans:a">
	<Indicativ>
		<prezent>
			<p><i>ez</i></p>
			<p><i>ezi</i></p>
			<p><i>ează</i></p>
			<p><i>ăm</i></p>
			<p><i>aţi</i></p>
			<p><i>ează</i></p>
		</prezent>
		<imperfect>
			<p><i>am</i></p>
			<p><i>ai</i></p>
			<p><i>a</i></p>
			<p><i>am</i></p>
			<p><i>aţi</i></p>
			<p><i>au</i></p>
		</imperfect>
		<perfect-simplu>
			<p><i>ai</i></p>
			<p><i>ași</i></p>
			<p><i>ă</i></p>
			<p><i>arăm</i></p>
			<p><i>arăţi</i></p>
			<p><i>ară</i></p>
		</perfect-simplu>
		<mai-mult-ca-perfect>
			<p><i>asem</i></p>
			<p><i>aseși</i></p>
			<p><i>ase</i></p>
			<p><i>aserăm</i></p>
			<p><i>aserăţi</i></p>
			<p><i>aseră</i></p>
		</mai-mult-ca-perfect>
		<viitor-2-popular>
			<p><i>ez</i></p>
			<p><i>ezi</i></p>
			<p><i>eze</i></p>
			<p><i>ăm</i></p>
			<p><i>aţi</i></p>
			<p><i>eze</i></p>
		</viitor-2-popular>
	</Indicativ>
	<Conjunctiv>
		<prezent>
			<p><i>ez</i></p>
			<p><i>ezi</i></p>
			<p><i>eze</i></p>
			<p><i>ăm</i></p>
			<p><i>aţi</i></p>
			<p><i>eze</i></p>
		</prezent>
		<perfect>
			<p><i>at</i></p>
			<p><i>at</i></p>
			<p><i>at</i></p>
			<p><i>at</i></p>
			<p><i>at</i></p>
			<p><i>at</i></p>
		</perfect>
	</Conjunctiv>
	<Infinitiv>
		<afirmativ>
			<p><i>a</i></p>
		</afirmativ>
	</Infinitiv>
	<Conditional>
		<prezent>
			<p><i>a</i></p>
			<p><i>a</i></p>
			<p><i>a</i></p>
			<p><i>a</i></p>
			<p><i>a</i></p>
			<p><i>a</i></p>
		</prezent>
		<perfect>
			<p><i>at</i></p>
			<p><i>at</i></p>
			<p><i>at</i></p>
			<p><i>at</i></p>
			<p><i>at</i></p>
			<p><i>at</i></p>
		</perfect>
	</Conditional>
	<Imperativ>
		<imperativ>
			<p><i>ează</i></p>
			<p><i>aţi</i></p>
		</imperativ>
		<negativ>
			<p><i>a</i></p>
			<p><i>aţi</i></p>
		</negativ>
	</Imperativ>
	<Gerunziu>
		<gerunziu>
			<p><i>ând</i></p>
		</gerunziu>
	</Gerunziu>
	<Participiu>
		<participiu>
			<p><i>at</i></p>
		</participiu>
	</Participiu>
</template>

<template name="do:rmi">
	<Indicativ>
		<prezent>
			<p><i>rm</i></p>
			<p><i>rmi</i></p>
			<p><i>arme</i></p>
			<p><i>rmim</i></p>
			<p><i>rmiţi</i></p>
			<p><i>rm</i></p>
		</prezent>
		<imperfect>
			<p><i>rmeam</i></p>
			<p><i>rmeai</i></p>
			<p><i>rmea</i></p>
			<p><i>rmeam</i></p>
			<p><i>rmeaţi</i></p>
			<p><i>rmeau</i></p>
		</imperfect>
		<perfect-simplu>
			<p><i>rmii</i></p>
			<p><i>rmiși</i></p>
			<p><i>rmi</i></p>
			<p><i>rmirăm</i></p>
			<p><i>rmirăţi</i></p>
			<p><i>rmiră</i></p>
		</perfect-simplu>
		<mai-mult-ca-perfect>
			<p><i>rmisem</i></p>
			<p><i>rmiseși</i></p>
			<p><i>rmise</i></p>
			<p><i>rmiserăm</i></p>
			<p><i>rmiserăţi</i></p>
			<p><i>rmiseră</i></p>
		</mai-mult-ca-perfect>
		<viitor-2-popular>
			<p><i>rm</i></p>
			<p><i>rmi</i></p>
			<p><i>armă</i></p>
			<p><i>rmim</i></p>
			<p><i>rmiţi</i></p>
			<p><i>armă</i></p>
		</viitor-2-popular>
	</Indicativ>
	<Conjunctiv>
		<prezent>
			<p><i>rm</i></p>
			<p><i>rmi</i></p>
			<p><i>armă</i></p>
			<p><i>rmim</i></p>
			<p><i>rmiţi</i></p>
			<p><i>armă</i></p>
		</prezent>
		<perfect>
			<p><i>rmit</i></p>
			<p><i>rmit</i></p>
			<p><i>rmit</i></p>
			<p><i>rmit</i></p>
			<p><i>rmit</i></p>
			<p><i>rmit</i></p>
		</perfect>
	</Conjunctiv>
	<Infinitiv>
		<afirmativ>
			<p><i>rmi</i></p>
		</afirmativ>
	</Infinitiv>
	<Conditional>
		<prezent>
			<p><i>rmi</i></p>
			<p><i>rmi</i></p>
			<p><i>rmi</i></p>
			<p><i>rmi</i></p>
			<p><i>rmi</i></p>
			<p><i>rmi</i></p>
		</prezent>
		<perfect>
			<p><i>rmit</i></p>
			<p><i>rmit</i></p>
			<p><i>rmit</i></p>
			<p><i>rmit</i></p>
			<p><i>rmit</i></p>
			<p><i>rmit</i></p>
		</perfect>
	</Conditional>
	<Imperativ>
		<imperativ>
			<p><i>rmi</i></p>
			<p><i>rmiţi</i></p>
		</imperativ>
		<negativ>
			<p><i>rmi</i></p>
			<p><i>rmiţi</i></p>
		</negativ>
	</Imperativ>
	<Gerunziu>
		<gerunziu>
			<p><i>rmind</i></p>
		</gerunziu>
	</Gerunziu>
	<Participiu>
		<participiu>
			<p><i>rmit</i></p>
		</participiu>
	</Participiu>
</template>

<template name="fer:i">
	<Indicativ>
		<prezent>
			<p><i>esc</i></p>
			<p><i>ești</i></p>
			<p><i>ește</i></p>
			<p><i>im</i></p>
			<p><i>iţi</i></p>
			<p><i>esc</i></p>
		</prezent>
		<imperfect>
			<p><i>eam</i></p>
			<p><i>eai</i></p>
			<p><i>ea</i></p>
			<p><i>eam</i></p>
			<p><i>eaţi</i></p>
			<p><i>eau</i></p>
		</imperfect>
		<perfect-simplu>
			<p><i>ii</i></p>
			<p><i>iși</i></p>
			<p><i>i</i></p>
			<p><i>irăm</i></p>
			<p><i>irăţi</i></p>
			<p><i>iră</i></p>
		</perfect-simplu>
		<mai-mult-ca-perfect>
			<p><i>isem</i></p>
			<p><i>iseși</i></p>
			<p><i>ise</i></p>
			<p><i>iserăm</i></p>
			<p><i>iserăţi</i></p>
			<p><i>iseră</i></p>
		</mai-mult-ca-perfect>
		<viitor-2-popular>
			<p><i>esc</i></p>
			<p><i>ești</i></p>
			<p><i>ească</i></p>
			<p><i>im</i></p>
			<p><i>iţi</i></p>
			<p><i>ească</i></p>
		</viitor-2-popular>
	</Indicativ>
	<Conjunctiv>
		<prezent>
			<p><i>esc</i></p>
			<p><i>ești</i></p>
			<p><i>ească</i></p>
			<p><i>im</i></p>
			<p><i>iţi</i></p>
			<p><i>ească</i></p>
		</prezent>
		<perfect>
			<p><i>it</i></p>
			<p><i>it</i></p>
			<p><i>it</i></p>
			<p><i>it</i></p>
			<p><i>it</i></p>
			<p><i>it</i></p>
		</perfect>
	</Conjunctiv>
	<Infinitiv>
		<afirmativ>
			<p><i>i</i></p>
		</afirmativ>
	</Infinitiv>
	<Conditional>
		<prezent>
			<p><i>i</i></p>
			<p><i>i</i></p>
			<p><i>i</i></p>
			<p><i>i</i></p>
			<p><i>i</i></p>
			<p><i>i</i></p>
		</prezent>
		<perfect>
			<p><i>it</i></p>
			<p><i>it</i></p>
			<p><i>it</i></p>
			<p><i>it</i></p>
			<p><i>it</i></p>
			<p><i>it</i></p>
		</perfect>
	</Conditional>
	<Imperativ>
		<imperativ>
			<p><i>ește</i></p>
			<p><i>iţi</i></p>
		</imperativ>
		<negativ>
			<p><i>i</i></p>
			<p><i>iţi</i></p>
		</negativ>
	</Imperativ>
	<Gerunziu>
		<gerunziu>
			<p><i>ind</i></p>
		</gerunziu>
	</Gerunziu>
	<Participiu>
		<participiu>
			<p><i>it</i></p>
		</participiu>
	</Participiu>
</template>

<template name=":fi">
	<Indicativ>
		<prezent>
			<p><i>sunt</i></p>
			<p><i>ești</i></p>
			<p><i>e</i></p>
			<p><i>suntem</i></p>
			<p><i>sunteţi</i></p>
			<p><i>sunt</i></p>
		</prezent>
		<imperfect>
			<p><i>eram</i></p>
			<p><i>erai</i></p>
			<p><i>era</i></p>
			<p><i>eram</i></p>
			<p><i>eraţi</i></p>
			<p><i>erau</i></p>
		</imperfect>
		<perfect-simplu>
			<p><i>fui</i></p>
			<p><i>fuși</i></p>
			<p><i>fu</i></p>
			<p><i>furăm</i></p>
			<p><i>furăţi</i></p>
			<p><i>fură</i></p>
		</perfect-simplu>
		<mai-mult-ca-perfect>
			<p><i>fusesem</i></p>
			<p><i>fuseseși</i></p>
			<p><i>fusese</i></p>
			<p><i>fuseserăm</i></p>
			<p><i>fuseserăţi</i></p>
			<p><i>fuseseră</i></p>
		</mai-mult-ca-perfect>
		<viitor-2-popular>
			<p><i>fiu</i></p>
			<p><i>fii</i></p>
			<p><i>fie</i></p>
			<p><i>fim</i></p>
			<p><i>fiţi</i></p>
			<p><i>fie</i></p>
		</viitor-2-popular>
	</Indicativ>
	<Conjunctiv>
		<prezent>
			<p><i>fiu</i></p>
			<p><i>fii</i></p>
			<p><i>fie</i></p>
			<p><i>fim</i></p>
			<p><i>fiţi</i></p>
			<p><i>fie</i></p>
		</prezent>
		<perfect>
			<p><i>fost</i></p>
			<p><i>fost</i></p>
			<p><i>fost</i></p>
			<p><i>fost</i></p>
			<p><i>fost</i></p>
			<p><i>fost</i></p>
		</perfect>
	</Conjunctiv>
	<Infinitiv>
		<afirmativ>
			<p><i>fi</i></p>
		</afirmativ>
	</Infinitiv>
	<Conditional>
		<prezent>
			<p><i>fi</i></p>
			<p><i>fi</i></p>
			<p><i>fi</i></p>
			<p><i>fi</i></p>
			<p><i>fi</i></p>
			<p><i>fi</i></p>
		</prezent>
		<perfect>
			<p><i>fost</i></p>
			<p><i>fost</i></p>
			<p><i>fost</i></p>
			<p><i>fost</i></p>
			<p><i>fost</i></p>
			<p><i>fost</i></p>
		</perfect>
	</Conditional>
	<Imperativ>
		<imperativ>
			<p><i>fii</i></p>
			<p><i>fiţi</i></p>
		</imperativ>
		<negativ>
			<p><i>fi</i></p>
			<p><i>fiţi</i></p>
		</negativ>
	</Imperativ>
	<Gerunziu>
		<gerunziu>
			<p><i>fiind</i></p>
		</gerunziu>
	</Gerunziu>
	<Participiu>
		<participiu>
			<p><i>fost</i></p>
		</participiu>
	</Participiu>
</template>

<template name="v:oi">
	<Indicativ>
		<prezent>
			<p><i>oiesc</i><i>oi</i></p>
			<p><i>oiești</i><i>ei</i></p>
			<p><i>oiește</i><i>a</i></p>
			<p><i>oim</i><i>om</i></p>
			<p><i>oiţi</i><i>eţi</i></p>
			<p><i>oiesc</i><i>or</i></p>
		</prezent>
		<imperfect>
			<p><i>oiam</i></p>
			<p><i>oiai</i></p>
			<p><i>oia</i></p>
			<p><i>oiam</i></p>
			<p><i>oiaţi</i></p>
			<p><i>oiau</i></p>
		</imperfect>
		<perfect-simplu>
			<p><i>oii</i></p>
			<p><i>oiși</i></p>
			<p><i>oi</i></p>
			<p><i>oirăm</i></p>
			<p><i>oirăţi</i></p>
			<p><i>oiră</i></p>
		</perfect-simplu>
		<mai-mult-ca-perfect>
			<p><i>oisem</i></p>
			<p><i>oiseși</i></p>
			<p><i>oise</i></p>
			<p><i>oiserăm</i></p>
			<p><i>oiserăţi</i></p>
			<p><i>oiseră</i></p>
		</mai-mult-ca-perfect>
		<viitor-2-popular>
			<p><i>oiesc</i></p>
			<p><i>oiești</i></p>
			<p><i>oiască</i></p>
			<p><i>oim</i></p>
			<p><i>oiţi</i></p>
			<p><i>oiască</i></p>
		</viitor-2-popular>
	</Indicativ>
	<Conjunctiv>
		<prezent>
			<p><i>oiesc</i></p>
			<p><i>oiești</i></p>
			<p><i>oiască</i></p>
			<p><i>oim</i></p>
			<p><i>oiţi</i></p>
			<p><i>oiască</i></p>
		</prezent>
		<perfect>
			<p><i>oit</i></p>
			<p><i>oit</i></p>
			<p><i>oit</i></p>
			<p><i>oit</i></p>
			<p><i>oit</i></p>
			<p><i>oit</i></p>
		</perfect>
	</Conjunctiv>
	<Infinitiv>
		<afirmativ>
			<p><i/></p>
		</afirmativ>
	</Infinitiv>
	<Conditional>
		<prezent>
			<p><i>oi</i></p>
			<p><i>oi</i></p>
			<p><i>oi</i></p>
			<p><i>oi</i></p>
			<p><i>oi</i></p>
			<p><i>oi</i></p>
		</prezent>
		<perfect>
			<p><i>oit</i></p>
			<p><i>oit</i></p>
			<p><i>oit</i></p>
			<p><i>oit</i></p>
			<p><i>oit</i></p>
			<p><i>oit</i></p>
		</perfect>
	</Conditional>
	<Imperativ>
		<imperativ>
			<p><i>oiește</i></p>
			<p><i>oiţi</i></p>
		</imperativ>
		<negativ>
			<p><i>oi</i></p>
			<p><i>oiţi</i></p>
		</negativ>
	</Imperativ>
	<Gerunziu>
		<gerunziu>
			<p><i>oind</i></p>
		</gerunziu>
	</Gerunziu>
	<Participiu>
		<participiu>
			<p><i>oit</i></p>
		</participiu>
	</Participiu>
</template>

<template name="locui:">
	<Indicativ>
		<prezent>
			<p><i>esc</i></p>
			<p><i>ești</i></p>
			<p><i>ește</i></p>
			<p><i>m</i></p>
			<p><i>ţi</i></p>
			<p><i>esc</i></p>
		</prezent>
		<imperfect>
			<p><i>am</i></p>
			<p><i>ai</i></p>
			<p><i>a</i></p>
			<p><i>am</i></p>
			<p><i>aţi</i></p>
			<p><i>au</i></p>
		</imperfect>
		<perfect-simplu>
			<p><i>i</i></p>
			<p><i>și</i></p>
			<p><i/></p>
			<p><i>răm</i></p>
			<p><i>răţi</i></p>
			<p><i>ră</i></p>
		</perfect-simplu>
		<mai-mult-ca-perfect>
			<p><i>sem</i></p>
			<p><i>seși</i></p>
			<p><i>se</i></p>
			<p><i>serăm</i></p>
			<p><i>serăţi</i></p>
			<p><i>seră</i></p>
		</mai-mult-ca-perfect>
		<viitor-2-popular>
			<p><i>esc</i></p>
			<p><i>ești</i></p>
			<p><i>ască</i></p>
			<p><i>m</i></p>
			<p><i>ţi</i></p>
			<p><i>ască</i></p>
		</viitor-2-popular>
	</Indicativ>
	<Conjunctiv>
		<prezent>
			<p><i>esc</i></p>
			<p><i>ești</i></p>
			<p><i>ască</i></p>
			<p><i>m</i></p>
			<p><i>ţi</i></p>
			<p><i>ască</i></p>
		</prezent>
		<perfect>
			<p><i>t</i></p>
			<p><i>t</i></p>
			<p><i>t</i></p>
			<p><i>t</i></p>
			<p><i>t</i></p>
			<p><i>t</i></p>
		</perfect>
	</Conjunctiv>
	<Infinitiv>
		<afirmativ>
			<p><i/></p>
		</afirmativ>
	</Infinitiv>
	<Conditional>
		<prezent>
			<p><i/></p>
			<p><i/></p>
			<p><i/></p>
			<p><i/></p>
			<p><i/></p>
			<p><i/></p>
		</prezent>
		<perfect>
			<p><i>t</i></p>
			<p><i>t</i></p>
			<p><i>t</i></p>
			<p><i>t</i></p>
			<p><i>t</i></p>
			<p><i>t</i></p>
		</perfect>
	</Conditional>
	<Imperativ>
		<imperativ>
			<p><i>ește</i></p>
			<p><i>ţi</i></p>
		</imperativ>
		<negativ>
			<p><i/></p>
			<p><i>ţi</i></p>
		</negativ>
	</Imperativ>
	<Gerunziu>
		<gerunziu>
			<p><i>nd</i></p>
		</gerunziu>
	</Gerunziu>
	<Participiu>
		<participiu>
			<p><i>t</i></p>
		</participiu>
	</Participiu>
</template>

<template name=":lua">
	<Indicativ>
		<prezent>
			<p><i>iau</i></p>
			<p><i>iei</i></p>
			<p><i>ia</i></p>
			<p><i>luăm</i></p>
			<p><i>luaţi</i></p>
			<p><i>iau</i></p>
		</prezent>
		<imperfect>
			<p><i>luam</i></p>
			<p><i>luai</i></p>
			<p><i>lua</i></p>
			<p><i>luam</i></p>
			<p><i>luaţi</i></p>
			<p><i>luau</i></p>
		</imperfect>
		<perfect-simplu>
			<p><i>luai</i></p>
			<p><i>luași</i></p>
			<p><i>luă</i></p>
			<p><i>luarăm</i></p>
			<p><i>luarăţi</i></p>
			<p><i>luară</i></p>
		</perfect-simplu>
		<mai-mult-ca-perfect>
			<p><i>luasem</i></p>
			<p><i>luaseși</i></p>
			<p><i>luase</i></p>
			<p><i>luaserăm</i></p>
			<p><i>luaserăţi</i></p>
			<p><i>luaseră</i></p>
		</mai-mult-ca-perfect>
		<viitor-2-popular>
			<p><i>iau</i></p>
			<p><i>iei</i></p>
			<p><i>ia</i></p>
			<p><i>luăm</i></p>
			<p><i>luaţi</i></p>
			<p><i>ia</i></p>
		</viitor-2-popular>
	</Indicativ>
	<Conjunctiv>
		<prezent>
			<p><i>iau</i></p>
			<p><i>iei</i></p>
			<p><i>ia</i></p>
			<p><i>luăm</i></p>
			<p><i>luaţi</i></p>
			<p><i>ia</i></p>
		</prezent>
		<perfect>
			<p><i>luat</i></p>
			<p><i>luat</i></p>
			<p><i>luat</i></p>
			<p><i>luat</i></p>
			<p><i>luat</i></p>
			<p><i>luat</i></p>
		</perfect>
	</Conjunctiv>
	<Infinitiv>
		<afirmativ>
			<p><i>lua</i></p>
		</afirmativ>
	</Infinitiv>
	<Conditional>
		<prezent>
			<p><i>lua</i></p>
			<p><i>lua</i></p>
			<p><i>lua</i></p>
			<p><i>lua</i></p>
			<p><i>lua</i></p>
			<p><i>lua</i></p>
		</prezent>
		<perfect>
			<p><i>luat</i></p>
			<p><i>luat</i></p>
			<p><i>luat</i></p>
			<p><i>luat</i></p>
			<p><i>luat</i></p>
			<p><i>luat</i></p>
		</perfect>
	</Conditional>
	<Imperativ>
		<imperativ>
			<p><i>ia</i></p>
			<p><i>luaţi</i></p>
		</imperativ>
		<negativ>
			<p><i>lua</i></p>
			<p><i>luaţi</i></p>
		</negativ>
	</Imperativ>
	<Gerunziu>
		<gerunziu>
			<p><i>luând</i></p>
		</gerunziu>
	</Gerunziu>
	<Participiu>
		<participiu>
			<p><i>luat</i></p>
		</participiu>
	</Participiu>
</template>

<template name="m:ânca">
	<Indicativ>
		<prezent>
			<p><i>ănânc</i></p>
			<p><i>ănânci</i></p>
			<p><i>ănâncă</i></p>
			<p><i>âncăm</i></p>
			<p><i>âncaţi</i></p>
			<p><i>ănâncă</i></p>
		</prezent>
		<imperfect>
			<p><i>âncam</i></p>
			<p><i>âncai</i></p>
			<p><i>ânca</i></p>
			<p><i>âncam</i></p>
			<p><i>âncaţi</i></p>
			<p><i>âncau</i></p>
		</imperfect>
		<perfect-simplu>
			<p><i>âncai</i></p>
			<p><i>âncași</i></p>
			<p><i>âncă</i></p>
			<p><i>âncarăm</i></p>
			<p><i>âncarăţi</i></p>
			<p><i>âncară</i></p>
		</perfect-simplu>
		<mai-mult-ca-perfect>
			<p><i>âncasem</i></p>
			<p><i>âncaseși</i></p>
			<p><i>âncase</i></p>
			<p><i>âncaserăm</i></p>
			<p><i>âncaserăţi</i></p>
			<p><i>âncaseră</i></p>
		</mai-mult-ca-perfect>
		<viitor-2-popular>
			<p><i>ănânc</i></p>
			<p><i>ănânci</i></p>
			<p><i>ănânce</i></p>
			<p><i>âncăm</i></p>
			<p><i>âncaţi</i></p>
			<p><i>ănânce</i></p>
		</viitor-2-popular>
	</Indicativ>
	<Conjunctiv>
		<prezent>
			<p><i>ănânc</i></p>
			<p><i>ănânci</i></p>
			<p><i>ănânce</i></p>
			<p><i>âncăm</i></p>
			<p><i>âncaţi</i></p>
			<p><i>ănânce</i></p>
		</prezent>
		<perfect>
			<p><i>âncat</i></p>
			<p><i>âncat</i></p>
			<p><i>âncat</i></p>
			<p><i>âncat</i></p>
			<p><i>âncat</i></p>
			<p><i>âncat</i></p>
		</perfect>
	</Conjunctiv>
	<Infinitiv>
		<afirmativ>
			<p><i>ânca</i></p>
		</afirmativ>
	</Infinitiv>
	<Conditional>
		<prezent>
			<p><i>ânca</i></p>
			<p><i>ânca</i></p>
			<p><i>ânca</i></p>
			<p><i>ânca</i></p>
			<p><i>ânca</i></p>
			<p><i>ânca</i></p>
		</prezent>
		<perfect>
			<p><i>âncat</i></p>
			<p><i>âncat</i></p>
			<p><i>âncat</i></p>
			<p><i>âncat</i></p>
			<p><i>âncat</i></p>
			<p><i>âncat</i></p>
		</perfect>
	</Conditional>
	<Imperativ>
		<imperativ>
			<p><i>ănâncă</i></p>
			<p><i>âncaţi</i></p>
		</imperativ>
		<negativ>
			<p><i>ânca</i></p>
			<p><i>âncaţi</i></p>
		</negativ>
	</Imperativ>
	<Gerunziu>
		<gerunziu>
			<p><i>âncând</i></p>
		</gerunziu>
	</Gerunziu>
	<Participiu>
		<participiu>
			<p><i>âncat</i></p>
		</participiu>
	</Participiu>
</template>

<template name="p:ărea">
	<Indicativ>
		<prezent>
			<p><i>ar</i></p>
			<p><i>ari</i></p>
			<p><i>are</i></p>
			<p><i>ărem</i></p>
			<p><i>ăreţi</i></p>
			<p><i>ar</i></p>
		</prezent>
		<imperfect>
			<p><i>ăream</i></p>
			<p><i>ăreai</i></p>
			<p><i>ărea</i></p>
			<p><i>ăream</i></p>
			<p><i>ăreaţi</i></p>
			<p><i>ăreau</i></p>
		</imperfect>
		<perfect-simplu>
			<p><i>ărui</i></p>
			<p><i>ăruși</i></p>
			<p><i>ăru</i></p>
			<p><i>ărurăm</i></p>
			<p><i>ărurăţi</i></p>
			<p><i>ărură</i></p>
		</perfect-simplu>
		<mai-mult-ca-perfect>
			<p><i>ărusem</i></p>
			<p><i>ăruseși</i></p>
			<p><i>ăruse</i></p>
			<p><i>ăruserăm</i></p>
			<p><i>ăruserăţi</i></p>
			<p><i>ăruseră</i></p>
		</mai-mult-ca-perfect>
		<viitor-2-popular>
			<p><i>ar</i></p>
			<p><i>ari</i></p>
			<p><i>ară</i></p>
			<p><i>ărem</i></p>
			<p><i>ăreţi</i></p>
			<p><i>ară</i></p>
		</viitor-2-popular>
	</Indicativ>
	<Conjunctiv>
		<prezent>
			<p><i>ar</i></p>
			<p><i>ari</i></p>
			<p><i>ară</i></p>
			<p><i>ărem</i></p>
			<p><i>ăreţi</i></p>
			<p><i>ară</i></p>
		</prezent>
		<perfect>
			<p><i>ărut</i></p>
			<p><i>ărut</i></p>
			<p><i>ărut</i></p>
			<p><i>ărut</i></p>
			<p><i>ărut</i></p>
			<p><i>ărut</i></p>
		</perfect>
	</Conjunctiv>
	<Infinitiv>
		<afirmativ>
			<p><i>ărea</i></p>
		</afirmativ>
	</Infinitiv>
	<Conditional>
		<prezent>
			<p><i>ărea</i></p>
			<p><i>ărea</i></p>
			<p><i>ărea</i></p>
			<p><i>ărea</i></p>
			<p><i>ărea</i></p>
			<p><i>ărea</i></p>
		</prezent>
		<perfect>
			<p><i>ărut</i></p>
			<p><i>ărut</i></p>
			<p><i>ărut</i></p>
			<p><i>ărut</i></p>
			<p><i>ărut</i></p>
			<p><i>ărut</i></p>
		</perfect>
	</Conditional>
	<Imperativ>
		<imperativ>
			<p><i>are</i></p>
			<p><i>ăreţi</i></p>
		</imperativ>
		<negativ>
			<p><i>ărea</i></p>
			<p><i>ăreţi</i></p>
		</negativ>
	</Imperativ>
	<Gerunziu>
		<gerunziu>
			<p><i>ărând</i></p>
		</gerunziu>
	</Gerunziu>
	<Participiu>
		<participiu>
			<p><i>ărut</i></p>
		</participiu>
	</Participiu>
</template>

<template name="pu:ne">
	<Indicativ>
		<prezent>
			<p><i>n</i></p>
			<p><i>i</i></p>
			<p><i>ne</i></p>
			<p><i>nem</i></p>
			<p><i>neţi</i></p>
			<p><i>n</i></p>
		</prezent>
		<imperfect>
			<p><i>neam</i></p>
			<p><i>neai</i></p>
			<p><i>nea</i></p>
			<p><i>neam</i></p>
			<p><i>neaţi</i></p>
			<p><i>neau</i></p>
		</imperfect>
		<perfect-simplu>
			<p><i>sei</i></p>
			<p><i>seși</i></p>
			<p><i>se</i></p>
			<p><i>serăm</i></p>
			<p><i>serăţi</i></p>
			<p><i>seră</i></p>
		</perfect-simplu>
		<mai-mult-ca-perfect>
			<p><i>sesem</i></p>
			<p><i>seseși</i></p>
			<p><i>sese</i></p>
			<p><i>seserăm</i></p>
			<p><i>seserăţi</i></p>
			<p><i>seseră</i></p>
		</mai-mult-ca-perfect>
		<viitor-2-popular>
			<p><i>n</i></p>
			<p><i>i</i></p>
			<p><i>ie</i></p>
			<p><i>nem</i></p>
			<p><i>neţi</i></p>
			<p><i>ie</i></p>
		</viitor-2-popular>
	</Indicativ>
	<Conjunctiv>
		<prezent>
			<p><i>n</i></p>
			<p><i>i</i></p>
			<p><i>ie</i></p>
			<p><i>nem</i></p>
			<p><i>neţi</i></p>
			<p><i>ie</i></p>
		</prezent>
		<perfect>
			<p><i>s</i></p>
			<p><i>s</i></p>
			<p><i>s</i></p>
			<p><i>s</i></p>
			<p><i>s</i></p>
			<p><i>s</i></p>
		</perfect>
	</Conjunctiv>
	<Infinitiv>