<?xml version="1.0" encoding='utf-8'?>

<!--
	verbs-pt.xml - List of Portuguese verbs with their conjugation template.
	The templates were generated by SekouD using Unsupervised Learning,
	and follow the xml schema defined by Pierre Sarrazin in conjug_manager.

	Copyright (C) 2018 Sekou Diao <https://github.com/SekouD>
	Copyright (C) 2003-2016 Pierre Sarrazin <http://sarrazip.com/>

	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with this program; if not, write to the Free Software
	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
	02110-1301, USA.
-->

<!DOCTYPE verbs-pt [
    <!ELEMENT verbs-pt (v)+>
    <!ATTLIST verbs-pt
      xmlns CDATA #FIXED ''>

    <!ELEMENT v (i,t)> <!-- verb's conjugation information (infinitive, radical) -->
    <!ATTLIST v
      xmlns CDATA #FIXED ''>

    <!ELEMENT i (#PCDATA)>  <!-- infinitive -->
    <!ATTLIST i
      xmlns CDATA #FIXED ''>

    <!ELEMENT t (#PCDATA)> <!-- template (radical:termination) -->
    <!ATTLIST t
        xmlns CDATA #FIXED ''>
]>

<verbs-pt>

<v><i>ababalhar</i>		<t>compr:ar</t></v>
<v><i>ababelar</i>		<t>compr:ar</t></v>
<v><i>ababelar-se</i>		<t>ababel:ar-se</t></v>
<v><i>ababosar</i>		<t>compr:ar</t></v>
<v><i>ababosar-se</i>		<t>ababel:ar-se</t></v>
<v><i>abacalhoar</i>		<t>perdo:ar</t></v>
<v><i>abacalhoar-se</i>		<t>abacalho:ar-se</t></v>
<v><i>abacelar</i>		<t>compr:ar</t></v>
<v><i>abacharelar-se</i>		<t>ababel:ar-se</t></v>
<v><i>abaciar</i>		<t>compr:ar</t></v>
<v><i>abacinar</i>		<t>compr:ar</t></v>
<v><i>abacinar-se</i>		<t>ababel:ar-se</t></v>
<v><i>abadalar</i>		<t>compr:ar</t></v>
<v><i>abadalar-se</i>		<t>ababel:ar-se</t></v>
<v><i>abadanar</i>		<t>compr:ar</t></v>
<v><i>abadanar-se</i>		<t>ababel:ar-se</t></v>
<v><i>abadar</i>		<t>compr:ar</t></v>
<v><i>abadernar</i>		<t>compr:ar</t></v>
<v><i>abadessar</i>		<t>compr:ar</t></v>
<v><i>abadiar</i>		<t>compr:ar</t></v>
<v><i>abaetar</i>		<t>compr:ar</t></v>
<v><i>abafar</i>		<t>compr:ar</t></v>
<v><i>abaganhar</i>		<t>compr:ar</t></v>
<v><i>abagoar</i>		<t>perdo:ar</t></v>
<v><i>abagualar-se</i>		<t>ababel:ar-se</t></v>
<v><i>abagunçar</i>		<t>come:çar</t></v>
<v><i>abainhar</i>		<t>compr:ar</t></v>
<v><i>abaionetar</i>		<t>compr:ar</t></v>
<v><i>abairrar</i>		<t>compr:ar</t></v>
<v><i>abaiucar</i>		<t>abai:ucar</t></v>
<v><i>abaixar</i>		<t>compr:ar</t></v>
<v><i>abajoujar-se</i>		<t>ababel:ar-se</t></v>
<v><i>abalançar</i>		<t>come:çar</t></v>
<v><i>abalançar-se</i>		<t>abalan:çar-se</t></v>
<v><i>abalar</i>		<t>compr:ar</t></v>
<v><i>abalaustrar</i>		<t>abala:ustrar</t></v>
<v><i>abalizar</i>		<t>compr:ar</t></v>
<v><i>abalizar-se</i>		<t>ababel:ar-se</t></v>
<v><i>abaloar</i>		<t>perdo:ar</t></v>
<v><i>abalofar</i>		<t>compr:ar</t></v>
<v><i>abalofar-se</i>		<t>ababel:ar-se</t></v>
<v><i>abalroar</i>		<t>perdo:ar</t></v>
<v><i>abalroar-se</i>		<t>abacalho:ar-se</t></v>
<v><i>abalsar</i>		<t>compr:ar</t></v>
<v><i>abaluartar</i>		<t>compr:ar</t></v>
<v><i>abaluartar-se</i>		<t>ababel:ar-se</t></v>
<v><i>abananar</i>		<t>compr:ar</t></v>
<v><i>abananar-se</i>		<t>ababel:ar-se</t></v>
<v><i>abanar</i>		<t>compr:ar</t></v>
<v><i>abanar-se</i>		<t>ababel:ar-se</t></v>
<v><i>abancar</i>		<t>aban:car</t></v>
<v><i>abancar-se</i>		<t>aban:car-se</t></v>
<v><i>abandalhar</i>		<t>compr:ar</t></v>
<v><i>abandalhar-se</i>		<t>ababel:ar-se</t></v>
<v><i>abandar</i>		<t>compr:ar</t></v>
<v><i>abandar-se</i>		<t>ababel:ar-se</t></v>
<v><i>abandear</i>		<t>relampague:ar</t></v>
<v><i>abandear-se</i>		<t>abande:ar-se</t></v>
<v><i>abandeirar</i>		<t>compr:ar</t></v>
<v><i>abandeirar-se</i>		<t>ababel:ar-se</t></v>
<v><i>abandejar</i>		<t>compr:ar</t></v>
<v><i>abandidar</i>		<t>compr:ar</t></v>
<v><i>abandidar-se</i>		<t>ababel:ar-se</t></v>
<v><i>abandoar-se</i>		<t>abacalho:ar-se</t></v>
<v><i>abandonar</i>		<t>compr:ar</t></v>
<v><i>abandonar-se</i>		<t>ababel:ar-se</t></v>
<v><i>abanicar</i>		<t>aban:car</t></v>
<v><i>abanicar-se</i>		<t>aban:car-se</t></v>
<v><i>abaquetar</i>		<t>compr:ar</t></v>
<v><i>abar</i>		<t>ab:ar</t></v>
<v><i>abaratar</i>		<t>compr:ar</t></v>
<v><i>abarbar</i>		<t>compr:ar</t></v>
<v><i>abarbarar-se</i>		<t>ababel:ar-se</t></v>
<v><i>abarbarizar</i>		<t>compr:ar</t></v>
<v><i>abarbelar</i>		<t>compr:ar</t></v>
<v><i>abarbilhar</i>		<t>compr:ar</t></v>
<v><i>abarcar</i>		<t>aban:car</t></v>
<v><i>abaritonar</i>		<t>compr:ar</t></v>
<v><i>abaritonar-se</i>		<t>ababel:ar-se</t></v>
<v><i>abarracar</i>		<t>aban:car</t></v>
<v><i>abarracar-se</i>		<t>aban:car-se</t></v>
<v><i>abarrancar</i>		<t>aban:car</t></v>
<v><i>abarrancar-se</i>		<t>aban:car-se</t></v>
<v><i>abarregar-se</i>		<t>abarreg:ar-se</t></v>
<v><i>abarreirar</i>		<t>compr:ar</t></v>
<v><i>abarretar</i>		<t>compr:ar</t></v>
<v><i>abarretar-se</i>		<t>ababel:ar-se</t></v>
<v><i>abarrigar</i>		<t>cheg:ar</t></v>
<v><i>abarrotar</i>		<t>compr:ar</t></v>
<v><i>abarrotar-se</i>		<t>ababel:ar-se</t></v>
<v><i>abasbacar</i>		<t>aban:car</t></v>
<v><i>abasbacar-se</i>		<t>aban:car-se</t></v>
<v><i>abastar</i>		<t>compr:ar</t></v>
<v><i>abastar-se</i>		<t>ababel:ar-se</t></v>
<v><i>abastardar</i>		<t>compr:ar</t></v>
<v><i>abastardar-se</i>		<t>ababel:ar-se</t></v>
<v><i>abastecer</i>		<t>aque:cer</t></v>
<v><i>abastecer-se</i>		<t>abaste:cer-se</t></v>
<v><i>abatatar</i>		<t>compr:ar</t></v>
<v><i>abater</i>		<t>vend:er</t></v>
<v><i>abater-se</i>		<t>abat:er-se</t></v>
<v><i>abatocar</i>		<t>aban:car</t></v>
<v><i>abatumar</i>		<t>compr:ar</t></v>
<v><i>abaular</i>		<t>aba:ular</t></v>
<v><i>abaçanar</i>		<t>compr:ar</t></v>
<v><i>abdicar</i>		<t>aban:car</t></v>
<v><i>abduzir</i>		<t>traduz:ir</t></v>
<v><i>abeatar</i>		<t>compr:ar</t></v>
<v><i>abeatar-se</i>		<t>ababel:ar-se</t></v>
<v><i>abeberar</i>		<t>compr:ar</t></v>
<v><i>abeberar-se</i>		<t>ababel:ar-se</t></v>
<v><i>abecar</i>		<t>abe:car</t></v>
<v><i>abeirar</i>		<t>compr:ar</t></v>
<v><i>abeirar-se</i>		<t>ababel:ar-se</t></v>
<v><i>abelidar-se</i>		<t>ababel:ar-se</t></v>
<v><i>abemolar</i>		<t>compr:ar</t></v>
<v><i>abemolar-se</i>		<t>ababel:ar-se</t></v>
<v><i>abendiçoar</i>		<t>perdo:ar</t></v>
<v><i>abençoar</i>		<t>perdo:ar</t></v>
<v><i>abençoar-se</i>		<t>abacalho:ar-se</t></v>
<v><i>aberrar</i>		<t>compr:ar</t></v>
<v><i>aberrar-se</i>		<t>ababel:ar-se</t></v>
<v><i>aberturar</i>		<t>compr:ar</t></v>
<v><i>abesantar</i>		<t>compr:ar</t></v>
<v><i>abespinhar</i>		<t>compr:ar</t></v>
<v><i>abespinhar-se</i>		<t>ababel:ar-se</t></v>
<v><i>abestiar</i>		<t>compr:ar</t></v>
<v><i>abetumar</i>		<t>compr:ar</t></v>
<v><i>abexigar</i>		<t>cheg:ar</t></v>
<v><i>abibliotecar</i>		<t>aban:car</t></v>
<v><i>abicar</i>		<t>abe:car</t></v>
<v><i>abicar-se</i>		<t>abi:car-se</t></v>
<v><i>abichar</i>		<t>compr:ar</t></v>
<v><i>abichar-se</i>		<t>ababel:ar-se</t></v>
<v><i>abicharar</i>		<t>compr:ar</t></v>
<v><i>abichornar</i>		<t>compr:ar</t></v>
<v><i>abichornar-se</i>		<t>ababel:ar-se</t></v>
<v><i>abirritar</i>		<t>compr:ar</t></v>
<v><i>abiscoitar</i>		<t>compr:ar</t></v>
<v><i>abiscoutar</i>		<t>compr:ar</t></v>
<v><i>abismar</i>		<t>compr:ar</t></v>
<v><i>abismar-se</i>		<t>ababel:ar-se</t></v>
<v><i>abitar</i>		<t>compr:ar</t></v>
<v><i>abitolar</i>		<t>compr:ar</t></v>
<v><i>abjudicar</i>		<t>aban:car</t></v>
<v><i>abjugar</i>		<t>cheg:ar</t></v>
<v><i>abjungir</i>		<t>fri:gir</t></v>
<v><i>abjurar</i>		<t>compr:ar</t></v>
<v><i>abjurgar</i>		<t>cheg:ar</t></v>
<v><i>ablactar</i>		<t>compr:ar</t></v>
<v><i>ablaquear</i>		<t>relampague:ar</t></v>
<v><i>ablaquecer</i>		<t>aque:cer</t></v>
<v><i>ablegar</i>		<t>cheg:ar</t></v>
<v><i>abluir</i>		<t>distribu:ir</t></v>
<v><i>abluir-se</i>		<t>ablu:ir-se</t></v>
<v><i>abnegar</i>		<t>cheg:ar</t></v>
<v><i>abnegar-se</i>		<t>abarreg:ar-se</t></v>
<v><i>abnodar</i>		<t>compr:ar</t></v>
<v><i>abnuir</i>		<t>distribu:ir</t></v>
<v><i>abobadar</i>		<t>compr:ar</t></v>
<v><i>abobar</i>		<t>compr:ar</t></v>
<v><i>abobar-se</i>		<t>ababel:ar-se</t></v>
<v><i>aboborar</i>		<t>compr:ar</t></v>
<v><i>aboborar-se</i>		<t>ababel:ar-se</t></v>
<v><i>abocanhar</i>		<t>compr:ar</t></v>
<v><i>abocanhar-se</i>		<t>ababel:ar-se</t></v>
<v><i>abocar</i>		<t>abe:car</t></v>
<v><i>abocar-se</i>		<t>abi:car-se</t></v>
<v><i>abocetar</i>		<t>compr:ar</t></v>
<v><i>abochornar</i>		<t>compr:ar</t></v>
<v><i>abochornar-se</i>		<t>ababel:ar-se</t></v>
<v><i>abodegar</i>		<t>cheg:ar</t></v>
<v><i>aboiar</i>		<t>ab:oiar</t></v>
<v><i>abojar</i>		<t>compr:ar</t></v>
<v><i>abolachar</i>		<t>compr:ar</t></v>
<v><i>abolar</i>		<t>compr:ar</t></v>
<v><i>aboldriar</i>		<t>compr:ar</t></v>
<v><i>aboldriar-se</i>		<t>ababel:ar-se</t></v>
<v><i>aboleimar</i>		<t>compr:ar</t></v>
<v><i>aboleimar-se</i>		<t>ababel:ar-se</t></v>
<v><i>aboletar</i>		<t>compr:ar</t></v>
<v><i>aboletar-se</i>		<t>ababel:ar-se</t></v>
<v><i>abolinar</i>		<t>compr:ar</t></v>
<v><i>abolir</i>		<t>retorqu:ir</t></v>
<v><i>abolorecer</i>		<t>aque:cer</t></v>
<v><i>abolsar</i>		<t>compr:ar</t></v>
<v><i>abolçar</i>		<t>come:çar</t></v>
<v><i>abombar</i>		<t>compr:ar</t></v>
<v><i>abombar-se</i>		<t>ababel:ar-se</t></v>
<v><i>abominar</i>		<t>compr:ar</t></v>
<v><i>abominar-se</i>		<t>ababel:ar-se</t></v>
<v><i>abonançar</i>		<t>come:çar</t></v>
<v><i>abonar</i>		<t>compr:ar</t></v>
<v><i>abonar-se</i>		<t>ababel:ar-se</t></v>
<v><i>abonecar</i>		<t>aban:car</t></v>
<v><i>abonecar-se</i>		<t>aban:car-se</t></v>
<v><i>aboquejar</i>		<t>compr:ar</t></v>
<v><i>aborbulhar</i>		<t>compr:ar</t></v>
<v><i>aborbulhar-se</i>		<t>ababel:ar-se</t></v>
<v><i>abordar</i>		<t>compr:ar</t></v>
<v><i>abordoar</i>		<t>perdo:ar</t></v>
<v><i>aborletar</i>		<t>compr:ar</t></v>
<v><i>abornalar</i>		<t>compr:ar</t></v>
<v><i>aborrascar</i>		<t>aban:car</t></v>
<v><i>aborrecer</i>		<t>aque:cer</t></v>
<v><i>aborrecer-se</i>		<t>abaste:cer-se</t></v>
<v><i>aborregar</i>		<t>cheg:ar</t></v>
<v><i>aborregar-se</i>		<t>abarreg:ar-se</t></v>
<v><i>aborrir</i>		<t>garant:ir</t></v>
<v><i>aborrir-se</i>		<t>aborr:ir-se</t></v>
<v><i>abortar</i>		<t>compr:ar</t></v>
<v><i>aboscar</i>		<t>aban:car</t></v>
<v><i>abostelar</i>		<t>compr:ar</t></v>
<v><i>abotecar</i>		<t>aban:car</t></v>
<v><i>aboticar</i>		<t>aban:car</t></v>
<v><i>abotinar</i>		<t>compr:ar</t></v>
<v><i>abotoar</i>		<t>perdo:ar</t></v>
<v><i>abotoar-se</i>		<t>abacalho:ar-se</t></v>
<v><i>abotocar</i>		<t>aban:car</t></v>
<v><i>aboubar-se</i>		<t>ababel:ar-se</t></v>
<v><i>aboçar</i>		<t>come:çar</t></v>
<v><i>abracar</i>		<t>aban:car</t></v>
<v><i>abrandar</i>		<t>compr:ar</t></v>
<v><i>abrandecer</i>		<t>aque:cer</t></v>
<v><i>abranger</i>		<t>prote:ger</t></v>
<v><i>abranger-se</i>		<t>abran:ger-se</t></v>
<v><i>abrasar</i>		<t>compr:ar</t></v>
<v><i>abrasar-se</i>		<t>ababel:ar-se</t></v>
<v><i>abrasear</i>		<t>relampague:ar</t></v>
<v><i>abrasileirar</i>		<t>compr:ar</t></v>
<v><i>abrasileirar-se</i>		<t>ababel:ar-se</t></v>
<v><i>abrasilianar</i>		<t>compr:ar</t></v>
<v><i>abrasilianar-se</i>		<t>ababel:ar-se</t></v>
<v><i>abrasonar</i>		<t>compr:ar</t></v>
<v><i>abraçar</i>		<t>come:çar</t></v>
<v><i>abraçar-se</i>		<t>abalan:çar-se</t></v>
<v><i>abrejar</i>		<t>compr:ar</t></v>
<v><i>abrejar-se</i>		<t>ababel:ar-se</t></v>
<v><i>abrenhar</i>		<t>compr:ar</t></v>
<v><i>abrenhar-se</i>		<t>ababel:ar-se</t></v>
<v><i>abrenunciar</i>		<t>compr:ar</t></v>
<v><i>abrevar</i>		<t>compr:ar</t></v>
<v><i>abrevar-se</i>		<t>ababel:ar-se</t></v>
<v><i>abreviar</i>		<t>compr:ar</t></v>
<v><i>abreviar-se</i>		<t>ababel:ar-se</t></v>
<v><i>abrigar</i>		<t>cheg:ar</t></v>
<v><i>abrigar-se</i>		<t>abarreg:ar-se</t></v>
<v><i>abrir</i>		<t>ab:rir</t></v>
<v><i>abrir-se</i>		<t>ab:rir-se</t></v>
<v><i>abrochar</i>		<t>compr:ar</t></v>
<v><i>abrochar-se</i>		<t>ababel:ar-se</t></v>
<v><i>abrogar</i>		<t>cheg:ar</t></v>
<v><i>abrolhar</i>		<t>compr:ar</t></v>
<v><i>abrolhar-se</i>		<t>ababel:ar-se</t></v>
<v><i>abronzar</i>		<t>compr:ar</t></v>
<v><i>abronzear</i>		<t>relampague:ar</t></v>
<v><i>abroquelar</i>		<t>compr:ar</t></v>
<v><i>abroquelar-se</i>		<t>ababel:ar-se</t></v>
<v><i>abrotar</i>		<t>compr:ar</t></v>
<v><i>abrumar</i>		<t>compr:ar</t></v>
<v><i>abrutalhar</i>		<t>compr:ar</t></v>
<v><i>abrutalhar-se</i>		<t>ababel:ar-se</t></v>
<v><i>abrutar</i>		<t>compr:ar</t></v>
<v><i>abrutar-se</i>		<t>ababel:ar-se</t></v>
<v><i>abrutecer</i>		<t>aque:cer</t></v>
<v><i>abrutecer-se</i>		<t>abaste:cer-se</t></v>
<v><i>absceder</i>		<t>vend:er</t></v>
<v><i>abscidar</i>		<t>compr:ar</t></v>
<v><i>absconder</i>		<t>vend:er</t></v>
<v><i>absconder-se</i>		<t>abat:er-se</t></v>
<v><i>absintiar</i>		<t>compr:ar</t></v>
<v><i>absolver</i>		<t>absolv:er</t></v>
<v><i>absolver-se</i>		<t>absolv:er-se</t></v>
<v><i>absonar</i>		<t>compr:ar</t></v>
<v><i>absorver</i>		<t>vend:er</t></v>
<v><i>absorver-se</i>		<t>abat:er-se</t></v>
<v><i>abster</i>		<t>abst:er</t></v>
<v><i>abster-se</i>		<t>abst:er-se</t></v>
<v><i>absterger</i>		<t>prote:ger</t></v>
<v><i>abstrair</i>		<t>sa:ir</t></v>
<v><i>abstrair-se</i>		<t>abstra:ir-se</t></v>
<v><i>abufelar</i>		<t>compr:ar</t></v>
<v><i>abugalhar</i>		<t>compr:ar</t></v>
<v><i>abular</i>		<t>compr:ar</t></v>
<v><i>abundanciar</i>		<t>compr:ar</t></v>
<v><i>abundar</i>		<t>compr:ar</t></v>
<v><i>abunhar</i>		<t>compr:ar</t></v>
<v><i>aburacar</i>		<t>aban:car</t></v>
<v><i>aburelar</i>		<t>compr:ar</t></v>
<v><i>aburelar-se</i>		<t>ababel:ar-se</t></v>
<v><i>aburguesar</i>		<t>compr:ar</t></v>
<v><i>aburguesar-se</i>		<t>ababel:ar-se</t></v>
<v><i>abusar</i>		<t>compr:ar</t></v>
<v><i>abuzinar</i>		<t>compr:ar</t></v>
<v><i>acabanar</i>		<t>compr:ar</t></v>
<v><i>acabar</i>		<t>compr:ar</t></v>
<v><i>acabar-se</i>		<t>ababel:ar-se</t></v>
<v><i>acabaçar</i>		<t>come:çar</t></v>
<v><i>acabelar</i>		<t>compr:ar</t></v>
<v><i>acaboclar</i>		<t>compr:ar</t></v>
<v><i>acaboclar-se</i>		<t>ababel:ar-se</t></v>
<v><i>acabramar</i>		<t>compr:ar</t></v>
<v><i>acabrunhar</i>		<t>compr:ar</t></v>
<v><i>acabrunhar-se</i>		<t>ababel:ar-se</t></v>
<v><i>acachapar</i>		<t>compr:ar</t></v>
<v><i>acachapar-se</i>		<t>ababel:ar-se</t></v>
<v><i>acachar</i>		<t>compr:ar</t></v>
<v><i>acachar-se</i>		<t>ababel:ar-se</t></v>
<v><i>acachoar</i>		<t>perdo:ar</t></v>
<v><i>acachoar-se</i>		<t>abacalho:ar-se</t></v>
<v><i>acacifar</i>		<t>compr:ar</t></v>
<v><i>acacular</i>		<t>compr:ar</t></v>
<v><i>acadeirar-se</i>		<t>ababel:ar-se</t></v>
<v><i>academiar</i>		<t>compr:ar</t></v>
<v><i>acadimar</i>		<t>compr:ar</t></v>
<v><i>acafajestar-se</i>		<t>ababel:ar-se</t></v>
<v><i>acafelar</i>		<t>compr:ar</t></v>
<v><i>acafobar</i>		<t>compr:ar</t></v>
<v><i>acafobar-se</i>		<t>ababel:ar-se</t></v>
<v><i>acaipirar-se</i>		<t>ababel:ar-se</t></v>
<v><i>acairelar</i>		<t>compr:ar</t></v>
<v><i>acaiçarar-se</i>		<t>ababel:ar-se</t></v>
<v><i>acajadar</i>		<t>compr:ar</t></v>
<v><i>acalantar</i>		<t>compr:ar</t></v>
<v><i>acalantar-se</i>		<t>ababel:ar-se</t></v>
<v><i>acalcanhar</i>		<t>compr:ar</t></v>
<v><i>acalcar</i>		<t>aban:car</t></v>
<v><i>acalentar</i>		<t>compr:ar</t></v>
<v><i>acalentar-se</i>		<t>ababel:ar-se</t></v>
<v><i>acalmar</i>		<t>compr:ar</t></v>
<v><i>acalmar-se</i>		<t>ababel:ar-se</t></v>
<v><i>acalorar</i>		<t>compr:ar</t></v>
<v><i>acalorar-se</i>		<t>ababel:ar-se</t></v>
<v><i>acamar</i>		<t>compr:ar</t></v>
<v><i>acamar-se</i>		<t>ababel:ar-se</t></v>
<v><i>acamaradar</i>		<t>compr:ar</t></v>
<v><i>acamaradar-se</i>		<t>ababel:ar-se</t></v>
<v><i>acambetar</i>		<t>compr:ar</t></v>
<v><i>acamboar</i>		<t>perdo:ar</t></v>
<v><i>acambulhar</i>		<t>compr:ar</t></v>
<v><i>acambulhar-se</i>		<t>ababel:ar-se</t></v>
<v><i>acampar</i>		<t>compr:ar</t></v>
<v><i>acampar-se</i>		<t>ababel:ar-se</t></v>
<v><i>acamurçar</i>		<t>come:çar</t></v>
<v><i>acanalar</i>		<t>compr:ar</t></v>
<v><i>acanalhar</i>		<t>compr:ar</t></v>
<v><i>acanalhar-se</i>		<t>ababel:ar-se</t></v>
<v><i>acanavear</i>		<t>relampague:ar</t></v>
<v><i>acanavear-se</i>		<t>abande:ar-se</t></v>
<v><i>acancelar</i>		<t>compr:ar</t></v>
<v><i>acanelar</i>		<t>compr:ar</t></v>
<v><i>acanhar</i>		<t>compr:ar</t></v>
<v><i>acanhar-se</i>		<t>ababel:ar-se</t></v>
<v><i>acanhoar</i>		<t>perdo:ar</t></v>
<v><i>acanhonear</i>		<t>relampague:ar</t></v>
<v><i>acanoar</i>		<t>perdo:ar</t></v>
<v><i>acantoar</i>		<t>perdo:ar</t></v>
<v><i>acantoar-se</i>		<t>abacalho:ar-se</t></v>
<v><i>acanular</i>		<t>compr:ar</t></v>
<v><i>acapachar</i>		<t>compr:ar</t></v>
<v><i>acapachar-se</i>		<t>ababel:ar-se</t></v>
<v><i>acapangar-se</i>		<t>abarreg:ar-se</t></v>
<v><i>acapelar</i>		<t>compr:ar</t></v>
<v><i>acapelar-se</i>		<t>ababel:ar-se</t></v>
<v><i>acapitular</i>		<t>compr:ar</t></v>
<v><i>acapoeirar-se</i>		<t>ababel:ar-se</t></v>
<v><i>acardumar</i>		<t>compr:ar</t></v>
<v><i>acardumar-se</i>		<t>ababel:ar-se</t></v>
<v><i>acarear</i>		<t>relampague:ar</t></v>
<v><i>acariciar</i>		<t>compr:ar</t></v>
<v><i>acaridar</i>		<t>compr:ar</t></v>
<v><i>acaridar-se</i>		<t>ababel:ar-se</t></v>
<v><i>acarinhar</i>		<t>compr:ar</t></v>
<v><i>acaroar</i>		<t>perdo:ar</t></v>
<v><i>acarrancar</i>		<t>aban:car</t></v>
<v><i>acarrancar-se</i>		<t>aban:car-se</t></v>
<v><i>acarrapatar</i>		<t>compr:ar</t></v>
<v><i>acarrar</i>		<t>compr:ar</t></v>
<v><i>acarrar-se</i>		<t>ababel:ar-se</t></v>
<v><i>acarrear</i>		<t>relampague:ar</t></v>
<v><i>acarretar</i>		<t>compr:ar</t></v>
<v><i>acartonar</i>		<t>compr:ar</t></v>
<v><i>acasalar</i>		<t>compr:ar</t></v>
<v><i>acasalar-se</i>		<t>ababel:ar-se</t></v>
<v><i>acasear</i>		<t>relampague:ar</t></v>
<v><i>acastanhar</i>		<t>compr:ar</t></v>
<v><i>acastelar</i>		<t>compr:ar</t></v>
<v><i>acastelar-se</i>		<t>ababel:ar-se</t></v>
<v><i>acastelhanar</i>		<t>compr:ar</t></v>
<v><i>acastelhanar-se</i>		<t>ababel:ar-se</t></v>
<v><i>acasular</i>		<t>compr:ar</t></v>
<v><i>acatar</i>		<t>compr:ar</t></v>
<v><i>acatarroar-se</i>		<t>abacalho:ar-se</t></v>
<v><i>acatassolar</i>		<t>compr:ar</t></v>
<v><i>acatitar</i>		<t>compr:ar</t></v>
<v><i>acatitar-se</i>		<t>ababel:ar-se</t></v>
<v><i>acatruzar</i>		<t>compr:ar</t></v>
<v><i>acaudilhar</i>		<t>compr:ar</t></v>
<v><i>acaudilhar-se</i>		<t>ababel:ar-se</t></v>
<v><i>acautelar</i>		<t>compr:ar</t></v>
<v><i>acautelar-se</i>		<t>ababel:ar-se</t></v>
<v><i>acavalar</i>		<t>compr:ar</t></v>
<v><i>acavalar-se</i>		<t>ababel:ar-se</t></v>
<v><i>acavaleirar</i>		<t>compr:ar</t></v>
<v><i>acaçapar</i>		<t>compr:ar</t></v>
<v><i>acaçapar-se</i>		<t>ababel:ar-se</t></v>
<v><i>accionar</i>		<t>compr:ar</t></v>
<v><i>acebolar</i>		<t>compr:ar</t></v>
<v><i>aceder</i>		<t>vend:er</t></v>
<v><i>aceimar</i>		<t>compr:ar</t></v>
<v><i>aceirar</i>		<t>compr:ar</t></v>
<v><i>aceitar</i>		<t>aceit:ar</t></v>
<v><i>aceleirar</i>		<t>compr:ar</t></v>
<v><i>acelerar</i>		<t>compr:ar</t></v>
<v><i>acelerar-se</i>		<t>ababel:ar-se</t></v>
<v><i>acenar</i>		<t>compr:ar</t></v>
<v><i>acenar-se</i>		<t>ababel:ar-se</t></v>
<v><i>acender</i>		<t>ace:nder</t></v>
<v><i>acender-se</i>		<t>ace:nder-se</t></v>
<v><i>acendrar</i>		<t>compr:ar</t></v>
<v><i>acentuar</i>		<t>compr:ar</t></v>
<v><i>acentuar-se</i>		<t>ababel:ar-se</t></v>
<v><i>acepilhar</i>		<t>compr:ar</t></v>
<v><i>acepilhar-se</i>		<t>ababel:ar-se</t></v>
<v><i>acerar</i>		<t>compr:ar</t></v>
<v><i>acerbar</i>		<t>compr:ar</t></v>
<v><i>acercar</i>		<t>aban:car</t></v>
<v><i>acercar-se</i>		<t>aban:car-se</t></v>
<v><i>acerejar</i>		<t>compr:ar</t></v>
<v><i>acertar</i>		<t>compr:ar</t></v>
<v><i>acertar-se</i>		<t>ababel:ar-se</t></v>
<v><i>acervar</i>		<t>compr:ar</t></v>
<v><i>acetar</i>		<t>compr:ar</t></v>
<v><i>acetar-se</i>		<t>ababel:ar-se</t></v>
<v><i>acetificar</i>		<t>aban:car</t></v>
<v><i>acetificar-se</i>		<t>aban:car-se</t></v>
<v><i>acetinar</i>		<t>compr:ar</t></v>
<v><i>acevadar</i>		<t>compr:ar</t></v>
<v><i>acevar</i>		<t>compr:ar</t></v>
<v><i>acevar-se</i>		<t>ababel:ar-se</t></v>
<v><i>achacar</i>		<t>aban:car</t></v>
<v><i>achacar-se</i>		<t>aban:car-se</t></v>
<v><i>achamboar</i>		<t>perdo:ar</t></v>
<v><i>achamboar-se</i>		<t>abacalho:ar-se</t></v>
<v><i>achambonar</i>		<t>compr:ar</t></v>
<v><i>achambonar-se</i>		<t>ababel:ar-se</t></v>
<v><i>achanar</i>		<t>compr:ar</t></v>
<v><i>achaparrar</i>		<t>compr:ar</t></v>
<v><i>achar</i>		<t>ach:ar</t></v>
<v><i>achar-se</i>		<t>ach:ar-se</t></v>
<v><i>acharoar</i>		<t>perdo:ar</t></v>
<v><i>achatar</i>		<t>compr:ar</t></v>
<v><i>achatar-se</i>		<t>ababel:ar-se</t></v>
<v><i>achavascar</i>		<t>aban:car</t></v>
<v><i>achavascar-se</i>		<t>aban:car-se</t></v>
<v><i>achegar</i>		<t>cheg:ar</t></v>
<v><i>achegar-se</i>		<t>abarreg:ar-se</t></v>
<v><i>achibantar</i>		<t>compr:ar</t></v>
<v><i>achibantar-se</i>		<t>ababel:ar-se</t></v>
<v><i>achicar</i>		<t>aban:car</t></v>
<v><i>achicar-se</i>		<t>aban:car-se</t></v>
<v><i>achichelar</i>		<t>compr:ar</t></v>
<v><i>achinar</i>		<t>compr:ar</t></v>
<v><i>achinar-se</i>		<t>ababel:ar-se</t></v>
<v><i>achincalhar</i>		<t>compr:ar</t></v>
<v><i>achinelar</i>		<t>compr:ar</t></v>
<v><i>achinelar-se</i>		<t>ababel:ar-se</t></v>
<v><i>achinesar</i>		<t>compr:ar</t></v>
<v><i>achinesar-se</i>		<t>ababel:ar-se</t></v>
<v><i>achoar</i>		<t>perdo:ar</t></v>
<v><i>achocalhar</i>		<t>compr:ar</t></v>
<v><i>achumbar</i>		<t>compr:ar</t></v>
<v><i>acicatar</i>		<t>compr:ar</t></v>
<v><i>acidar</i>		<t>compr:ar</t></v>
<v><i>acidar-se</i>		<t>ababel:ar-se</t></v>
<v><i>acidentar</i>		<t>compr:ar</t></v>
<v><i>acidentar-se</i>		<t>ababel:ar-se</t></v>
<v><i>acidificar</i>		<t>aban:car</t></v>
<v><i>acidificar-se</i>		<t>aban:car-se</t></v>
<v><i>acidrar</i>		<t>compr:ar</t></v>
<v><i>acidular</i>		<t>compr:ar</t></v>
<v><i>acidular-se</i>		<t>ababel:ar-se</t></v>
<v><i>aciganar</i>		<t>compr:ar</t></v>
<v><i>aciganar-se</i>		<t>ababel:ar-se</t></v>
<v><i>acingir</i>		<t>redi:gir</t></v>
<v><i>acingir-se</i>		<t>acin:gir-se</t></v>
<v><i>acinzar</i>		<t>compr:ar</t></v>
<v><i>acinzar-se</i>		<t>ababel:ar-se</t></v>
<v><i>acinzentar</i>		<t>compr:ar</t></v>
<v><i>acinzentar-se</i>		<t>ababel:ar-se</t></v>
<v><i>acionar</i>		<t>compr:ar</t></v>
<v><i>acirandar</i>		<t>compr:ar</t></v>
<v><i>acirrar</i>		<t>compr:ar</t></v>
<v><i>acirrar-se</i>		<t>ababel:ar-se</t></v>
<v><i>aclamar</i>		<t>compr:ar</t></v>
<v><i>aclamar-se</i>		<t>ababel:ar-se</t></v>
<v><i>aclarar</i>		<t>compr:ar</t></v>
<v><i>aclarar-se</i>		<t>ababel:ar-se</t></v>
<v><i>aclerizar-se</i>		<t>ababel:ar-se</t></v>
<v><i>aclimar</i>		<t>compr:ar</t></v>
<v><i>aclimar-se</i>		<t>ababel:ar-se</t></v>
<v><i>aclimatar</i>		<t>compr:ar</t></v>
<v><i>aclimatar-se</i>		<t>ababel:ar-se</t></v>
<v><i>aclimatizar</i>		<t>compr:ar</t></v>
<v><i>aclimatizar-se</i>		<t>ababel:ar-se</t></v>
<v><i>acobardar</i>		<t>compr:ar</t></v>
<v><i>acobardar-se</i>		<t>ababel:ar-se</t></v>
<v><i>acobertar</i>		<t>compr:ar</t></v>
<v><i>acobertar-se</i>		<t>ababel:ar-se</t></v>
<v><i>acobilhar</i>		<t>compr:ar</t></v>
<v><i>acobrear</i>		<t>relampague:ar</t></v>
<v><i>acocar</i>		<t>abe:car</t></v>
<v><i>acocar-se</i>		<t>abi:car-se</t></v>
<v><i>acochar</i>		<t>compr:ar</t></v>
<v><i>acochar-se</i>		<t>ababel:ar-se</t></v>
<v><i>acocorar</i>		<t>compr:ar</t></v>
<v><i>acocorar-se</i>		<t>ababel:ar-se</t></v>
<v><i>acoelhar-se</i>		<t>ababel:ar-se</t></v>
<v><i>acogular</i>		<t>compr:ar</t></v>
<v><i>acogular-se</i>		<t>ababel:ar-se</t></v>
<v><i>acoimar</i>		<t>compr:ar</t></v>
<v><i>acoimar-se</i>		<t>ababel:ar-se</t></v>
<v><i>acoirelar</i>		<t>compr:ar</t></v>
<v><i>acoitar</i>		<t>compr:ar</t></v>
<v><i>acoitar-se</i>		<t>ababel:ar-se</t></v>
<v><i>acolchetar</i>		<t>compr:ar</t></v>
<v><i>acolchetar-se</i>		<t>ababel:ar-se</t></v>
<v><i>acolchoar</i>		<t>perdo:ar</t></v>
<v><i>acoletar</i>		<t>compr:ar</t></v>
<v><i>acoletar-se</i>		<t>ababel:ar-se</t></v>
<v><i>acolher</i>		<t>vend:er</t></v>
<v><i>acolher-se</i>		<t>abat:er-se</t></v>
<v><i>acolherar</i>		<t>compr:ar</t></v>
<v><i>acolherar-se</i>		<t>ababel:ar-se</t></v>
<v><i>acolitar</i>		<t>compr:ar</t></v>
<v><i>acomadrar-se</i>		<t>ababel:ar-se</t></v>
<v><i>acometer</i>		<t>vend:er</t></v>
<v><i>acometer-se</i>		<t>abat:er-se</t></v>
<v><i>acomodar</i>		<t>compr:ar</t></v>
<v><i>acomodar-se</i>		<t>ababel:ar-se</t></v>
<v><i>acompadrar</i>		<t>compr:ar</t></v>
<v><i>acompadrar-se</i>		<t>ababel:ar-se</t></v>
<v><i>acompanhar</i>		<t>compr:ar</t></v>
<v><i>acompanhar-se</i>		<t>ababel:ar-se</t></v>
<v><i>acompridar</i>		<t>compr:ar</t></v>
<v><i>acomunar-se</i>		<t>ababel:ar-se</t></v>
<v><i>aconchar</i>		<t>compr:ar</t></v>
<v><i>aconchavar</i>		<t>compr:ar</t></v>
<v><i>aconchavar-se</i>		<t>ababel:ar-se</t></v>
<v><i>aconchear</i>		<t>relampague:ar</t></v>
<v><i>aconchegar</i>		<t>cheg:ar</t></v>
<v><i>aconchegar-se</i>		<t>abarreg:ar-se</t></v>
<v><i>acondicionar</i>		<t>compr:ar</t></v>
<v><i>acondicionar-se</i>		<t>ababel:ar-se</t></v>
<v><i>aconfeitar</i>		<t>compr:ar</t></v>
<v><i>aconfradar</i>		<t>compr:ar</t></v>
<v><i>aconfradar-se</i>		<t>ababel:ar-se</t></v>
<v><i>aconselhar</i>		<t>compr:ar</t></v>
<v><i>aconselhar-se</i>		<t>ababel:ar-se</t></v>
<v><i>aconsoantar</i>		<t>compr:ar</t></v>
<v><i>acontecer</i>		<t>aque:cer</t></v>
<v><i>acontiar</i>		<t>compr:ar</t></v>
<v><i>acontiar-se</i>		<t>ababel:ar-se</t></v>
<v><i>acontonar</i>		<t>compr:ar</t></v>
<v><i>acoplar</i>		<t>compr:ar</t></v>
<v><i>acoplar-se</i>		<t>ababel:ar-se</t></v>
<v><i>acoquinar</i>		<t>compr:ar</t></v>
<v><i>acoquinar-se</i>		<t>ababel:ar-se</t></v>
<v><i>acoraçoar</i>		<t>perdo:ar</t></v>
<v><i>acoraçoar-se</i>		<t>abacalho:ar-se</t></v>
<v><i>acorcundar</i>		<t>compr:ar</t></v>
<v><i>acorcundar-se</i>		<t>ababel:ar-se</t></v>
<v><i>acordar</i>		<t>compr:ar</t></v>
<v><i>acordar-se</i>		<t>ababel:ar-se</t></v>
<v><i>acornar</i>		<t>compr:ar</t></v>
<v><i>acoroçoar</i>		<t>perdo:ar</t></v>
<v><i>acoroçoar-se</i>		<t>abacalho:ar-se</t></v>
<v><i>acorrentar</i>		<t>compr:ar</t></v>
<v><i>acorrentar-se</i>		<t>ababel:ar-se</t></v>
<v><i>acorrer</i>		<t>vend:er</t></v>
<v><i>acorrer-se</i>		<t>abat:er-se</t></v>
<v><i>acorrilhar</i>		<t>compr:ar</t></v>
<v><i>acortinar</i>		<t>compr:ar</t></v>
<v><i>acoruchar</i>		<t>compr:ar</t></v>
<v><i>acorçoar</i>		<t>perdo:ar</t></v>
<v><i>acorçoar-se</i>		<t>abacalho:ar-se</t></v>
<v><i>acossar</i>		<t>compr:ar</t></v>
<v><i>acostar</i>		<t>compr:ar</t></v>
<v><i>acostar-se</i>		<t>ababel:ar-se</t></v>
<v><i>acostumar</i>		<t>compr:ar</t></v>
<v><i>acotiar</i>		<t>compr:ar</t></v>
<v><i>acotoar</i>		<t>perdo:ar</t></v>
<v><i>acotoar-se</i>		<t>abacalho:ar-se</t></v>
<v><i>acotonar</i>		<t>compr:ar</t></v>
<v><i>acotonar-se</i>		<t>ababel:ar-se</t></v>
<v><i>acotovelar</i>		<t>compr:ar</t></v>
<v><i>acotovelar-se</i>		<t>ababel:ar-se</t></v>
<v><i>acotunar</i>		<t>compr:ar</t></v>
<v><i>acourelar</i>		<t>compr:ar</t></v>
<v><i>acoutar</i>		<t>compr:ar</t></v>
<v><i>acoutar-se</i>		<t>ababel:ar-se</t></v>
<v><i>acovar</i>		<t>compr:ar</t></v>
<v><i>acovardar</i>		<t>compr:ar</t></v>
<v><i>acovardar-se</i>		<t>ababel:ar-se</t></v>
<v><i>acovilhar</i>		<t>compr:ar</t></v>
<v><i>acravar</i>		<t>compr:ar</t></v>
<v><i>acravar-se</i>		<t>ababel:ar-se</t></v>
<v><i>acreditar</i>		<t>compr:ar</t></v>
<v><i>acreditar-se</i>		<t>ababel:ar-se</t></v>
<v><i>acrescentar</i>		<t>compr:ar</t></v>
<v><i>acrescentar-se</i>		<t>ababel:ar-se</t></v>
<v><i>acrescer</i>		<t>aque:cer</t></v>
<v><i>acriançar-se</i>		<t>abalan:çar-se</t></v>
<v><i>acrimoniar</i>		<t>compr:ar</t></v>
<v><i>acrimoniar-se</i>		<t>ababel:ar-se</t></v>
<v><i>acrioular-se</i>		<t>ababel:ar-se</t></v>
<v><i>acrisolar</i>		<t>compr:ar</t></v>
<v><i>acrisolar-se</i>		<t>ababel:ar-se</t></v>
<v><i>acromatizar</i>		<t>compr:ar</t></v>
<v><i>activar</i>		<t>compr:ar</t></v>
<v><i>activar-se</i>		<t>ababel:ar-se</t></v>
<v><i>actualizar</i>		<t>compr:ar</t></v>
<v><i>actuar</i>		<t>compr:ar</t></v>
<v><i>acuar</i>		<t>ach:ar</t></v>
<v><i>acucular</i>		<t>compr:ar</t></v>
<v><i>acudir</i>		<t>ac:udir</t></v>
<v><i>acudir-se</i>		<t>ac:udir-se</t></v>
<v><i>aculear</i>		<t>relampague:ar</t></v>
<v><i>acumear</i>		<t>relampague:ar</t></v>
<v><i>acuminar</i>		<t>compr:ar</t></v>
<v><i>acumpliciar</i>		<t>compr:ar</t></v>
<v><i>acumpliciar-se</i>		<t>ababel:ar-se</t></v>
<v><i>acumular</i>		<t>compr:ar</t></v>
<v><i>acumular-se</i>		<t>ababel:ar-se</t></v>
<v><i>acunhar</i>		<t>compr:ar</t></v>
<v><i>acunhear</i>		<t>relampague:ar</t></v>
<v><i>acupuncturar</i>		<t>compr:ar</t></v>
<v><i>acupunturar</i>		<t>compr:ar</t></v>
<v><i>acurar</i>		<t>compr:ar</t></v>
<v><i>acurar-se</i>		<t>ababel:ar-se</t></v>
<v><i>acurralar</i>		<t>compr:ar</t></v>
<v><i>acurtar</i>		<t>compr:ar</t></v>
<v><i>acurtar-se</i>		<t>ababel:ar-se</t></v>
<v><i>acurvar</i>		<t>compr:ar</t></v>
<v><i>acurvilhar</i>		<t>compr:ar</t></v>
<v><i>acusar</i>		<t>compr:ar</t></v>
<v><i>acusar-se</i>		<t>ababel:ar-se</t></v>
<v><i>acutilar</i>		<t>compr:ar</t></v>
<v><i>acutilar-se</i>		<t>ababel:ar-se</t></v>
<v><i>adagiar</i>		<t>compr:ar</t></v>
<v><i>adamar</i>		<t>compr:ar</t></v>
<v><i>adamar-se</i>		<t>ababel:ar-se</t></v>
<v><i>adamascar</i>		<t>aban:car</t></v>
<v><i>adaptar</i>		<t>compr:ar</t></v>
<v><i>adaptar-se</i>		<t>ababel:ar-se</t></v>
<v><i>adarvar</i>		<t>compr:ar</t></v>
<v><i>adastrar</i>		<t>compr:ar</t></v>
<v><i>adegar</i>		<t>cheg:ar</t></v>
<v><i>adejar</i>		<t>compr:ar</t></v>
<v><i>adelgadar</i>		<t>compr:ar</t></v>
<v><i>adelgadar-se</i>		<t>ababel:ar-se</t></v>
<v><i>adelgaçar</i>		<t>come:çar</t></v>
<v><i>adelgaçar-se</i>		<t>abalan:çar-se</t></v>
<v><i>adensar</i>		<t>compr:ar</t></v>
<v><i>adensar-se</i>		<t>ababel:ar-se</t></v>
<v><i>adentar</i>		<t>compr:ar</t></v>