<?xml version="1.0" encoding='utf-8'?>

<!--
	verbs-ca.xml - List of Catalan verbs with their conjugation template.
	The templates follow the xml schema defined by Pierre Sarrazin.

	Copyright (C) 2003-2016 Pierre Sarrazin <http://sarrazip.com/>

	Most of the verbs in this list were imported from catverbs 
	developed by Neil Roberts (bpeel) (GNU GPL v2.0)
	<https://github.com/bpeel/catverbs> 

	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with this program; if not, write to the Free Software
	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
	02110-1301, USA.
-->

<!DOCTYPE verbs-ca [
    <!ELEMENT verbs-ca (v)+>
    <!ATTLIST verbs-ca
      xmlns CDATA #FIXED ''>

    <!ELEMENT v (i,t)> <!-- verb's conjugation information (infinitive, radical) -->
    <!ATTLIST v
      xmlns CDATA #FIXED ''>

    <!ELEMENT i (#PCDATA)>  <!-- infinitive -->
    <!ATTLIST i
      xmlns CDATA #FIXED ''>

    <!ELEMENT t (#PCDATA)> <!-- template (radical:termination) -->
    <!ATTLIST t
        xmlns CDATA #FIXED ''>
]>

<verbs-ca>

<!--
https://www.verbix.com/webverbix/go.php?D1=7&T1=abadanar
-->

<!--
First-conjugation (-ar) verbs
	About 86 percent of Catalan verbs belong to this group. 
	Examples include estimar ("to love"), esperar ("to wait" and "to hope"), 
	menjar ("to eat") and pensar ("to think").
-->

<v><i>cantar</i>	<t>cant:ar</t></v>
<v><i>parlar</i>	<t>cant:ar</t></v>

<!--	
Second-conjugation (-re, -er) verbs
	The most-frequently-used second-conjugation (-re, -er) verbs: 
	ser ("to be"), haver ("to have"), fer ("to do"), veure ("to see"), poder ("can"), 
	voler ("to want"), caldre ("must"), dir ("to say") and dur ("to take/get"). 
-->

<v><i>ser</i>		<t>:ser</t></v>
<v><i>haver</i>		<t>h:aver</t></v>
<v><i>fer</i>		<t>:fer</t></v>
<v><i>veure</i>		<t>v:eure</t></v>
<v><i>estar</i>		<t>est:ar</t></v>

<!--
Third-conjugation (-ir) verbs
This is the second-largest group of regular verbs in the Catalan language 
(about 10 percent of verbs in the dictionary). 
-->

<v><i>servir</i>	<t>serv:ir</t></v>
<v><i>tenir</i>		<t>t:enir</t></v>

<!-- Verbs imported from catverbs -->
<v><i>abacallanar</i>	<t>cant:ar</t></v>
<v><i>abadanar</i>	<t>cant:ar</t></v>
<v><i>abadernar</i>	<t>cant:ar</t></v>
<v><i>abaixar</i>	<t>cant:ar</t></v>
<v><i>abalançar</i>	<t>comen:çar</t></v>
<v><i>abalisar</i>	<t>cant:ar</t></v>
<v><i>aballestar</i>	<t>cant:ar</t></v>
<v><i>abaltir</i>	<t>serv:ir</t></v>
<v><i>abancalar</i>	<t>cant:ar</t></v>
<v><i>abanderar</i>	<t>cant:ar</t></v>
<v><i>abandonar</i>	<t>cant:ar</t></v>
<v><i>abaratir</i>	<t>serv:ir</t></v>
<v><i>abarbetar</i>	<t>cant:ar</t></v>
<v><i>abarloar</i>	<t>evacu:ar</t></v>
<v><i>abaronar</i>	<t>cant:ar</t></v>
<v><i>abarrancar</i>	<t>tren:car</t></v>
<v><i>abarrocar</i>	<t>tren:car</t></v>
<v><i>abarrotar</i>	<t>cant:ar</t></v>
<v><i>abassegar</i>	<t>preg:ar</t></v>
<v><i>abastar</i>	<t>cant:ar</t></v>
<v><i>abastir</i>	<t>serv:ir</t></v>
<v><i>abatollar</i>	<t>cant:ar</t></v>
<v><i>abatre</i>	<t>perd:re</t></v>
<v><i>abdicar</i>	<t>tren:car</t></v>
<v><i>abduir</i>	<t>redu:ir</t></v>
<v><i>abellir</i>	<t>serv:ir</t></v>
<v><i>abessonar</i>	<t>cant:ar</t></v>
<v><i>abeurar</i>	<t>cant:ar</t></v>
<v><i>abillar</i>	<t>cant:ar</t></v>
<v><i>abismar</i>	<t>cant:ar</t></v>
<v><i>abissar</i>	<t>cant:ar</t></v>
<v><i>abjurar</i>	<t>cant:ar</t></v>
<v><i>ablamar</i>	<t>cant:ar</t></v>
<v><i>ablanir</i>	<t>serv:ir</t></v>
<v><i>ablenar</i>	<t>cant:ar</t></v>
<v><i>abocar</i>	<t>tren:car</t></v>
<v><i>aboiar</i>	<t>esgla:iar</t></v>
<v><i>aboldronar</i>	<t>cant:ar</t></v>
<v><i>abolir</i>	<t>serv:ir</t></v>
<v><i>abominar</i>	<t>cant:ar</t></v>
<v><i>abonançar</i>	<t>comen:çar</t></v>
<v><i>abonar</i>	<t>cant:ar</t></v>
<v><i>abonir</i>	<t>serv:ir</t></v>
<v><i>abonyegar</i>	<t>preg:ar</t></v>
<v><i>abordar</i>	<t>cant:ar</t></v>
<v><i>aborrallonar</i>	<t>cant:ar</t></v>
<v><i>aborronar</i>	<t>cant:ar</t></v>
<v><i>abotifarrar</i>	<t>cant:ar</t></v>
<v><i>abrandar</i>	<t>cant:ar</t></v>
<v><i>abraonar</i>	<t>cant:ar</t></v>
<v><i>abrasar</i>	<t>cant:ar</t></v>
<v><i>abrasir</i>	<t>serv:ir</t></v>
<v><i>abraçallar</i>	<t>cant:ar</t></v>
<v><i>abraçar</i>	<t>comen:çar</t></v>
<v><i>abreujar</i>	<t>enve:jar</t></v>
<v><i>abreviar</i>	<t>canvi:ar</t></v>
<v><i>abrigallar</i>	<t>cant:ar</t></v>
<v><i>abrigar</i>	<t>preg:ar</t></v>
<v><i>abrilejar</i>	<t>enve:jar</t></v>
<v><i>abrillantar</i>	<t>cant:ar</t></v>
<v><i>abrinar</i>	<t>cant:ar</t></v>
<v><i>abriolar</i>	<t>cant:ar</t></v>
<v><i>abrivar</i>	<t>cant:ar</t></v>
<v><i>abrogar</i>	<t>preg:ar</t></v>
<v><i>abromar</i>	<t>cant:ar</t></v>
<v><i>abroquerar</i>	<t>cant:ar</t></v>
<v><i>abrusar</i>	<t>cant:ar</t></v>
<v><i>abscindir</i>	<t>serv:ir</t></v>
<v><i>absentar</i>	<t>cant:ar</t></v>
<v><i>absoldre</i>	<t>per:dre</t></v>
<v><i>absolutitzar</i>	<t>cant:ar</t></v>
<v><i>absorbir</i>	<t>serv:ir</t></v>
<v><i>abstenir</i>	<t>prev:enir</t></v>
<v><i>abstergir</i>	<t>serv:ir</t></v>
<v><i>abstraure</i>	<t>tr:aure</t></v>
<v><i>abstreure</i>	<t>tr:eure</t></v>
<v><i>abuixar</i>	<t>cant:ar</t></v>
<v><i>abundar</i>	<t>cant:ar</t></v>
<v><i>aburgesar</i>	<t>cant:ar</t></v>
<v><i>abusar</i>	<t>cant:ar</t></v>
<v><i>acabalar</i>	<t>cant:ar</t></v>
<v><i>acabar</i>	<t>cant:ar</t></v>
<v><i>acabdillar</i>	<t>cant:ar</t></v>
<v><i>academitzar</i>	<t>cant:ar</t></v>
<v><i>acagallonar</i>	<t>cant:ar</t></v>
<v><i>acalar</i>	<t>cant:ar</t></v>
<v><i>acalorar</i>	<t>cant:ar</t></v>
<v><i>acampanar</i>	<t>cant:ar</t></v>
<v><i>acampar</i>	<t>cant:ar</t></v>
<v><i>acamussar</i>	<t>cant:ar</t></v>
<v><i>acanalar</i>	<t>cant:ar</t></v>
<v><i>acanar</i>	<t>cant:ar</t></v>
<v><i>acanissar</i>	<t>cant:ar</t></v>
<v><i>acanonar</i>	<t>cant:ar</t></v>
<v><i>acantonar</i>	<t>cant:ar</t></v>
<v><i>acanyar</i>	<t>cant:ar</t></v>
<v><i>acaparar</i>	<t>cant:ar</t></v>
<v><i>acaptar</i>	<t>cant:ar</t></v>
<v><i>acaramel·lar</i>	<t>cant:ar</t></v>
<v><i>acaramullar</i>	<t>cant:ar</t></v>
<v><i>acarar</i>	<t>cant:ar</t></v>
<v><i>acarcanyar</i>	<t>cant:ar</t></v>
<v><i>acariciar</i>	<t>canvi:ar</t></v>
<v><i>acarnissar</i>	<t>cant:ar</t></v>
<v><i>acaronar</i>	<t>cant:ar</t></v>
<v><i>acarrerar</i>	<t>cant:ar</t></v>
<v><i>acastellanar</i>	<t>cant:ar</t></v>
<v><i>acastellar</i>	<t>cant:ar</t></v>
<v><i>acatalanar</i>	<t>cant:ar</t></v>
<v><i>acatar</i>	<t>cant:ar</t></v>
<v><i>acatarrar</i>	<t>cant:ar</t></v>
<v><i>acatxar</i>	<t>cant:ar</t></v>
<v><i>acaçar</i>	<t>comen:çar</t></v>
<v><i>accedir</i>	<t>serv:ir</t></v>
<v><i>accelerar</i>	<t>cant:ar</t></v>
<v><i>accentuar</i>	<t>evacu:ar</t></v>
<v><i>acceptar</i>	<t>cant:ar</t></v>
<v><i>accidentar</i>	<t>cant:ar</t></v>
<v><i>accionar</i>	<t>cant:ar</t></v>
<v><i>acendrar</i>	<t>cant:ar</t></v>
<v><i>acensar</i>	<t>cant:ar</t></v>
<v><i>acerar</i>	<t>cant:ar</t></v>
<v><i>acetificar</i>	<t>tren:car</t></v>
<v><i>acidar</i>	<t>cant:ar</t></v>
<v><i>acidificar</i>	<t>tren:car</t></v>
<v><i>acidular</i>	<t>cant:ar</t></v>
<v><i>acientar</i>	<t>cant:ar</t></v>
<v><i>aciençar</i>	<t>comen:çar</t></v>
<v><i>acimar</i>	<t>cant:ar</t></v>
<v><i>acivadar</i>	<t>cant:ar</t></v>
<v><i>aclamar</i>	<t>cant:ar</t></v>
<v><i>aclameir</i>	<t>redu:ir</t></v>
<v><i>aclaparar</i>	<t>cant:ar</t></v>
<v><i>aclarir</i>	<t>serv:ir</t></v>
<v><i>aclimatar</i>	<t>cant:ar</t></v>
<v><i>aclivellar</i>	<t>cant:ar</t></v>
<v><i>aclocar</i>	<t>tren:car</t></v>
<v><i>aclofar</i>	<t>cant:ar</t></v>
<v><i>aclotar</i>	<t>cant:ar</t></v>
<v><i>aclucar</i>	<t>tren:car</t></v>
<v><i>acoblar</i>	<t>cant:ar</t></v>
<v><i>acollar</i>	<t>cant:ar</t></v>
<v><i>acollir</i>	<t>c:ollir</t></v>
<v><i>acollonar</i>	<t>cant:ar</t></v>
<v><i>acollonir</i>	<t>serv:ir</t></v>
<v><i>acolorar</i>	<t>cant:ar</t></v>
<v><i>acolorir</i>	<t>serv:ir</t></v>
<v><i>acoltellar</i>	<t>cant:ar</t></v>
<v><i>acomboiar</i>	<t>esgla:iar</t></v>
<v><i>acomiadar</i>	<t>cant:ar</t></v>
<v><i>acomodar</i>	<t>cant:ar</t></v>
<v><i>acompanyar</i>	<t>cant:ar</t></v>
<v><i>acomplexar</i>	<t>cant:ar</t></v>
<v><i>acomplir</i>	<t>compl:ir</t></v>
<v><i>acondiciar</i>	<t>canvi:ar</t></v>
<v><i>aconductar</i>	<t>cant:ar</t></v>
<v><i>aconduir</i>	<t>redu:ir</t></v>
<v><i>aconseguir</i>	<t>serv:ir</t></v>
<v><i>aconsellar</i>	<t>cant:ar</t></v>
<v><i>acontentar</i>	<t>cant:ar</t></v>
<v><i>acopar</i>	<t>cant:ar</t></v>
<v><i>acoquinar</i>	<t>cant:ar</t></v>
<v><i>acorar</i>	<t>cant:ar</t></v>
<v><i>acordar</i>	<t>cant:ar</t></v>
<v><i>acordillar</i>	<t>cant:ar</t></v>
<v><i>acordonar</i>	<t>cant:ar</t></v>
<v><i>acorralar</i>	<t>cant:ar</t></v>
<v><i>acorriolar</i>	<t>cant:ar</t></v>
<v><i>acorruar</i>	<t>evacu:ar</t></v>
<v><i>acostar</i>	<t>cant:ar</t></v>
<v><i>acostumar</i>	<t>cant:ar</t></v>
<v><i>acotar</i>	<t>cant:ar</t></v>
<v><i>acotiar</i>	<t>canvi:ar</t></v>
<v><i>acotxar</i>	<t>cant:ar</t></v>
<v><i>acovardir</i>	<t>serv:ir</t></v>
<v><i>acreditar</i>	<t>cant:ar</t></v>
<v><i>acromatitzar</i>	<t>cant:ar</t></v>
<v><i>acréixer</i>	<t>cr:éixer</t></v>
<v><i>activar</i>	<t>cant:ar</t></v>
<v><i>actualitzar</i>	<t>cant:ar</t></v>
<v><i>actuar</i>	<t>evacu:ar</t></v>
<v><i>acubar</i>	<t>cant:ar</t></v>
<v><i>acubillar</i>	<t>cant:ar</t></v>
<v><i>acudir</i>	<t>:mentir</t></v>
<v><i>acugular</i>	<t>cant:ar</t></v>
<v><i>acuindar</i>	<t>cant:ar</t></v>
<v><i>acuitar</i>	<t>cant:ar</t></v>
<v><i>acular</i>	<t>cant:ar</t></v>
<v><i>aculturar</i>	<t>cant:ar</t></v>
<v><i>acumular</i>	<t>cant:ar</t></v>
<v><i>acunçar</i>	<t>comen:çar</t></v>
<v><i>acurtar</i>	<t>cant:ar</t></v>
<v><i>acurçar</i>	<t>comen:çar</t></v>
<v><i>acusar</i>	<t>cant:ar</t></v>
<v><i>acórrer</i>	<t>c:órrer</t></v>
<v><i>adaptar</i>	<t>cant:ar</t></v>
<v><i>adargar</i>	<t>preg:ar</t></v>
<v><i>addicionar</i>	<t>cant:ar</t></v>
<v><i>adduir</i>	<t>redu:ir</t></v>
<v><i>adelerar</i>	<t>cant:ar</t></v>
<v><i>adelitar</i>	<t>cant:ar</t></v>
<v><i>adequar</i>	<t>enaig:uar</t></v>
<v><i>adesar</i>	<t>cant:ar</t></v>
<v><i>adherir</i>	<t>serv:ir</t></v>
<v><i>adiar</i>	<t>canvi:ar</t></v>
<v><i>adinerar</i>	<t>cant:ar</t></v>
<v><i>adir</i>	<t>serv:ir</t></v>
<v><i>adir-se</i>	<t>:dir</t></v>
<v><i>adjectivar</i>	<t>cant:ar</t></v>
<v><i>adjudicar</i>	<t>tren:car</t></v>
<v><i>adjuntar</i>	<t>cant:ar</t></v>
<v><i>adjurar</i>	<t>cant:ar</t></v>
<v><i>admetre</i>	<t>:perdre</t></v>
<v><i>adminicular</i>	<t>cant:ar</t></v>
<v><i>administrar</i>	<t>cant:ar</t></v>
<v><i>admirar</i>	<t>cant:ar</t></v>
<v><i>adobar</i>	<t>cant:ar</t></v>
<v><i>adobassar</i>	<t>cant:ar</t></v>
<v><i>adoctrinar</i>	<t>cant:ar</t></v>
<v><i>adollar</i>	<t>cant:ar</t></v>
<v><i>adolorar</i>	<t>cant:ar</t></v>
<v><i>adolorir</i>	<t>serv:ir</t></v>
<v><i>adomassar</i>	<t>cant:ar</t></v>
<v><i>adonar</i>	<t>cant:ar</t></v>
<v><i>adondar</i>	<t>cant:ar</t></v>
<v><i>adonitzar</i>	<t>cant:ar</t></v>
<v><i>adoperar</i>	<t>cant:ar</t></v>
<v><i>adoptar</i>	<t>cant:ar</t></v>
<v><i>adorar</i>	<t>cant:ar</t></v>
<v><i>adormir</i>	<t>dorm:ir</t></v>
<v><i>adormissar</i>	<t>cant:ar</t></v>
<v><i>adornar</i>	<t>cant:ar</t></v>
<v><i>adossar</i>	<t>cant:ar</t></v>
<v><i>adotzenar</i>	<t>cant:ar</t></v>
<v><i>adquirir</i>	<t>serv:ir</t></v>
<v><i>adreçar</i>	<t>comen:çar</t></v>
<v><i>adscriure</i>	<t>escri:ure</t></v>
<v><i>adular</i>	<t>cant:ar</t></v>
<v><i>adulterar</i>	<t>cant:ar</t></v>
<v><i>adunar</i>	<t>cant:ar</t></v>
<v><i>advenir</i>	<t>prev:enir</t></v>
<v><i>adverar</i>	<t>cant:ar</t></v>
<v><i>adverbialitzar</i>	<t>cant:ar</t></v>
<v><i>advertir</i>	<t>serv:ir</t></v>
<v><i>advocar</i>	<t>tren:car</t></v>
<v><i>aerificar</i>	<t>tren:car</t></v>
<v><i>afaenar</i>	<t>cant:ar</t></v>
<v><i>afaitar</i>	<t>cant:ar</t></v>
<v><i>afaiçonar</i>	<t>cant:ar</t></v>
<v><i>afalagar</i>	<t>preg:ar</t></v>
<v><i>afalconar</i>	<t>cant:ar</t></v>
<v><i>afal·lerar</i>	<t>cant:ar</t></v>
<v><i>afamar</i>	<t>cant:ar</t></v>
<v><i>afamegar</i>	<t>preg:ar</t></v>
<v><i>afanar</i>	<t>cant:ar</t></v>
<v><i>afanyar</i>	<t>cant:ar</t></v>
<v><i>afarrossar</i>	<t>cant:ar</t></v>
<v><i>afartar</i>	<t>cant:ar</t></v>
<v><i>afavorir</i>	<t>serv:ir</t></v>
<v><i>afeblir</i>	<t>serv:ir</t></v>
<v><i>afeccionar</i>	<t>cant:ar</t></v>
<v><i>afectar</i>	<t>cant:ar</t></v>
<v><i>afegir</i>	<t>serv:ir</t></v>
<v><i>afeixar</i>	<t>cant:ar</t></v>
<v><i>afeixegar</i>	<t>preg:ar</t></v>
<v><i>afeixugar</i>	<t>preg:ar</t></v>
<v><i>afermançar</i>	<t>comen:çar</t></v>
<v><i>afermar</i>	<t>cant:ar</t></v>
<v><i>aferrallar</i>	<t>cant:ar</t></v>
<v><i>aferrar</i>	<t>cant:ar</t></v>
<v><i>aferrissar</i>	<t>cant:ar</t></v>
<v><i>aferrussar</i>	<t>cant:ar</t></v>
<v><i>afetgegar</i>	<t>preg:ar</t></v>
<v><i>afiblar</i>	<t>cant:ar</t></v>
<v><i>aficionar</i>	<t>cant:ar</t></v>
<v><i>afiganyar</i>	<t>cant:ar</t></v>
<v><i>afigurar</i>	<t>cant:ar</t></v>
<v><i>afilar</i>	<t>cant:ar</t></v>
<v><i>afilerar</i>	<t>cant:ar</t></v>
<v><i>afiliar</i>	<t>canvi:ar</t></v>
<v><i>afillar</i>	<t>cant:ar</t></v>
<v><i>afillolar</i>	<t>cant:ar</t></v>
<v><i>afinar</i>	<t>cant:ar</t></v>
<v><i>afirmar</i>	<t>cant:ar</t></v>
<v><i>afitorar</i>	<t>cant:ar</t></v>
<v><i>afixar</i>	<t>cant:ar</t></v>
<v><i>aflacar</i>	<t>tren:car</t></v>
<v><i>aflamar</i>	<t>cant:ar</t></v>
<v><i>aflaquir</i>	<t>serv:ir</t></v>
<v><i>afligir</i>	<t>serv:ir</t></v>
<v><i>aflonjar</i>	<t>enve:jar</t></v>
<v><i>aflorar</i>	<t>cant:ar</t></v>
<v><i>afluir</i>	<t>redu:ir</t></v>
<v><i>afluixar</i>	<t>cant:ar</t></v>
<v><i>afogar</i>	<t>preg:ar</t></v>
<v><i>afollar</i>	<t>cant:ar</t></v>
<v><i>afonar</i>	<t>cant:ar</t></v>
<v><i>aforar</i>	<t>cant:ar</t></v>
<v><i>aforestar</i>	<t>cant:ar</t></v>
<v><i>afrancesar</i>	<t>cant:ar</t></v>
<v><i>afranquir</i>	<t>serv:ir</t></v>
<v><i>afrenellar</i>	<t>cant:ar</t></v>
<v><i>afrevolir</i>	<t>serv:ir</t></v>
<v><i>africar</i>	<t>tren:car</t></v>
<v><i>afrontar</i>	<t>cant:ar</t></v>
<v><i>afuar</i>	<t>evacu:ar</t></v>
<v><i>afusar</i>	<t>cant:ar</t></v>
<v><i>afusellar</i>	<t>cant:ar</t></v>
<v><i>agabellar</i>	<t>cant:ar</t></v>
<v><i>agafar</i>	<t>cant:ar</t></v>
<v><i>agallinar</i>	<t>cant:ar</t></v>
<v><i>agambar</i>	<t>cant:ar</t></v>
<v><i>agarbar</i>	<t>cant:ar</t></v>
<v><i>agarberar</i>	<t>cant:ar</t></v>
<v><i>agarbir</i>	<t>serv:ir</t></v>
<v><i>agarbonar</i>	<t>cant:ar</t></v>
<v><i>agarbuixar</i>	<t>cant:ar</t></v>
<v><i>agarrar</i>	<t>cant:ar</t></v>
<v><i>agarrofar</i>	<t>cant:ar</t></v>
<v><i>agarrotar</i>	<t>cant:ar</t></v>
<v><i>agegantar</i>	<t>cant:ar</t></v>
<v><i>agemolir</i>	<t>serv:ir</t></v>
<v><i>agenciar</i>	<t>canvi:ar</t></v>
<v><i>agenollar</i>	<t>cant:ar</t></v>
<v><i>agençar</i>	<t>comen:çar</t></v>
<v><i>agermanar</i>	<t>cant:ar</t></v>
<v><i>agibellar</i>	<t>cant:ar</t></v>
<v><i>agilitar</i>	<t>cant:ar</t></v>
<v><i>agilitzar</i>	<t>cant:ar</t></v>
<v><i>agitar</i>	<t>cant:ar</t></v>
<v><i>aglanar</i>	<t>cant:ar</t></v>
<v><i>aglevar</i>	<t>cant:ar</t></v>
<v><i>aglomerar</i>	<t>cant:ar</t></v>
<v><i>aglutinar</i>	<t>cant:ar</t></v>
<v><i>agomboiar</i>	<t>esgla:iar</t></v>
<v><i>agombolar</i>	<t>cant:ar</t></v>
<v><i>agonitzar</i>	<t>cant:ar</t></v>
<v><i>agostar</i>	<t>cant:ar</t></v>
<v><i>agostejar</i>	<t>enve:jar</t></v>
<v><i>agotzonar</i>	<t>cant:ar</t></v>
<v><i>agraciar</i>	<t>canvi:ar</t></v>
<v><i>agradar</i>	<t>cant:ar</t></v>
<v><i>agrair</i>	<t>redu:ir</t></v>
<v><i>agranar</i>	<t>cant:ar</t></v>
<v><i>agredir</i>	<t>serv:ir</t></v>
<v><i>agregar</i>	<t>preg:ar</t></v>
<v><i>agrejar</i>	<t>enve:jar</t></v>
<v><i>agremiar</i>	<t>canvi:ar</t></v>
<v><i>agreujar</i>	<t>enve:jar</t></v>
<v><i>agrimar</i>	<t>cant:ar</t></v>
<v><i>agrir</i>	<t>serv:ir</t></v>
<v><i>agrisar</i>	<t>cant:ar</t></v>
<v><i>agrumar</i>	<t>cant:ar</t></v>
<v><i>agrumollar</i>	<t>cant:ar</t></v>
<v><i>agrunsar</i>	<t>cant:ar</t></v>
<v><i>agrupar</i>	<t>cant:ar</t></v>
<v><i>aguaitar</i>	<t>cant:ar</t></v>
<v><i>aguantar</i>	<t>cant:ar</t></v>
<v><i>aguar</i>	    <t>cant:ar</t></v>
<v><i>aguditzar</i>	<t>cant:ar</t></v>
<v><i>aguerrir</i>	<t>serv:ir</t></v>
<v><i>aguisar</i>	<t>cant:ar</t></v>
<v><i>aguissar</i>	<t>cant:ar</t></v>
<v><i>agullonar</i>	<t>cant:ar</t></v>
<v><i>agusar</i>	<t>cant:ar</t></v>
<v><i>aidar</i>	<t>cant:ar</t></v>
<v><i>aiguabarrejar</i>	<t>enve:jar</t></v>
<v><i>aiguabatre</i>	<t>perd:re</t></v>
<v><i>aigualejar</i>	<t>enve:jar</t></v>
<v><i>aigualir</i>	<t>serv:ir</t></v>
<v><i>airejar</i>	<t>enve:jar</t></v>
<v><i>aixafar</i>	<t>cant:ar</t></v>
<v><i>aixafinar</i>	<t>cant:ar</t></v>
<v><i>aixamfranar</i>	<t>cant:ar</t></v>
<v><i>aixaragallar</i>	<t>cant:ar</t></v>
<v><i>aixecar</i>	<t>tren:car</t></v>
<v><i>aixerriar</i>	<t>canvi:ar</t></v>
<v><i>aixoplugar</i>	<t>preg:ar</t></v>
<v><i>ajaure</i>	<t>j:aure</t></v>
<v><i>ajaçar</i>	<t>comen:çar</t></v>
<v><i>ajeure</i>	<t>j:eure</t></v>
<v><i>ajocar</i>	<t>tren:car</t></v>
<v><i>ajornalar</i>	<t>cant:ar</t></v>
<v><i>ajornar</i>	<t>cant:ar</t></v>
<v><i>ajovar</i>	<t>cant:ar</t></v>
<v><i>ajudar</i>	<t>cant:ar</t></v>
<v><i>ajuntar</i>	<t>cant:ar</t></v>
<v><i>ajupir</i>	<t>dorm:ir</t></v>
<v><i>ajustar</i>	<t>cant:ar</t></v>
<v><i>ajusticiar</i>	<t>canvi:ar</t></v>
<v><i>alabar</i>	<t>cant:ar</t></v>
<v><i>alabatre</i>	<t>perd:re</t></v>
<v><i>alambinar</i>	<t>cant:ar</t></v>
<v><i>alapidar</i>	<t>cant:ar</t></v>
<v><i>alar</i>	<t>cant:ar</t></v>
<v><i>alarmar</i>	<t>cant:ar</t></v>
<v><i>albardanejar</i>	<t>enve:jar</t></v>
<v><i>albardar</i>	<t>cant:ar</t></v>
<v><i>albergar</i>	<t>preg:ar</t></v>
<v><i>albirar</i>	<t>cant:ar</t></v>
<v><i>alcadufar</i>	<t>cant:ar</t></v>
<v><i>alcalinitzar</i>	<t>cant:ar</t></v>
<v><i>alcavotejar</i>	<t>enve:jar</t></v>
<v><i>alcofollar</i>	<t>cant:ar</t></v>
<v><i>alcoholitzar</i>	<t>cant:ar</t></v>
<v><i>alegrar</i>	<t>cant:ar</t></v>
<v><i>alejar</i>	<t>enve:jar</t></v>
<v><i>alenar</i>	<t>cant:ar</t></v>
<v><i>alentir</i>	<t>serv:ir</t></v>
<v><i>alertar</i>	<t>cant:ar</t></v>
<v><i>aletejar</i>	<t>enve:jar</t></v>
<v><i>alfabetitzar</i>	<t>cant:ar</t></v>
<v><i>alfarrassar</i>	<t>cant:ar</t></v>
<v><i>alforrar</i>	<t>cant:ar</t></v>
<v><i>algaliar</i>	<t>canvi:ar</t></v>
<v><i>aliar</i>	<t>canvi:ar</t></v>
<v><i>alienar</i>	<t>cant:ar</t></v>
<v><i>alimentar</i>	<t>cant:ar</t></v>
<v><i>alinear</i>	<t>canvi:ar</t></v>
<v><i>aljubar</i>	<t>cant:ar</t></v>
<v><i>allargar</i>	<t>preg:ar</t></v>
<v><i>allargassar</i>	<t>cant:ar</t></v>
<v><i>allejar</i>	<t>enve:jar</t></v>
<v><i>allenyar</i>	<t>cant:ar</t></v>
<v><i>allerar</i>	<t>cant:ar</t></v>
<v><i>alletar</i>	<t>cant:ar</t></v>
<v><i>alleugerar</i>	<t>cant:ar</t></v>
<v><i>alleugerir</i>	<t>serv:ir</t></v>
<v><i>alleujar</i>	<t>enve:jar</t></v>
<v><i>allevar</i>	<t>cant:ar</t></v>
<v><i>alliberar</i>	<t>cant:ar</t></v>
<v><i>alligar</i>	<t>preg:ar</t></v>
<v><i>allisar</i>	<t>cant:ar</t></v>
<v><i>allistar</i>	<t>cant:ar</t></v>
<v><i>allitar</i>	<t>cant:ar</t></v>
<v><i>alliçonar</i>	<t>cant:ar</t></v>
<v><i>allocar</i>	<t>tren:car</t></v>
<v><i>allongar</i>	<t>preg:ar</t></v>
<v><i>allotjar</i>	<t>enve:jar</t></v>
<v><i>alluentar</i>	<t>cant:ar</t></v>
<v><i>allunar</i>	<t>cant:ar</t></v>
<v><i>allunyar</i>	<t>cant:ar</t></v>
<v><i>almescar</i>	<t>tren:car</t></v>
<v><i>almoinar</i>	<t>cant:ar</t></v>
<v><i>alquenar</i>	<t>cant:ar</t></v>
<v><i>alquilar</i>	<t>cant:ar</t></v>
<v><i>altejar</i>	<t>enve:jar</t></v>
<v><i>alterar</i>	<t>cant:ar</t></v>
<v><i>altercar</i>	<t>tren:car</t></v>
<v><i>alternar</i>	<t>cant:ar</t></v>
<v><i>alterquejar</i>	<t>enve:jar</t></v>
<v><i>altificar</i>	<t>tren:car</t></v>
<v><i>altivar</i>	<t>cant:ar</t></v>
<v><i>alullar</i>	<t>cant:ar</t></v>
<v><i>alumenar</i>	<t>cant:ar</t></v>
<v><i>alzinar</i>	<t>cant:ar</t></v>
<v><i>al·legar</i>	<t>preg:ar</t></v>
<v><i>al·legoritzar</i>	<t>cant:ar</t></v>
<v><i>al·literar</i>	<t>cant:ar</t></v>
<v><i>al·lotejar</i>	<t>enve:jar</t></v>
<v><i>al·lucinar</i>	<t>cant:ar</t></v>
<v><i>al·ludir</i>	<t>serv:ir</t></v>
<v><i>alçapremar</i>	<t>cant:ar</t></v>
<v><i>alçar</i>	<t>comen:çar</t></v>
<v><i>alçurar</i>	<t>cant:ar</t></v>
<v><i>amagar</i>	<t>preg:ar</t></v>
<v><i>amagrir</i>	<t>serv:ir</t></v>
<v><i>amainar</i>	<t>cant:ar</t></v>
<v><i>amalgamar</i>	<t>cant:ar</t></v>
<v><i>amanerar</i>	<t>cant:ar</t></v>
<v><i>amanir</i>	<t>serv:ir</t></v>
<v><i>amanollar</i>	<t>cant:ar</t></v>
<v><i>amansar</i>	<t>cant:ar</t></v>
<v><i>amansir</i>	<t>serv:ir</t></v>
<v><i>amanyagar</i>	<t>preg:ar</t></v>
<v><i>amanyogar</i>	<t>preg:ar</t></v>
<v><i>amar</i>	<t>cant:ar</t></v>
<v><i>amarar</i>	<t>cant:ar</t></v>
<v><i>amargantejar</i>	<t>enve:jar</t></v>
<v><i>amargar</i>	<t>preg:ar</t></v>
<v><i>amargenar</i>	<t>cant:ar</t></v>
<v><i>amargotejar</i>	<t>enve:jar</t></v>
<v><i>amarguejar</i>	<t>enve:jar</t></v>
<v><i>amarinar</i>	<t>cant:ar</t></v>
<v><i>amarrar</i>	<t>cant:ar</t></v>
<v><i>amarrir</i>	<t>serv:ir</t></v>
<v><i>amartellar</i>	<t>cant:ar</t></v>
<v><i>amassar</i>	<t>cant:ar</t></v>
<v><i>amatinar</i>	<t>cant:ar</t></v>
<v><i>amatonar</i>	<t>cant:ar</t></v>
<v><i>amaçar</i>	<t>comen:çar</t></v>
<v><i>ambicionar</i>	<t>cant:ar</t></v>
<v><i>ambientar</i>	<t>cant:ar</t></v>
<v><i>amblar</i>	<t>cant:ar</t></v>
<v><i>ambular</i>	<t>cant:ar</t></v>
<v><i>amelar</i>	<t>cant:ar</t></v>
<v><i>amenaçar</i>	<t>comen:çar</t></v>
<v><i>amenitzar</i>	<t>cant:ar</t></v>
<v><i>amerar</i>	<t>cant:ar</t></v>
<v><i>americanitzar</i>	<t>cant:ar</t></v>
<v><i>amidar</i>	<t>cant:ar</t></v>
<v><i>amigar</i>	<t>preg:ar</t></v>
<v><i>amigrançar</i>	<t>comen:çar</t></v>
<v><i>amistançar</i>	<t>comen:çar</t></v>
<v><i>amistar</i>	<t>cant:ar</t></v>
<v><i>amitjanar</i>	<t>cant:ar</t></v>
<v><i>amnistiar</i>	<t>canvi:ar</t></v>
<v><i>amoixar</i>	<t>cant:ar</t></v>
<v><i>amoixir</i>	<t>serv:ir</t></v>
<v><i>amolar</i>	<t>cant:ar</t></v>
<v><i>amollar</i>	<t>cant:ar</t></v>
<v><i>amollegar</i>	<t>preg:ar</t></v>
<v><i>amollir</i>	<t>serv:ir</t></v>
<v><i>amollonar</i>	<t>cant:ar</t></v>
<v><i>amoltonar</i>	<t>cant:ar</t></v>
<v><i>amonedar</i>	<t>cant:ar</t></v>
<v><i>amonestar</i>	<t>cant:ar</t></v>
<v><i>amorejar</i>	<t>enve:jar</t></v>
<v><i>amorosir</i>	<t>serv:ir</t></v>
<v><i>amorrallar</i>	<t>cant:ar</t></v>
<v><i>amorrar</i>	<t>cant:ar</t></v>
<v><i>amorriar</i>	<t>canvi:ar</t></v>
<v><i>amorronir</i>	<t>serv:ir</t></v>
<v><i>amortallar</i>	<t>cant:ar</t></v>
<v><i>amortar</i>	<t>cant:ar</t></v>
<v><i>amorterar</i>	<t>cant:ar</t></v>
<v><i>amortir</i>	<t>serv:ir</t></v>
<v><i>amortitzar</i>	<t>cant:ar</t></v>
<v><i>amotar</i>	<t>cant:ar</t></v>
<v><i>amotinar</i>	<t>cant:ar</t></v>
<v><i>amoïnar</i>	<t>cant:ar</t></v>
<v><i>amplejar</i>	<t>enve:jar</t></v>
<v><i>ampliar</i>	<t>canvi:ar</t></v>
<v><i>amplificar</i>	<t>tren:car</t></v>
<v><i>amprar</i>	<t>cant:ar</t></v>
<v><i>amputar</i>	<t>cant:ar</t></v>
<v><i>amullerar</i>	<t>cant:ar</t></v>
<v><i>amunionar</i>	<t>cant:ar</t></v>
<v><i>amuntanyar</i>	<t>cant:ar</t></v>
<v><i>amuntegar</i>	<t>preg:ar</t></v>
<v><i>amuntonar</i>	<t>cant:ar</t></v>
<v><i>amuradar</i>	<t>cant:ar</t></v>
<v><i>amurar</i>	<t>cant:ar</t></v>
<v><i>anagramatitzar</i>	<t>cant:ar</t></v>
<v><i>analitzar</i>	<t>cant:ar</t></v>
<v><i>anar</i>	<t>cant:ar</t></v>
<v><i>anarquitzar</i>	<t>cant:ar</t></v>
<v><i>anastomitzar</i>	<t>cant:ar</t></v>
<v><i>anatematitzar</i>	<t>cant:ar</t></v>
<v><i>anatomitzar</i>	<t>cant:ar</t></v>
<v><i>ancorar</i>	<t>cant:ar</t></v>
<v><i>andanar</i>	<t>cant:ar</t></v>
<v><i>andarejar</i>	<t>enve:jar</t></v>
<v><i>andoiar</i>	<t>esgla:iar</t></v>
<v><i>anellar</i>	<t>cant:ar</t></v>
<v><i>anestesiar</i>	<t>canvi:ar</t></v>
<v><i>angelicar</i>	<t>tren:car</t></v>
<v><i>angelitzar</i>	<t>cant:ar</t></v>
<v><i>anglicitzar</i>	<t>cant:ar</t></v>
<v><i>angoixar</i>	<t>cant:ar</t></v>
<v><i>anguilejar</i>	<t>enve:jar</t></v>
<v><i>anguniar</i>	<t>canvi:ar</t></v>
<v><i>anguniejar</i>	<t>enve:jar</t></v>
<v><i>anhelar</i>	<t>cant:ar</t></v>
<v><i>anihilar</i>	<t>cant:ar</t></v>
<v><i>animalitzar</i>	<t>cant:ar</t></v>
<v><i>animar</i>	<t>cant:ar</t></v>
<v><i>aniquilar</i>	<t>cant:ar</t></v>
<v><i>anisar</i>	<t>cant:ar</t></v>
<v><i>anivellar</i>	<t>cant:ar</t></v>
<v><i>annexar</i>	<t>cant:ar</t></v>
<v><i>annexionar</i>	<t>cant:ar</t></v>
<v><i>anoditzar</i>	<t>cant:ar</t></v>
<v><i>anomenar</i>	<t>cant:ar</t></v>
<v><i>anorrear</i>	<t>canvi:ar</t></v>
<v><i>anostrar</i>	<t>cant:ar</t></v>
<v><i>anotar</i>	<t>cant:ar</t></v>
<v><i>anquejar</i>	<t>enve:jar</t></v>
<v><i>anquilosar</i>	<t>cant:ar</t></v>
<v><i>ansar</i>	<t>cant:ar</t></v>
<v><i>ansiejar</i>	<t>enve:jar</t></v>
<v><i>antecedir</i>	<t>serv:ir</t></v>
<v><i>antedatar</i>	<t>cant:ar</t></v>
<v><i>anteposar</i>	<t>cant:ar</t></v>
<v><i>anticipar</i>	<t>cant:ar</t></v>
<v><i>antullar</i>	<t>cant:ar</t></v>
<v><i>anul·lar</i>	<t>cant:ar</t></v>
<v><i>anunciar</i>	<t>canvi:ar</t></v>
<v><i>anyellar</i>	<t>cant:ar</t></v>
<v><i>anyocar</i>	<t>tren:car</t></v>
<v><i>aombrar</i>	<t>cant:ar</t></v>
<v><i>apadrinar</i>	<t>cant:ar</t></v>
<v><i>apagar</i>	<t>preg:ar</t></v>
<v><i>apaivagar</i>	<t>preg:ar</t></v>
<v><i>apallar</i>	<t>cant:ar</t></v>
<v><i>apallerar</i>	<t>cant:ar</t></v>
<v><i>apalleronar</i>	<t>cant:ar</t></v>
<v><i>apallissar</i>	<t>cant:ar</t></v>
<v><i>apamar</i>	<t>cant:ar</t></v>
<v><i>apanar</i>	<t>cant:ar</t></v>
<v><i>apanyar</i>	<t>cant:ar</t></v>
<v><i>apanyussar</i>	<t>cant:ar</t></v>
<v><i>aparaular</i>	<t>cant:ar</t></v>
<v><i>aparcar</i>	<t>tren:car</t></v>
<v><i>aparedar</i>	<t>cant:ar</t></v>
<v><i>aparellar</i>	<t>cant:ar</t></v>
<v><i>aparentar</i>	<t>cant:ar</t></v>
<v><i>aparençar</i>	<t>comen:çar</t></v>
<v><i>aparer</i>	<t>perd:re</t></v>
<v><i>apariar</i>	<t>canvi:ar</t></v>
<v><i>aparionar</i>	<t>cant:ar</t></v>
<v><i>aparracar</i>	<t>tren:car</t></v>
<v><i>aparroquianar</i>	<t>cant:ar</t></v>
<v><i>aparroquiar</i>	<t>canvi:ar</t></v>
<v><i>aparrussar</i>	<t>cant:ar</t></v>
<v><i>apartar</i>	<t>cant:ar</t></v>
<v><i>aparèixer</i>	<t>:perdre</t></v>
<v><i>apassar</i>	<t>cant:ar</t></v>
<v><i>apassionar</i>	<t>cant:ar</t></v>
<v><i>apedaçar</i>	<t>comen:çar</t></v>
<v><i>apedregar</i>	<t>preg:ar</t></v>
<v><i>apegar</i>	<t>preg:ar</t></v>
<v><i>apeixar</i>	<t>cant:ar</t></v>
<v><i>apeixir</i>	<t>serv:ir</t></v>
<v><i>apelfar</i>	<t>cant:ar</t></v>
<v><i>apellar</i>	<t>cant:ar</t></v>
<v><i>apel·lar</i>	<t>cant:ar</t></v>
<v><i>apequinar</i>	<t>cant:ar</t></v>
<v><i>apercebre</i>	<t>re:bre</t></v>
<v><i>aperduar</i>	<t>evacu:ar</t></v>
<v><i>apergaminar</i>	<t>cant:ar</t></v>
<v><i>apesarar</i>	<t>cant:ar</t></v>
<v><i>apetir</i>	<t>serv:ir</t></v>
<v><i>apetitar</i>	<t>cant:ar</t></v>
<v><i>apetonar</i>	<t>cant:ar</t></v>
<v><i>apeçonar</i>	<t>cant:ar</t></v>
<v><i>apiadar</i>	<t>cant:ar</t></v>
<v><i>apilar</i>	<t>cant:ar</t></v>
<v><i>apilonar</i>	<t>cant:ar</t></v>
<v><i>apilotar</i>	<t>cant:ar</t></v>
<v><i>apinyar</i>	<t>cant:ar</t></v>
<v><i>apirrossar</i>	<t>cant:ar</t></v>
<v><i>apitrar</i>	<t>cant:ar</t></v>
<v><i>apitxar</i>	<t>cant:ar</t></v>
<v><i>aplacar</i>	<t>tren:car</t></v>
<v><i>aplanar</i>	<t>cant:ar</t></v>
<v><i>aplantillar</i>	<t>cant:ar</t></v>
<v><i>aplançonar</i>	<t>cant:ar</t></v>
<v><i>aplatar</i>	<t>cant:ar</t></v>
<v><i>aplaudir</i>	<t>serv:ir</t></v>
<v><i>aplaçar</i>	<t>comen:çar</t></v>
<v><i>aplegar</i>	<t>preg:ar</t></v>
<v><i>apletar</i>	<t>cant:ar</t></v>
<v><i>aplicar</i>	<t>tren:car</t></v>
<v><i>aplomar</i>	<t>cant:ar</t></v>
<v><i>apocar</i>	<t>tren:car</t></v>
<v><i>apocopar</i>	<t>cant:ar</t></v>
<v><i>apoderar</i>	<t>cant:ar</t></v>
<v><i>apollegar</i>	<t>preg:ar</t></v>
<v><i>apologitzar</i>	<t>cant:ar</t></v>
<v><i>apomar</i>	<t>cant:ar</t></v>
<v><i>apomellar</i>	<t>cant:ar</t></v>
<v><i>aponar</i>	<t>cant:ar</t></v>
<v><i>aponentar</i>	<t>cant:ar</t></v>
<v><i>apoquir</i>	<t>serv:ir</t></v>
<v><i>aporrinar</i>	<t>cant:ar</t></v>
<v><i>aportar</i>	<t>cant:ar</t></v>
<v><i>aporugar</i>	<t>preg:ar</t></v>
<v><i>aposar</i>	<t>cant:ar</t></v>
<v><i>aposentar</i>	<t>cant:ar</t></v>
<v><i>apostar</i>	<t>cant:ar</t></v>
<v><i>apostatar</i>	<t>cant:ar</t></v>
<v><i>apostemar</i>	<t>cant:ar</t></v>
<v><i>apostrofar</i>	<t>cant:ar</t></v>
<v><i>apradar</i>	<t>cant:ar</t></v>
<v><i>apreciar</i>	<t>canvi:ar</t></v>
<v><i>apregonar</i>	<t>cant:ar</t></v>
<v><i>aprehendre</i>	<t>apr:endre</t></v>
<v><i>aprendre</i>	<t>:perdre</t></v>
<v><i>apressar</i>	<t>cant:ar</t></v>
<v><i>aprestar</i>	<t>cant:ar</t></v>
<v><i>apreuar</i>	<t>cant:ar</t></v>
<v><i>aprimar</i>	<t>cant:ar</t></v>
<v><i>aprisiar</i>	<t>canvi:ar</t></v>
<v><i>aprofitar</i>	<t>cant:ar</t></v>
<v><i>aprofundir</i>	<t>serv:ir</t></v>
<v><i>apromptar</i>	<t>cant:ar</t></v>
<v><i>apropar</i>	<t>cant:ar</t></v>
<v><i>apropiar</i>	<t>canvi:ar</t></v>
<v><i>apropinquar</i>	<t>enaig:uar</t></v>
<v><i>aprovar</i>	<t>cant:ar</t></v>
<v><i>aprovisionar</i>	<t>cant:ar</t></v>
<v><i>aproximar</i>	<t>cant:ar</t></v>
<v><i>apugonar</i>	<t>cant:ar</t></v>
<v><i>apujar</i>	<t>enve:jar</t></v>
<v><i>apuntalar</i>	<t>cant:ar</t></v>
<v><i>apuntar</i>	<t>cant:ar</t></v>
<v><i>apunyalar</i>	<t>cant:ar</t></v>
<v><i>apunyegar</i>	<t>preg:ar</t></v>
<v><i>apurar</i>	<t>cant:ar</t></v>
<v><i>aquarterar</i>	<t>cant:ar</t></v>
<v><i>aquedar</i>	<t>cant:ar</t></v>
<v><i>aqueferar</i>	<t>cant:ar</t></v>
<v><i>aquietar</i>	<t>cant:ar</t></v>
<v><i>aquilotar</i>	<t>cant:ar</t></v>
<v><i>aquintanar</i>	<t>cant:ar</t></v>
<v><i>aquissar</i>	<t>cant:ar</t></v>
<v><i>aquistar</i>	<t>cant:ar</t></v>
<v><i>arabitzar</i>	<t>cant:ar</t></v>
<v><i>arbitrar</i>	<t>cant:ar</t></v>
<v><i>arborar</i>	<t>cant:ar</t></v>
<v><i>arbrar</i>	<t>cant:ar</t></v>
<v><i>arcabussejar</i>	<t>enve:jar</t></v>
<v><i>arcar</i>	<t>tren:car</t></v>